namespace ThinkOnErp.Application.DTOs.User;

/// <summary>
/// DTO for user reset password response
/// Contains the temporary password generated by admin
/// </summary>
public class UserResetPasswordDto
{
    /// <summary>
    /// The temporary password generated for the user
    /// </summary>
    public string TemporaryPassword { get; set; } = string.Empty;

    /// <summary>
    /// Message with instructions for the user
    /// </summary>
    public string Message { get; set; } = string.Empty;
}
