SET SERVEROUTPUT ON;
DECLARE
  v_max_id NUMBER;
BEGIN
  FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN ('SYS_BRANCH_SYSTEMS', 'SYS_ROLE_SCREEN_PERMISSIONS', 'SYS_USER_SCREEN_PERMISSIONS', 'SYS_USERS_ROLES', 'SYS_BRANCH')) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'SELECT NVL(MAX("Id"),0) FROM "' || t.table_name || '"' INTO v_max_id;
      IF v_max_id > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE "' || t.table_name || '" MODIFY ("Id" GENERATED BY DEFAULT AS IDENTITY (START WITH ' || (v_max_id + 1) || '))';
        DBMS_OUTPUT.PUT_LINE(t.table_name || ': advanced to ' || (v_max_id + 1));
      END IF;
    EXCEPTION
      WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(t.table_name || ': ' || SQLERRM);
    END;
  END LOOP;
END;
/
EXIT;
