SELECT SCHEMA_USER, COUNT(*) AS cnt FROM SYS_COMPANY GROUP BY SCHEMA_USER HAVING COUNT(*) > 1;
SELECT '---' FROM DUAL;
SELECT COMPANY_SCHEMA, COUNT(*) AS cnt FROM SYS_COMPANY GROUP BY COMPANY_SCHEMA HAVING COUNT(*) > 1;
SELECT '---' FROM DUAL;
SELECT COMPANY_CODE, COUNT(*) AS cnt FROM SYS_COMPANY GROUP BY COMPANY_CODE HAVING COUNT(*) > 1;
SELECT '---' FROM DUAL;
SELECT ID, COMPANY_CODE, COMPANY_SCHEMA FROM SYS_COMPANY ORDER BY ID;
EXIT;
