ALTER TABLE "SYS_BRANCH_SCREEN_PERMISSIONS" DROP CONSTRAINT "FK_SYS_BRANCH_SCREEN_PERMISSIONS_SYS_COMPANY_COMPANY_ID"
/

ALTER TABLE "SYS_BRANCH_SYSTEMS" DROP CONSTRAINT "FK_SYS_BRANCH_SYSTEMS_SYS_COMPANY_COMPANY_ID"
/

DROP TABLE "SYS_COMPANY_SCREEN_PERMISSIONS"
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "SYS_COMPANY_SYSTEMS"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

DROP INDEX "IX_SYS_BRANCH_SYSTEMS_COMPANY_ID"
/

DROP INDEX "IX_SYS_BRANCH_SCREEN_PERMISSIONS_COMPANY_ID"
/

ALTER TABLE "SYS_BRANCH_SYSTEMS" DROP COLUMN "COMPANY_ID"
/

ALTER TABLE "SYS_BRANCH_SCREEN_PERMISSIONS" DROP COLUMN "COMPANY_ID"
/

ALTER TABLE "SYS_COMPANY" ADD "COMPANY_SCHEMA" NVARCHAR2(100)
/

ALTER TABLE "SYS_COMPANY" ADD "CREATED_BY_SUPER_ADMIN_ID" NUMBER(19)
/

CREATE INDEX "IX_SYS_COMPANY_CREATED_BY_SUPER_ADMIN_ID" ON "SYS_COMPANY" ("CREATED_BY_SUPER_ADMIN_ID")
/

ALTER TABLE "SYS_COMPANY" ADD CONSTRAINT "FK_SYS_COMPANY_SYS_SUPER_ADMIN_CREATED_BY_SUPER_ADMIN_ID" FOREIGN KEY ("CREATED_BY_SUPER_ADMIN_ID") REFERENCES "SYS_SUPER_ADMIN" ("Id") ON DELETE SET NULL
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260605221529_AddCompanySchemaAndSuperAdminId', '8.0.11')
/
