ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE TABLE "THINKONERP_NEW1"."TEST_ID2"( "Id" NUMBER(19) NOT NULL, "NAME" NVARCHAR2(100), PRIMARY KEY ("Id"));
CREATE SEQUENCE "THINKONERP_NEW1"."SEQ_TEST_ID2" START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER "THINKONERP_NEW1"."TRI_TEST_ID2" BEFORE INSERT ON "THINKONERP_NEW1"."TEST_ID2" FOR EACH ROW BEGIN SELECT "THINKONERP_NEW1"."SEQ_TEST_ID2".NEXTVAL INTO :NEW."Id" FROM DUAL; END;
/DROP TABLE "THINKONERP_NEW1"."TEST_ID2";
DROP SEQUENCE "THINKONERP_NEW1"."SEQ_TEST_ID2";
EXIT;
