INSERT INTO "SYS_BRANCH_SCREEN_PERMISSIONS" ("BRANCH_ID", "SCREEN_ID", "CAN_VIEW", "CAN_INSERT", "CAN_UPDATE", "CAN_DELETE", "CREATION_DATE", "CREATION_USER", "GRANTED_BY", "GRANTED_DATE", "NOTES", "UPDATE_DATE", "UPDATE_USER") VALUES (999, 999, 1, 1, 1, 1, SYSDATE, 'test', NULL, SYSDATE, 'test', SYSDATE, 'test') RETURNING "Id" INTO :x;
PRINT x;
ROLLBACK;
EXIT;
