-- =====================================================
-- Permissions System - Table Creation Script
-- Phase 1: Core Permission Tables for Multi-Tenant System
-- =====================================================

-- =====================================================
-- 1. SYS_SUPER_ADMIN Table
-- Stores Super Admin accounts with full platform access
-- =====================================================
CREATE TABLE SYS_SUPER_ADMIN (
    ROW_ID NUMBER(19) PRIMARY KEY,
    ROW_DESC NVARCHAR2(200) NOT NULL,
    ROW_DESC_E NVARCHAR2(200) NOT NULL,
    USER_NAME NVARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD NVARCHAR2(500) NOT NULL,
    EMAIL NVARCHAR2(200) UNIQUE,
    PHONE NVARCHAR2(50),
    TWO_FA_SECRET NVARCHAR2(100),
    TWO_FA_ENABLED CHAR(1) DEFAULT '0' CHECK (TWO_FA_ENABLED IN ('0', '1')),
    IS_ACTIVE CHAR(1) DEFAULT '1' CHECK (IS_ACTIVE IN ('0', '1')),
    LAST_LOGIN_DATE DATE,
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE,
    UPDATE_USER NVARCHAR2(100),
    UPDATE_DATE DATE
);

COMMENT ON TABLE SYS_SUPER_ADMIN IS 'Super Admin accounts with full platform control';
COMMENT ON COLUMN SYS_SUPER_ADMIN.TWO_FA_SECRET IS 'TOTP secret for 2FA authentication';
COMMENT ON COLUMN SYS_SUPER_ADMIN.TWO_FA_ENABLED IS '1=Enabled, 0=Disabled';

-- =====================================================
-- 2. SYS_SYSTEM Table
-- Defines available systems (modules) in the platform
-- =====================================================
CREATE TABLE SYS_SYSTEM (
    ROW_ID NUMBER(19) PRIMARY KEY,
    SYSTEM_CODE NVARCHAR2(50) NOT NULL UNIQUE,
    SYSTEM_NAME NVARCHAR2(200) NOT NULL,
    SYSTEM_NAME_E NVARCHAR2(200) NOT NULL,
    DESCRIPTION NVARCHAR2(500),
    DESCRIPTION_E NVARCHAR2(500),
    ICON NVARCHAR2(100),
    DISPLAY_ORDER NUMBER(10) DEFAULT 0,
    IS_ACTIVE CHAR(1) DEFAULT '1' CHECK (IS_ACTIVE IN ('0', '1')),
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE,
    UPDATE_USER NVARCHAR2(100),
    UPDATE_DATE DATE
);

COMMENT ON TABLE SYS_SYSTEM IS 'Available systems/modules (Accounting, Inventory, HR, etc.)';
COMMENT ON COLUMN SYS_SYSTEM.SYSTEM_CODE IS 'Unique code identifier (e.g., accounting, inventory)';
COMMENT ON COLUMN SYS_SYSTEM.DISPLAY_ORDER IS 'Order for displaying in UI';

-- =====================================================
-- 3. SYS_SCREEN Table
-- Defines screens/pages within each system
-- =====================================================
CREATE TABLE SYS_SCREEN (
    ROW_ID NUMBER(19) PRIMARY KEY,
    SYSTEM_ID NUMBER(19) NOT NULL,
    PARENT_SCREEN_ID NUMBER(19),
    SCREEN_CODE NVARCHAR2(100) NOT NULL UNIQUE,
    SCREEN_NAME NVARCHAR2(200) NOT NULL,
    SCREEN_NAME_E NVARCHAR2(200) NOT NULL,
    ROUTE NVARCHAR2(500),
    DESCRIPTION NVARCHAR2(500),
    DESCRIPTION_E NVARCHAR2(500),
    ICON NVARCHAR2(100),
    DISPLAY_ORDER NUMBER(10) DEFAULT 0,
    IS_ACTIVE CHAR(1) DEFAULT '1' CHECK (IS_ACTIVE IN ('0', '1')),
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE,
    UPDATE_USER NVARCHAR2(100),
    UPDATE_DATE DATE,
    CONSTRAINT FK_SCREEN_SYSTEM FOREIGN KEY (SYSTEM_ID) REFERENCES SYS_SYSTEM(ROW_ID),
    CONSTRAINT FK_SCREEN_PARENT FOREIGN KEY (PARENT_SCREEN_ID) REFERENCES SYS_SCREEN(ROW_ID)
);

COMMENT ON TABLE SYS_SCREEN IS 'Screens/pages within each system';
COMMENT ON COLUMN SYS_SCREEN.SCREEN_CODE IS 'Unique code identifier (e.g., invoices_list)';
COMMENT ON COLUMN SYS_SCREEN.PARENT_SCREEN_ID IS 'For nested/hierarchical screens';
COMMENT ON COLUMN SYS_SCREEN.ROUTE IS 'Frontend route path';

-- =====================================================
-- 4. SYS_COMPANY_SYSTEM Table
-- Maps which systems are allowed/blocked per company
-- =====================================================
CREATE TABLE SYS_COMPANY_SYSTEM (
    ROW_ID NUMBER(19) PRIMARY KEY,
    COMPANY_ID NUMBER(19) NOT NULL,
    SYSTEM_ID NUMBER(19) NOT NULL,
    IS_ALLOWED CHAR(1) DEFAULT '1' CHECK (IS_ALLOWED IN ('0', '1')),
    GRANTED_BY NUMBER(19),
    GRANTED_DATE DATE DEFAULT SYSDATE,
    REVOKED_DATE DATE,
    NOTES NVARCHAR2(1000),
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE,
    UPDATE_USER NVARCHAR2(100),
    UPDATE_DATE DATE,
    CONSTRAINT FK_COMPANY_SYSTEM_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES SYS_COMPANY(ROW_ID),
    CONSTRAINT FK_COMPANY_SYSTEM_SYSTEM FOREIGN KEY (SYSTEM_ID) REFERENCES SYS_SYSTEM(ROW_ID),
    CONSTRAINT FK_COMPANY_SYSTEM_GRANTED_BY FOREIGN KEY (GRANTED_BY) REFERENCES SYS_SUPER_ADMIN(ROW_ID),
    CONSTRAINT UK_COMPANY_SYSTEM UNIQUE (COMPANY_ID, SYSTEM_ID)
);

COMMENT ON TABLE SYS_COMPANY_SYSTEM IS 'System access control per company (allow/block)';
COMMENT ON COLUMN SYS_COMPANY_SYSTEM.IS_ALLOWED IS '1=Allowed, 0=Blocked';
COMMENT ON COLUMN SYS_COMPANY_SYSTEM.GRANTED_BY IS 'Super Admin who granted/revoked access';

-- =====================================================
-- 5. SYS_ROLE_SCREEN_PERMISSION Table
-- Screen-level permissions per role (View/Insert/Update/Delete)
-- =====================================================
CREATE TABLE SYS_ROLE_SCREEN_PERMISSION (
    ROW_ID NUMBER(19) PRIMARY KEY,
    ROLE_ID NUMBER(19) NOT NULL,
    SCREEN_ID NUMBER(19) NOT NULL,
    CAN_VIEW CHAR(1) DEFAULT '0' CHECK (CAN_VIEW IN ('0', '1')),
    CAN_INSERT CHAR(1) DEFAULT '0' CHECK (CAN_INSERT IN ('0', '1')),
    CAN_UPDATE CHAR(1) DEFAULT '0' CHECK (CAN_UPDATE IN ('0', '1')),
    CAN_DELETE CHAR(1) DEFAULT '0' CHECK (CAN_DELETE IN ('0', '1')),
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE,
    UPDATE_USER NVARCHAR2(100),
    UPDATE_DATE DATE,
    CONSTRAINT FK_ROLE_SCREEN_PERM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE(ROW_ID),
    CONSTRAINT FK_ROLE_SCREEN_PERM_SCREEN FOREIGN KEY (SCREEN_ID) REFERENCES SYS_SCREEN(ROW_ID),
    CONSTRAINT UK_ROLE_SCREEN UNIQUE (ROLE_ID, SCREEN_ID)
);

COMMENT ON TABLE SYS_ROLE_SCREEN_PERMISSION IS 'Granular screen permissions per role';
COMMENT ON COLUMN SYS_ROLE_SCREEN_PERMISSION.CAN_VIEW IS 'Can view/read the screen';
COMMENT ON COLUMN SYS_ROLE_SCREEN_PERMISSION.CAN_INSERT IS 'Can create new records';
COMMENT ON COLUMN SYS_ROLE_SCREEN_PERMISSION.CAN_UPDATE IS 'Can edit existing records';
COMMENT ON COLUMN SYS_ROLE_SCREEN_PERMISSION.CAN_DELETE IS 'Can delete records';

-- =====================================================
-- 6. SYS_USER_ROLE Table
-- Maps users to roles (many-to-many)
-- =====================================================
CREATE TABLE SYS_USER_ROLE (
    ROW_ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL,
    ROLE_ID NUMBER(19) NOT NULL,
    ASSIGNED_BY NUMBER(19),
    ASSIGNED_DATE DATE DEFAULT SYSDATE,
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USERS(ROW_ID),
    CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE(ROW_ID),
    CONSTRAINT UK_USER_ROLE UNIQUE (USER_ID, ROLE_ID)
);

COMMENT ON TABLE SYS_USER_ROLE IS 'User to role assignments';
COMMENT ON COLUMN SYS_USER_ROLE.ASSIGNED_BY IS 'User ID who assigned this role';

-- =====================================================
-- 7. SYS_USER_SCREEN_PERMISSION Table
-- Direct user-level permission overrides (highest priority)
-- =====================================================
CREATE TABLE SYS_USER_SCREEN_PERMISSION (
    ROW_ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL,
    SCREEN_ID NUMBER(19) NOT NULL,
    CAN_VIEW CHAR(1) DEFAULT '0' CHECK (CAN_VIEW IN ('0', '1')),
    CAN_INSERT CHAR(1) DEFAULT '0' CHECK (CAN_INSERT IN ('0', '1')),
    CAN_UPDATE CHAR(1) DEFAULT '0' CHECK (CAN_UPDATE IN ('0', '1')),
    CAN_DELETE CHAR(1) DEFAULT '0' CHECK (CAN_DELETE IN ('0', '1')),
    ASSIGNED_BY NUMBER(19),
    ASSIGNED_DATE DATE DEFAULT SYSDATE,
    NOTES NVARCHAR2(1000),
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE,
    UPDATE_USER NVARCHAR2(100),
    UPDATE_DATE DATE,
    CONSTRAINT FK_USER_SCREEN_PERM_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USERS(ROW_ID),
    CONSTRAINT FK_USER_SCREEN_PERM_SCREEN FOREIGN KEY (SCREEN_ID) REFERENCES SYS_SCREEN(ROW_ID),
    CONSTRAINT UK_USER_SCREEN UNIQUE (USER_ID, SCREEN_ID)
);

COMMENT ON TABLE SYS_USER_SCREEN_PERMISSION IS 'Direct user-level permission overrides (takes precedence over role permissions)';
COMMENT ON COLUMN SYS_USER_SCREEN_PERMISSION.ASSIGNED_BY IS 'Super Admin or Company Admin who set this override';

-- =====================================================
-- 8. SYS_AUDIT_LOG Table
-- Comprehensive audit trail for all permission changes
-- =====================================================
CREATE TABLE SYS_AUDIT_LOG (
    ROW_ID NUMBER(19) PRIMARY KEY,
    ACTOR_TYPE NVARCHAR2(50) NOT NULL CHECK (ACTOR_TYPE IN ('SUPER_ADMIN', 'COMPANY_ADMIN', 'USER')),
    ACTOR_ID NUMBER(19) NOT NULL,
    COMPANY_ID NUMBER(19),
    ACTION NVARCHAR2(100) NOT NULL,
    ENTITY_TYPE NVARCHAR2(100) NOT NULL,
    ENTITY_ID NUMBER(19),
    OLD_VALUE CLOB,
    NEW_VALUE CLOB,
    IP_ADDRESS NVARCHAR2(50),
    USER_AGENT NVARCHAR2(500),
    CREATION_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_AUDIT_LOG_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES SYS_COMPANY(ROW_ID)
);

COMMENT ON TABLE SYS_AUDIT_LOG IS 'Comprehensive audit trail for all system changes';
COMMENT ON COLUMN SYS_AUDIT_LOG.ACTOR_TYPE IS 'Type of user performing action';
COMMENT ON COLUMN SYS_AUDIT_LOG.ACTION IS 'Action performed (CREATE, UPDATE, DELETE, etc.)';
COMMENT ON COLUMN SYS_AUDIT_LOG.OLD_VALUE IS 'JSON of old values';
COMMENT ON COLUMN SYS_AUDIT_LOG.NEW_VALUE IS 'JSON of new values';

-- =====================================================
-- Create Indexes for Performance
-- =====================================================
CREATE INDEX IDX_COMPANY_SYSTEM_COMPANY ON SYS_COMPANY_SYSTEM(COMPANY_ID);
CREATE INDEX IDX_COMPANY_SYSTEM_SYSTEM ON SYS_COMPANY_SYSTEM(SYSTEM_ID);
CREATE INDEX IDX_ROLE_SCREEN_PERM_ROLE ON SYS_ROLE_SCREEN_PERMISSION(ROLE_ID);
CREATE INDEX IDX_ROLE_SCREEN_PERM_SCREEN ON SYS_ROLE_SCREEN_PERMISSION(SCREEN_ID);
CREATE INDEX IDX_USER_ROLE_USER ON SYS_USER_ROLE(USER_ID);
CREATE INDEX IDX_USER_ROLE_ROLE ON SYS_USER_ROLE(ROLE_ID);
CREATE INDEX IDX_USER_SCREEN_PERM_USER ON SYS_USER_SCREEN_PERMISSION(USER_ID);
CREATE INDEX IDX_USER_SCREEN_PERM_SCREEN ON SYS_USER_SCREEN_PERMISSION(SCREEN_ID);
CREATE INDEX IDX_SCREEN_SYSTEM ON SYS_SCREEN(SYSTEM_ID);
CREATE INDEX IDX_SCREEN_PARENT ON SYS_SCREEN(PARENT_SCREEN_ID);
CREATE INDEX IDX_AUDIT_LOG_COMPANY ON SYS_AUDIT_LOG(COMPANY_ID);
CREATE INDEX IDX_AUDIT_LOG_ACTOR ON SYS_AUDIT_LOG(ACTOR_ID, ACTOR_TYPE);
CREATE INDEX IDX_AUDIT_LOG_ENTITY ON SYS_AUDIT_LOG(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IDX_AUDIT_LOG_DATE ON SYS_AUDIT_LOG(CREATION_DATE);

-- =====================================================
-- Extend Existing Tables
-- =====================================================

-- Add IS_SUPER_ADMIN flag to SYS_USERS table
ALTER TABLE SYS_USERS ADD (
    IS_SUPER_ADMIN CHAR(1) DEFAULT '0' CHECK (IS_SUPER_ADMIN IN ('0', '1'))
);

COMMENT ON COLUMN SYS_USERS.IS_SUPER_ADMIN IS '1=Super Admin (full platform access), 0=Regular user';

-- Add COMPANY_ID to SYS_ROLE table (for multi-tenant role isolation)
-- Note: This assumes SYS_ROLE doesn't already have COMPANY_ID
-- If it does, skip this ALTER statement
-- ALTER TABLE SYS_ROLE ADD (
--     COMPANY_ID NUMBER(19),
--     CONSTRAINT FK_ROLE_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES SYS_COMPANY(ROW_ID)
-- );

-- COMMENT ON COLUMN SYS_ROLE.COMPANY_ID IS 'Company this role belongs to (NULL for global roles)';

COMMIT;

-- =====================================================
-- Script Execution Complete
-- =====================================================
