-- =====================================================
-- ThinkOnErp - Inventory Posting Rules Seed Script
-- =====================================================

BEGIN
    -- Depending on the actual table name (GL_POSTING_RULE), we wrap in a block
    -- to insert missing rules.

    -- INV_RECEIPT
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'INV_RECEIPT' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('INV_RECEIPT', 'Inventory Receipt', '114301', '212101', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- INV_LANDED_COST_FREIGHT
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'INV_LANDED_COST_FREIGHT' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('INV_LANDED_COST_FREIGHT', 'Landed Cost - Freight', '114301', '531101', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- INV_LANDED_COST_CUSTOMS
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'INV_LANDED_COST_CUSTOMS' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('INV_LANDED_COST_CUSTOMS', 'Landed Cost - Customs', '114301', '531102', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- INV_COGS
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'INV_COGS' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('INV_COGS', 'Cost of Goods Sold', '511101', '114301', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- INV_ISSUE_WIP
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'INV_ISSUE_WIP' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('INV_ISSUE_WIP', 'Issue to WIP', '114201', '114101', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- INV_COMPLETE
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'INV_COMPLETE' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('INV_COMPLETE', 'WIP Completion', '114301', '114201', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- INV_ADJUST_SURPLUS
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'INV_ADJUST_SURPLUS' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('INV_ADJUST_SURPLUS', 'Adjustment - Surplus', '114301', '532102', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- INV_ADJUST_SHORTAGE
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'INV_ADJUST_SHORTAGE' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('INV_ADJUST_SHORTAGE', 'Adjustment - Shortage', '532102', '114301', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- INV_WRITEOFF
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'INV_WRITEOFF' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('INV_WRITEOFF', 'Inventory Write-off', '532103', '114301', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- INV_OBSOLESCENCE
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'INV_OBSOLESCENCE' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('INV_OBSOLESCENCE', 'Inventory Obsolescence', '532103', '114501', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- SALES_RETURN_GOOD
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'SALES_RETURN_GOOD' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('SALES_RETURN_GOOD', 'Sales Return (Good)', '114301', '511101', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- SALES_RETURN_DAMAGED
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'SALES_RETURN_DAMAGED' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('SALES_RETURN_DAMAGED', 'Sales Return (Damaged)', '532103', '511101', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- INV_OPENING_BALANCE
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'INV_OPENING_BALANCE' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('INV_OPENING_BALANCE', 'Inventory Opening Balance', '114301', '311101', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- BRANCH_TRANSFER
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'BRANCH_TRANSFER' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('BRANCH_TRANSFER', 'Branch Transfer', '114301', '114301', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    -- AP_BILL_VARIANCE
    MERGE INTO GL_POSTING_RULE tgt
    USING (SELECT 'AP_BILL_VARIANCE' AS RULE_CODE FROM DUAL) src
    ON (tgt.RULE_CODE = src.RULE_CODE)
    WHEN NOT MATCHED THEN
        INSERT (RULE_CODE, RULE_NAME, DEBIT_ACCOUNT, CREDIT_ACCOUNT, MODULE, IS_ACTIVE, CREATION_USER, CREATION_DATE)
        VALUES ('AP_BILL_VARIANCE', 'AP Bill Variance', '532101', '212101', 'INVENTORY', 1, 'SYSTEM', SYSTIMESTAMP);

    COMMIT;
END;
/
