-- ==============================================================================
-- 103_Seed_Payment_Methods_SysCode.sql
-- Seed Payment Methods (CODE_MGR = 17) into SYS_CODE for ThinkOn ERP
-- ==============================================================================

MERGE INTO "SYS_CODE" t
USING (SELECT 17 AS m, 0 AS n, 1 AS l, N'طرق الدفع' AS d, 'PaymentMethods' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 17 AS m, 0 AS n, 2 AS l, 'Payment Methods' AS d, 'PaymentMethods' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 1: Cash
MERGE INTO "SYS_CODE" t
USING (SELECT 17 AS m, 1 AS n, 1 AS l, N'نقدي' AS d, 'Cash' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 17 AS m, 1 AS n, 2 AS l, 'Cash' AS d, 'Cash' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 2: Credit
MERGE INTO "SYS_CODE" t
USING (SELECT 17 AS m, 2 AS n, 1 AS l, N'آجل / ذمم' AS d, 'Credit' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 17 AS m, 2 AS n, 2 AS l, 'Credit / On Account' AS d, 'Credit' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 3: Card / POS
MERGE INTO "SYS_CODE" t
USING (SELECT 17 AS m, 3 AS n, 1 AS l, N'شبكة / بطاقة / مدى' AS d, 'Card' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 17 AS m, 3 AS n, 2 AS l, 'Card / POS' AS d, 'Card' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 4: Bank Transfer
MERGE INTO "SYS_CODE" t
USING (SELECT 17 AS m, 4 AS n, 1 AS l, N'تحويل بنكي' AS d, 'BankTransfer' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 17 AS m, 4 AS n, 2 AS l, 'Bank Transfer' AS d, 'BankTransfer' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 5: Cheque
MERGE INTO "SYS_CODE" t
USING (SELECT 17 AS m, 5 AS n, 1 AS l, N'شيك' AS d, 'Cheque' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 17 AS m, 5 AS n, 2 AS l, 'Cheque' AS d, 'Cheque' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

COMMIT;
