-- ==============================================================================
-- 105_Seed_Inventory_SysCodes.sql
-- Seed Inventory Lookup Codes into SYS_CODE for ThinkOn ERP:
--   - CODE_MGR = 18: Item Types (مخزني، غير مخزني، خدمي، طقم، تجميعي)
--   - CODE_MGR = 19: Costing Methods (المتوسط المرجح، FIFO، التمييز الفعلي، المعياري)
--   - CODE_MGR = 20: BOM Types (طقم مبيعات، تجميع إنتاجي، تفكيك)
--   - CODE_MGR = 21: Stock Transaction Types (أنواع حركات المخزون)
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. CODE_MGR = 18 : Item Types
-- ------------------------------------------------------------------------------
MERGE INTO "SYS_CODE" t
USING (SELECT 18 AS m, 0 AS n, 1 AS l, N'أنواع الأصناف' AS d, 'ItemTypes' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 18 AS m, 0 AS n, 2 AS l, 'Item Types' AS d, 'ItemTypes' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 1: Stock
MERGE INTO "SYS_CODE" t
USING (SELECT 18 AS m, 1 AS n, 1 AS l, N'مخزني' AS d, 'Stock' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 18 AS m, 1 AS n, 2 AS l, 'Stock' AS d, 'Stock' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 2: NonStock
MERGE INTO "SYS_CODE" t
USING (SELECT 18 AS m, 2 AS n, 1 AS l, N'غير مخزني' AS d, 'NonStock' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 18 AS m, 2 AS n, 2 AS l, 'Non-Stock' AS d, 'NonStock' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 3: Service
MERGE INTO "SYS_CODE" t
USING (SELECT 18 AS m, 3 AS n, 1 AS l, N'خدمي' AS d, 'Service' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 18 AS m, 3 AS n, 2 AS l, 'Service' AS d, 'Service' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 4: Kit
MERGE INTO "SYS_CODE" t
USING (SELECT 18 AS m, 4 AS n, 1 AS l, N'طقم / كيت' AS d, 'Kit' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 18 AS m, 4 AS n, 2 AS l, 'Kit' AS d, 'Kit' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 5: Assembly
MERGE INTO "SYS_CODE" t
USING (SELECT 18 AS m, 5 AS n, 1 AS l, N'تجميعي / تصنيعي' AS d, 'Assembly' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 18 AS m, 5 AS n, 2 AS l, 'Assembly' AS d, 'Assembly' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);


-- ------------------------------------------------------------------------------
-- 2. CODE_MGR = 19 : Costing Methods
-- ------------------------------------------------------------------------------
MERGE INTO "SYS_CODE" t
USING (SELECT 19 AS m, 0 AS n, 1 AS l, N'طرق احتساب التكلفة' AS d, 'CostingMethods' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 19 AS m, 0 AS n, 2 AS l, 'Costing Methods' AS d, 'CostingMethods' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 1: WeightedAverage
MERGE INTO "SYS_CODE" t
USING (SELECT 19 AS m, 1 AS n, 1 AS l, N'المتوسط المرجح' AS d, 'WeightedAverage' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 19 AS m, 1 AS n, 2 AS l, 'Weighted Average' AS d, 'WeightedAverage' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 2: Fifo
MERGE INTO "SYS_CODE" t
USING (SELECT 19 AS m, 2 AS n, 1 AS l, N'الوارد أولاً صادر أولاً (FIFO)' AS d, 'Fifo' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 19 AS m, 2 AS n, 2 AS l, 'First In, First Out (FIFO)' AS d, 'Fifo' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 3: SpecificId
MERGE INTO "SYS_CODE" t
USING (SELECT 19 AS m, 3 AS n, 1 AS l, N'التمييز المحدد / التكلفة الفعلية' AS d, 'SpecificId' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 19 AS m, 3 AS n, 2 AS l, 'Specific Identification' AS d, 'SpecificId' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 4: Standard
MERGE INTO "SYS_CODE" t
USING (SELECT 19 AS m, 4 AS n, 1 AS l, N'التكلفة المعيارية' AS d, 'Standard' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 19 AS m, 4 AS n, 2 AS l, 'Standard Cost' AS d, 'Standard' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);


-- ------------------------------------------------------------------------------
-- 3. CODE_MGR = 20 : BOM Types
-- ------------------------------------------------------------------------------
MERGE INTO "SYS_CODE" t
USING (SELECT 20 AS m, 0 AS n, 1 AS l, N'أنواع هياكل التجميع وقوائم المواد' AS d, 'BomTypes' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 20 AS m, 0 AS n, 2 AS l, 'Bill of Materials (BOM) Types' AS d, 'BomTypes' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 1: SalesKit
MERGE INTO "SYS_CODE" t
USING (SELECT 20 AS m, 1 AS n, 1 AS l, N'طقم مبيعات (Sales Kit)' AS d, 'SalesKit' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 20 AS m, 1 AS n, 2 AS l, 'Sales Kit' AS d, 'SalesKit' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 2: ProductionAssembly
MERGE INTO "SYS_CODE" t
USING (SELECT 20 AS m, 2 AS n, 1 AS l, N'تجميع إنتاجي (Production Assembly)' AS d, 'ProductionAssembly' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 20 AS m, 2 AS n, 2 AS l, 'Production Assembly' AS d, 'ProductionAssembly' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 3: Disassembly
MERGE INTO "SYS_CODE" t
USING (SELECT 20 AS m, 3 AS n, 1 AS l, N'تفكيك (Disassembly)' AS d, 'Disassembly' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 20 AS m, 3 AS n, 2 AS l, 'Disassembly' AS d, 'Disassembly' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);


-- ------------------------------------------------------------------------------
-- 4. CODE_MGR = 21 : Stock Transaction Types
-- ------------------------------------------------------------------------------
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 0 AS n, 1 AS l, N'أنواع حركات المخزون' AS d, 'StockTransactionTypes' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 0 AS n, 2 AS l, 'Stock Transaction Types' AS d, 'StockTransactionTypes' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 1001: LOCAL_CASH_SALES
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 1001 AS n, 1 AS l, N'مبيعات محلية نقدية' AS d, 'LOCAL_CASH_SALES' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 1001 AS n, 2 AS l, 'Local Cash Sales' AS d, 'LOCAL_CASH_SALES' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 1002: LOCAL_CREDIT_SALES
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 1002 AS n, 1 AS l, N'مبيعات محلية ذمم/آجل' AS d, 'LOCAL_CREDIT_SALES' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 1002 AS n, 2 AS l, 'Local Credit Sales' AS d, 'LOCAL_CREDIT_SALES' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 1003: EXPORT_SALES
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 1003 AS n, 1 AS l, N'مبيعات تصدير خارجي' AS d, 'EXPORT_SALES' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 1003 AS n, 2 AS l, 'Export Sales' AS d, 'EXPORT_SALES' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 1004: POS_SALES
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 1004 AS n, 1 AS l, N'مبيعات نقاط بيع تجزئة' AS d, 'POS_SALES' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 1004 AS n, 2 AS l, 'POS Retail Sales' AS d, 'POS_SALES' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 1501: SALES_RETURN_RESTOCK
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 1501 AS n, 1 AS l, N'مردود مبيعات سليم' AS d, 'SALES_RETURN_RESTOCK' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 1501 AS n, 2 AS l, 'Sales Return (Restock)' AS d, 'SALES_RETURN_RESTOCK' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 1502: SALES_RETURN_SCRAP
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 1502 AS n, 1 AS l, N'مردود مبيعات تالف/هالك' AS d, 'SALES_RETURN_SCRAP' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 1502 AS n, 2 AS l, 'Sales Return (Scrap)' AS d, 'SALES_RETURN_SCRAP' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 2001: LOCAL_PURCHASE
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 2001 AS n, 1 AS l, N'مشتريات محلية بضاعة' AS d, 'LOCAL_PURCHASE' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 2001 AS n, 2 AS l, 'Local Purchases' AS d, 'LOCAL_PURCHASE' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 2003: IMPORT_PURCHASE
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 2003 AS n, 1 AS l, N'مشتريات استيراد خارجي' AS d, 'IMPORT_PURCHASE' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 2003 AS n, 2 AS l, 'Import Purchases' AS d, 'IMPORT_PURCHASE' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 2501: PURCHASE_RETURN
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 2501 AS n, 1 AS l, N'مردود مشتريات لمورد' AS d, 'PURCHASE_RETURN' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 2501 AS n, 2 AS l, 'Purchase Return' AS d, 'PURCHASE_RETURN' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 3001: OPENING_STOCK
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3001 AS n, 1 AS l, N'سند إدخال رصيد افتتاحي' AS d, 'OPENING_STOCK' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3001 AS n, 2 AS l, 'Opening Stock Inbound' AS d, 'OPENING_STOCK' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 3002: STOCK_SURPLUS
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3002 AS n, 1 AS l, N'سند إدخال تسوية زيادة' AS d, 'STOCK_SURPLUS' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3002 AS n, 2 AS l, 'Stock Count Surplus' AS d, 'STOCK_SURPLUS' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 3003: FREE_SAMPLES_IN
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3003 AS n, 1 AS l, N'سند إدخال عينات وهدايا' AS d, 'FREE_SAMPLES_IN' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3003 AS n, 2 AS l, 'Free Samples Inbound' AS d, 'FREE_SAMPLES_IN' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 3011: STOCK_SHORTAGE
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3011 AS n, 1 AS l, N'سند إخراج تسوية عجز' AS d, 'STOCK_SHORTAGE' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3011 AS n, 2 AS l, 'Stock Count Shortage' AS d, 'STOCK_SHORTAGE' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 3012: SCRAP_WRITEOFF
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3012 AS n, 1 AS l, N'سند إخراج إتلاف وهالك' AS d, 'SCRAP_WRITEOFF' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3012 AS n, 2 AS l, 'Scrap & Damage Write-Off' AS d, 'SCRAP_WRITEOFF' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 3014: INTERNAL_USE
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3014 AS n, 1 AS l, N'سند إخراج استهلاك أقسام' AS d, 'INTERNAL_USE' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3014 AS n, 2 AS l, 'Internal Consumption' AS d, 'INTERNAL_USE' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 3501: INTERNAL_TRANSFER
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3501 AS n, 1 AS l, N'تحويل بين مستودعات' AS d, 'INTERNAL_TRANSFER' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 3501 AS n, 2 AS l, 'Internal Warehouse Transfer' AS d, 'INTERNAL_TRANSFER' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 4001: SALES_QUOTATION
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 4001 AS n, 1 AS l, N'عرض أسعار لعميل' AS d, 'SALES_QUOTATION' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 4001 AS n, 2 AS l, 'Sales Quotation' AS d, 'SALES_QUOTATION' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

-- 4004: PURCHASE_ORDER
MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 4004 AS n, 1 AS l, N'أمر شراء لمورد' AS d, 'PURCHASE_ORDER' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

MERGE INTO "SYS_CODE" t
USING (SELECT 21 AS m, 4004 AS n, 2 AS l, 'Purchase Order' AS d, 'PURCHASE_ORDER' AS v FROM dual) s
ON (t."CODE_MGR" = s.m AND t."CODE_MNR" = s.n AND t."CODE_LANG" = s.l)
WHEN MATCHED THEN UPDATE SET t."CODE_DESC" = s.d, t."CODE_VALUE" = s.v, t."IS_ACTIVE" = 1, t."UPDATE_DATE" = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT ("CODE_MGR", "CODE_MNR", "CODE_LANG", "CODE_DESC", "CODE_VALUE", "IS_ACTIVE", "CREATION_USER", "CREATION_DATE")
VALUES (s.m, s.n, s.l, s.d, s.v, 1, 'SEED', SYSTIMESTAMP);

COMMIT;
