-- ==============================================================================
-- 107_Add_Tax_To_INV_ITEM.sql
-- Add TaxRateId, TaxGroupId, IsTaxExempt, and TaxExemptionReasonCode to INV_ITEM
-- ==============================================================================

-- 1. Alter INV_ITEM to add tax columns
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "INV_ITEM" ADD ("TAX_RATE_ID" NUMBER(19) NULL)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "INV_ITEM" ADD ("TAX_GROUP_ID" NUMBER(19) NULL)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "INV_ITEM" ADD ("IS_TAX_EXEMPT" NUMBER(1) DEFAULT 0 NOT NULL)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "INV_ITEM" ADD ("TAX_EXEMPTION_REASON_CODE" NVARCHAR2(50) NULL)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 2. Indexes
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "IX_INV_ITEM_TAX_RATE_ID" ON "INV_ITEM"("TAX_RATE_ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "IX_INV_ITEM_TAX_GROUP_ID" ON "INV_ITEM"("TAX_GROUP_ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 3. Foreign Keys (if TAX_RATE and TAX_GROUP tables exist)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "INV_ITEM" ADD CONSTRAINT "FK_INV_ITEM_TAX_RATE" FOREIGN KEY ("TAX_RATE_ID") REFERENCES "TAX_RATE"("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2275 AND SQLCODE != -942 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "INV_ITEM" ADD CONSTRAINT "FK_INV_ITEM_TAX_GROUP" FOREIGN KEY ("TAX_GROUP_ID") REFERENCES "TAX_GROUP"("ID")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2275 AND SQLCODE != -942 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 4. Default existing items to standard 15% VAT rate if available
BEGIN
    EXECUTE IMMEDIATE '
    UPDATE "INV_ITEM"
    SET "TAX_RATE_ID" = (
        SELECT "ID" FROM "TAX_RATE" WHERE "TAX_RATE_CODE" = ''VAT_15'' AND ROWNUM = 1
    )
    WHERE "TAX_RATE_ID" IS NULL AND "IS_TAX_EXEMPT" = 0
    ';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

COMMIT;
