-- =====================================================
-- Permissions System - Stored Procedures
-- Phase 2: CRUD procedures for permission tables
-- =====================================================

-- =====================================================
-- SYS_SYSTEM Procedures
-- =====================================================

-- Get all systems
CREATE OR REPLACE PROCEDURE SP_SYS_SYSTEM_GET_ALL(
    P_RESULT_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RESULT_CURSOR FOR
    SELECT ROW_ID, SYSTEM_CODE, SYSTEM_NAME, SYSTEM_NAME_E, DESCRIPTION, DESCRIPTION_E,
           ICON, DISPLAY_ORDER, IS_ACTIVE, CREATION_USER, CREATION_DATE, UPDATE_USER, UPDATE_DATE
    FROM SYS_SYSTEM
    WHERE IS_ACTIVE = '1'
    ORDER BY DISPLAY_ORDER, SYSTEM_NAME;
END;
/

-- Get system by ID
CREATE OR REPLACE PROCEDURE SP_SYS_SYSTEM_GET_BY_ID(
    P_ROW_ID IN NUMBER,
    P_RESULT_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RESULT_CURSOR FOR
    SELECT ROW_ID, SYSTEM_CODE, SYSTEM_NAME, SYSTEM_NAME_E, DESCRIPTION, DESCRIPTION_E,
           ICON, DISPLAY_ORDER, IS_ACTIVE, CREATION_USER, CREATION_DATE, UPDATE_USER, UPDATE_DATE
    FROM SYS_SYSTEM
    WHERE ROW_ID = P_ROW_ID;
END;
/

-- Create system
CREATE OR REPLACE PROCEDURE SP_SYS_SYSTEM_CREATE(
    P_SYSTEM_CODE IN NVARCHAR2,
    P_SYSTEM_NAME IN NVARCHAR2,
    P_SYSTEM_NAME_E IN NVARCHAR2,
    P_DESCRIPTION IN NVARCHAR2,
    P_DESCRIPTION_E IN NVARCHAR2,
    P_ICON IN NVARCHAR2,
    P_DISPLAY_ORDER IN NUMBER,
    P_CREATION_USER IN NVARCHAR2,
    P_NEW_ID OUT NUMBER
)
AS
BEGIN
    SELECT SEQ_SYS_SYSTEM.NEXTVAL INTO P_NEW_ID FROM DUAL;
    
    INSERT INTO SYS_SYSTEM (
        ROW_ID, SYSTEM_CODE, SYSTEM_NAME, SYSTEM_NAME_E, DESCRIPTION, DESCRIPTION_E,
        ICON, DISPLAY_ORDER, IS_ACTIVE, CREATION_USER, CREATION_DATE
    ) VALUES (
        P_NEW_ID, P_SYSTEM_CODE, P_SYSTEM_NAME, P_SYSTEM_NAME_E, P_DESCRIPTION, P_DESCRIPTION_E,
        P_ICON, P_DISPLAY_ORDER, '1', P_CREATION_USER, SYSDATE
    );
    
    COMMIT;
END;
/

-- Update system
CREATE OR REPLACE PROCEDURE SP_SYS_SYSTEM_UPDATE(
    P_ROW_ID IN NUMBER,
    P_SYSTEM_CODE IN NVARCHAR2,
    P_SYSTEM_NAME IN NVARCHAR2,
    P_SYSTEM_NAME_E IN NVARCHAR2,
    P_DESCRIPTION IN NVARCHAR2,
    P_DESCRIPTION_E IN NVARCHAR2,
    P_ICON IN NVARCHAR2,
    P_DISPLAY_ORDER IN NUMBER,
    P_UPDATE_USER IN NVARCHAR2
)
AS
BEGIN
    UPDATE SYS_SYSTEM
    SET SYSTEM_CODE = P_SYSTEM_CODE,
        SYSTEM_NAME = P_SYSTEM_NAME,
        SYSTEM_NAME_E = P_SYSTEM_NAME_E,
        DESCRIPTION = P_DESCRIPTION,
        DESCRIPTION_E = P_DESCRIPTION_E,
        ICON = P_ICON,
        DISPLAY_ORDER = P_DISPLAY_ORDER,
        UPDATE_USER = P_UPDATE_USER,
        UPDATE_DATE = SYSDATE
    WHERE ROW_ID = P_ROW_ID;
    
    COMMIT;
END;
/

-- Delete system (soft delete)
CREATE OR REPLACE PROCEDURE SP_SYS_SYSTEM_DELETE(
    P_ROW_ID IN NUMBER,
    P_UPDATE_USER IN NVARCHAR2
)
AS
BEGIN
    UPDATE SYS_SYSTEM
    SET IS_ACTIVE = '0',
        UPDATE_USER = P_UPDATE_USER,
        UPDATE_DATE = SYSDATE
    WHERE ROW_ID = P_ROW_ID;
    
    COMMIT;
END;
/

-- =====================================================
-- SYS_SCREEN Procedures
-- =====================================================

-- Get all screens
CREATE OR REPLACE PROCEDURE SP_SYS_SCREEN_GET_ALL(
    P_RESULT_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RESULT_CURSOR FOR
    SELECT ROW_ID, SYSTEM_ID, PARENT_SCREEN_ID, SCREEN_CODE, SCREEN_NAME, SCREEN_NAME_E,
           ROUTE, DESCRIPTION, DESCRIPTION_E, ICON, DISPLAY_ORDER, IS_ACTIVE,
           CREATION_USER, CREATION_DATE, UPDATE_USER, UPDATE_DATE
    FROM SYS_SCREEN
    WHERE IS_ACTIVE = '1'
    ORDER BY SYSTEM_ID, DISPLAY_ORDER, SCREEN_NAME;
END;
/

-- Get screens by system ID
CREATE OR REPLACE PROCEDURE SP_SYS_SCREEN_GET_BY_SYSTEM(
    P_SYSTEM_ID IN NUMBER,
    P_RESULT_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RESULT_CURSOR FOR
    SELECT ROW_ID, SYSTEM_ID, PARENT_SCREEN_ID, SCREEN_CODE, SCREEN_NAME, SCREEN_NAME_E,
           ROUTE, DESCRIPTION, DESCRIPTION_E, ICON, DISPLAY_ORDER, IS_ACTIVE,
           CREATION_USER, CREATION_DATE, UPDATE_USER, UPDATE_DATE
    FROM SYS_SCREEN
    WHERE SYSTEM_ID = P_SYSTEM_ID
      AND IS_ACTIVE = '1'
    ORDER BY DISPLAY_ORDER, SCREEN_NAME;
END;
/

-- Get screen by ID
CREATE OR REPLACE PROCEDURE SP_SYS_SCREEN_GET_BY_ID(
    P_ROW_ID IN NUMBER,
    P_RESULT_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RESULT_CURSOR FOR
    SELECT ROW_ID, SYSTEM_ID, PARENT_SCREEN_ID, SCREEN_CODE, SCREEN_NAME, SCREEN_NAME_E,
           ROUTE, DESCRIPTION, DESCRIPTION_E, ICON, DISPLAY_ORDER, IS_ACTIVE,
           CREATION_USER, CREATION_DATE, UPDATE_USER, UPDATE_DATE
    FROM SYS_SCREEN
    WHERE ROW_ID = P_ROW_ID;
END;
/

-- Create screen
CREATE OR REPLACE PROCEDURE SP_SYS_SCREEN_CREATE(
    P_SYSTEM_ID IN NUMBER,
    P_PARENT_SCREEN_ID IN NUMBER,
    P_SCREEN_CODE IN NVARCHAR2,
    P_SCREEN_NAME IN NVARCHAR2,
    P_SCREEN_NAME_E IN NVARCHAR2,
    P_ROUTE IN NVARCHAR2,
    P_DESCRIPTION IN NVARCHAR2,
    P_DESCRIPTION_E IN NVARCHAR2,
    P_ICON IN NVARCHAR2,
    P_DISPLAY_ORDER IN NUMBER,
    P_CREATION_USER IN NVARCHAR2,
    P_NEW_ID OUT NUMBER
)
AS
BEGIN
    SELECT SEQ_SYS_SCREEN.NEXTVAL INTO P_NEW_ID FROM DUAL;
    
    INSERT INTO SYS_SCREEN (
        ROW_ID, SYSTEM_ID, PARENT_SCREEN_ID, SCREEN_CODE, SCREEN_NAME, SCREEN_NAME_E,
        ROUTE, DESCRIPTION, DESCRIPTION_E, ICON, DISPLAY_ORDER, IS_ACTIVE,
        CREATION_USER, CREATION_DATE
    ) VALUES (
        P_NEW_ID, P_SYSTEM_ID, P_PARENT_SCREEN_ID, P_SCREEN_CODE, P_SCREEN_NAME, P_SCREEN_NAME_E,
        P_ROUTE, P_DESCRIPTION, P_DESCRIPTION_E, P_ICON, P_DISPLAY_ORDER, '1',
        P_CREATION_USER, SYSDATE
    );
    
    COMMIT;
END;
/

-- Update screen
CREATE OR REPLACE PROCEDURE SP_SYS_SCREEN_UPDATE(
    P_ROW_ID IN NUMBER,
    P_SYSTEM_ID IN NUMBER,
    P_PARENT_SCREEN_ID IN NUMBER,
    P_SCREEN_CODE IN NVARCHAR2,
    P_SCREEN_NAME IN NVARCHAR2,
    P_SCREEN_NAME_E IN NVARCHAR2,
    P_ROUTE IN NVARCHAR2,
    P_DESCRIPTION IN NVARCHAR2,
    P_DESCRIPTION_E IN NVARCHAR2,
    P_ICON IN NVARCHAR2,
    P_DISPLAY_ORDER IN NUMBER,
    P_UPDATE_USER IN NVARCHAR2
)
AS
BEGIN
    UPDATE SYS_SCREEN
    SET SYSTEM_ID = P_SYSTEM_ID,
        PARENT_SCREEN_ID = P_PARENT_SCREEN_ID,
        SCREEN_CODE = P_SCREEN_CODE,
        SCREEN_NAME = P_SCREEN_NAME,
        SCREEN_NAME_E = P_SCREEN_NAME_E,
        ROUTE = P_ROUTE,
        DESCRIPTION = P_DESCRIPTION,
        DESCRIPTION_E = P_DESCRIPTION_E,
        ICON = P_ICON,
        DISPLAY_ORDER = P_DISPLAY_ORDER,
        UPDATE_USER = P_UPDATE_USER,
        UPDATE_DATE = SYSDATE
    WHERE ROW_ID = P_ROW_ID;
    
    COMMIT;
END;
/

-- Delete screen (soft delete)
CREATE OR REPLACE PROCEDURE SP_SYS_SCREEN_DELETE(
    P_ROW_ID IN NUMBER,
    P_UPDATE_USER IN NVARCHAR2
)
AS
BEGIN
    UPDATE SYS_SCREEN
    SET IS_ACTIVE = '0',
        UPDATE_USER = P_UPDATE_USER,
        UPDATE_DATE = SYSDATE
    WHERE ROW_ID = P_ROW_ID;
    
    COMMIT;
END;
/

-- =====================================================
-- SYS_COMPANY_SYSTEM Procedures
-- =====================================================

-- Get company systems
CREATE OR REPLACE PROCEDURE SP_SYS_COMPANY_SYSTEM_GET(
    P_COMPANY_ID IN NUMBER,
    P_RESULT_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RESULT_CURSOR FOR
    SELECT cs.ROW_ID, cs.COMPANY_ID, cs.SYSTEM_ID, cs.IS_ALLOWED, cs.GRANTED_BY,
           cs.GRANTED_DATE, cs.REVOKED_DATE, cs.NOTES,
           s.SYSTEM_CODE, s.SYSTEM_NAME, s.SYSTEM_NAME_E
    FROM SYS_COMPANY_SYSTEM cs
    INNER JOIN SYS_SYSTEM s ON cs.SYSTEM_ID = s.ROW_ID
    WHERE cs.COMPANY_ID = P_COMPANY_ID
    ORDER BY s.DISPLAY_ORDER, s.SYSTEM_NAME;
END;
/

-- Set company system access
CREATE OR REPLACE PROCEDURE SP_SYS_COMPANY_SYSTEM_SET(
    P_COMPANY_ID IN NUMBER,
    P_SYSTEM_ID IN NUMBER,
    P_IS_ALLOWED IN CHAR,
    P_GRANTED_BY IN NUMBER,
    P_NOTES IN NVARCHAR2,
    P_CREATION_USER IN NVARCHAR2
)
AS
    V_COUNT NUMBER;
    V_ROW_ID NUMBER;
BEGIN
    -- Check if record exists
    SELECT COUNT(*) INTO V_COUNT
    FROM SYS_COMPANY_SYSTEM
    WHERE COMPANY_ID = P_COMPANY_ID AND SYSTEM_ID = P_SYSTEM_ID;
    
    IF V_COUNT > 0 THEN
        -- Update existing record
        UPDATE SYS_COMPANY_SYSTEM
        SET IS_ALLOWED = P_IS_ALLOWED,
            GRANTED_BY = P_GRANTED_BY,
            GRANTED_DATE = CASE WHEN P_IS_ALLOWED = '1' THEN SYSDATE ELSE GRANTED_DATE END,
            REVOKED_DATE = CASE WHEN P_IS_ALLOWED = '0' THEN SYSDATE ELSE NULL END,
            NOTES = P_NOTES,
            UPDATE_USER = P_CREATION_USER,
            UPDATE_DATE = SYSDATE
        WHERE COMPANY_ID = P_COMPANY_ID AND SYSTEM_ID = P_SYSTEM_ID;
    ELSE
        -- Insert new record
        SELECT SEQ_SYS_COMPANY_SYSTEM.NEXTVAL INTO V_ROW_ID FROM DUAL;
        
        INSERT INTO SYS_COMPANY_SYSTEM (
            ROW_ID, COMPANY_ID, SYSTEM_ID, IS_ALLOWED, GRANTED_BY, GRANTED_DATE,
            NOTES, CREATION_USER, CREATION_DATE
        ) VALUES (
            V_ROW_ID, P_COMPANY_ID, P_SYSTEM_ID, P_IS_ALLOWED, P_GRANTED_BY, SYSDATE,
            P_NOTES, P_CREATION_USER, SYSDATE
        );
    END IF;
    
    COMMIT;
END;
/

-- =====================================================
-- SYS_ROLE_SCREEN_PERMISSION Procedures
-- =====================================================

-- Get role screen permissions
CREATE OR REPLACE PROCEDURE SP_SYS_ROLE_SCREEN_PERM_GET(
    P_ROLE_ID IN NUMBER,
    P_RESULT_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RESULT_CURSOR FOR
    SELECT rsp.ROW_ID, rsp.ROLE_ID, rsp.SCREEN_ID,
           rsp.CAN_VIEW, rsp.CAN_INSERT, rsp.CAN_UPDATE, rsp.CAN_DELETE,
           s.SCREEN_CODE, s.SCREEN_NAME, s.SCREEN_NAME_E, s.SYSTEM_ID
    FROM SYS_ROLE_SCREEN_PERMISSION rsp
    INNER JOIN SYS_SCREEN s ON rsp.SCREEN_ID = s.ROW_ID
    WHERE rsp.ROLE_ID = P_ROLE_ID
    ORDER BY s.SYSTEM_ID, s.DISPLAY_ORDER, s.SCREEN_NAME;
END;
/

-- Set role screen permission
CREATE OR REPLACE PROCEDURE SP_SYS_ROLE_SCREEN_PERM_SET(
    P_ROLE_ID IN NUMBER,
    P_SCREEN_ID IN NUMBER,
    P_CAN_VIEW IN CHAR,
    P_CAN_INSERT IN CHAR,
    P_CAN_UPDATE IN CHAR,
    P_CAN_DELETE IN CHAR,
    P_CREATION_USER IN NVARCHAR2
)
AS
    V_COUNT NUMBER;
    V_ROW_ID NUMBER;
BEGIN
    -- Check if record exists
    SELECT COUNT(*) INTO V_COUNT
    FROM SYS_ROLE_SCREEN_PERMISSION
    WHERE ROLE_ID = P_ROLE_ID AND SCREEN_ID = P_SCREEN_ID;
    
    IF V_COUNT > 0 THEN
        -- Update existing record
        UPDATE SYS_ROLE_SCREEN_PERMISSION
        SET CAN_VIEW = P_CAN_VIEW,
            CAN_INSERT = P_CAN_INSERT,
            CAN_UPDATE = P_CAN_UPDATE,
            CAN_DELETE = P_CAN_DELETE,
            UPDATE_USER = P_CREATION_USER,
            UPDATE_DATE = SYSDATE
        WHERE ROLE_ID = P_ROLE_ID AND SCREEN_ID = P_SCREEN_ID;
    ELSE
        -- Insert new record
        SELECT SEQ_SYS_ROLE_SCREEN_PERM.NEXTVAL INTO V_ROW_ID FROM DUAL;
        
        INSERT INTO SYS_ROLE_SCREEN_PERMISSION (
            ROW_ID, ROLE_ID, SCREEN_ID, CAN_VIEW, CAN_INSERT, CAN_UPDATE, CAN_DELETE,
            CREATION_USER, CREATION_DATE
        ) VALUES (
            V_ROW_ID, P_ROLE_ID, P_SCREEN_ID, P_CAN_VIEW, P_CAN_INSERT, P_CAN_UPDATE, P_CAN_DELETE,
            P_CREATION_USER, SYSDATE
        );
    END IF;
    
    COMMIT;
END;
/

-- Delete role screen permission
CREATE OR REPLACE PROCEDURE SP_SYS_ROLE_SCREEN_PERM_DEL(
    P_ROLE_ID IN NUMBER,
    P_SCREEN_ID IN NUMBER
)
AS
BEGIN
    DELETE FROM SYS_ROLE_SCREEN_PERMISSION
    WHERE ROLE_ID = P_ROLE_ID AND SCREEN_ID = P_SCREEN_ID;
    
    COMMIT;
END;
/

-- =====================================================
-- SYS_USER_ROLE Procedures
-- =====================================================

-- Get user roles
CREATE OR REPLACE PROCEDURE SP_SYS_USER_ROLE_GET(
    P_USER_ID IN NUMBER,
    P_RESULT_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RESULT_CURSOR FOR
    SELECT ur.ROW_ID, ur.USER_ID, ur.ROLE_ID, ur.ASSIGNED_BY, ur.ASSIGNED_DATE,
           r.ROW_DESC as ROLE_NAME, r.ROW_DESC_E as ROLE_NAME_E
    FROM SYS_USER_ROLE ur
    INNER JOIN SYS_ROLE r ON ur.ROLE_ID = r.ROW_ID
    WHERE ur.USER_ID = P_USER_ID
    ORDER BY r.ROW_DESC;
END;
/

-- Assign role to user
CREATE OR REPLACE PROCEDURE SP_SYS_USER_ROLE_ASSIGN(
    P_USER_ID IN NUMBER,
    P_ROLE_ID IN NUMBER,
    P_ASSIGNED_BY IN NUMBER,
    P_CREATION_USER IN NVARCHAR2
)
AS
    V_COUNT NUMBER;
    V_ROW_ID NUMBER;
BEGIN
    -- Check if already assigned
    SELECT COUNT(*) INTO V_COUNT
    FROM SYS_USER_ROLE
    WHERE USER_ID = P_USER_ID AND ROLE_ID = P_ROLE_ID;
    
    IF V_COUNT = 0 THEN
        SELECT SEQ_SYS_USER_ROLE.NEXTVAL INTO V_ROW_ID FROM DUAL;
        
        INSERT INTO SYS_USER_ROLE (
            ROW_ID, USER_ID, ROLE_ID, ASSIGNED_BY, ASSIGNED_DATE, CREATION_USER, CREATION_DATE
        ) VALUES (
            V_ROW_ID, P_USER_ID, P_ROLE_ID, P_ASSIGNED_BY, SYSDATE, P_CREATION_USER, SYSDATE
        );
        
        COMMIT;
    END IF;
END;
/

-- Remove role from user
CREATE OR REPLACE PROCEDURE SP_SYS_USER_ROLE_REMOVE(
    P_USER_ID IN NUMBER,
    P_ROLE_ID IN NUMBER
)
AS
BEGIN
    DELETE FROM SYS_USER_ROLE
    WHERE USER_ID = P_USER_ID AND ROLE_ID = P_ROLE_ID;
    
    COMMIT;
END;
/

-- =====================================================
-- SYS_USER_SCREEN_PERMISSION Procedures
-- =====================================================

-- Get user screen permissions (overrides)
CREATE OR REPLACE PROCEDURE SP_SYS_USER_SCREEN_PERM_GET(
    P_USER_ID IN NUMBER,
    P_RESULT_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RESULT_CURSOR FOR
    SELECT usp.ROW_ID, usp.USER_ID, usp.SCREEN_ID,
           usp.CAN_VIEW, usp.CAN_INSERT, usp.CAN_UPDATE, usp.CAN_DELETE,
           usp.ASSIGNED_BY, usp.ASSIGNED_DATE, usp.NOTES,
           s.SCREEN_CODE, s.SCREEN_NAME, s.SCREEN_NAME_E, s.SYSTEM_ID
    FROM SYS_USER_SCREEN_PERMISSION usp
    INNER JOIN SYS_SCREEN s ON usp.SCREEN_ID = s.ROW_ID
    WHERE usp.USER_ID = P_USER_ID
    ORDER BY s.SYSTEM_ID, s.DISPLAY_ORDER, s.SCREEN_NAME;
END;
/

-- Set user screen permission override
CREATE OR REPLACE PROCEDURE SP_SYS_USER_SCREEN_PERM_SET(
    P_USER_ID IN NUMBER,
    P_SCREEN_ID IN NUMBER,
    P_CAN_VIEW IN CHAR,
    P_CAN_INSERT IN CHAR,
    P_CAN_UPDATE IN CHAR,
    P_CAN_DELETE IN CHAR,
    P_ASSIGNED_BY IN NUMBER,
    P_NOTES IN NVARCHAR2,
    P_CREATION_USER IN NVARCHAR2
)
AS
    V_COUNT NUMBER;
    V_ROW_ID NUMBER;
BEGIN
    -- Check if record exists
    SELECT COUNT(*) INTO V_COUNT
    FROM SYS_USER_SCREEN_PERMISSION
    WHERE USER_ID = P_USER_ID AND SCREEN_ID = P_SCREEN_ID;
    
    IF V_COUNT > 0 THEN
        -- Update existing record
        UPDATE SYS_USER_SCREEN_PERMISSION
        SET CAN_VIEW = P_CAN_VIEW,
            CAN_INSERT = P_CAN_INSERT,
            CAN_UPDATE = P_CAN_UPDATE,
            CAN_DELETE = P_CAN_DELETE,
            ASSIGNED_BY = P_ASSIGNED_BY,
            ASSIGNED_DATE = SYSDATE,
            NOTES = P_NOTES,
            UPDATE_USER = P_CREATION_USER,
            UPDATE_DATE = SYSDATE
        WHERE USER_ID = P_USER_ID AND SCREEN_ID = P_SCREEN_ID;
    ELSE
        -- Insert new record
        SELECT SEQ_SYS_USER_SCREEN_PERM.NEXTVAL INTO V_ROW_ID FROM DUAL;
        
        INSERT INTO SYS_USER_SCREEN_PERMISSION (
            ROW_ID, USER_ID, SCREEN_ID, CAN_VIEW, CAN_INSERT, CAN_UPDATE, CAN_DELETE,
            ASSIGNED_BY, ASSIGNED_DATE, NOTES, CREATION_USER, CREATION_DATE
        ) VALUES (
            V_ROW_ID, P_USER_ID, P_SCREEN_ID, P_CAN_VIEW, P_CAN_INSERT, P_CAN_UPDATE, P_CAN_DELETE,
            P_ASSIGNED_BY, SYSDATE, P_NOTES, P_CREATION_USER, SYSDATE
        );
    END IF;
    
    COMMIT;
END;
/

-- Delete user screen permission override
CREATE OR REPLACE PROCEDURE SP_SYS_USER_SCREEN_PERM_DEL(
    P_USER_ID IN NUMBER,
    P_SCREEN_ID IN NUMBER
)
AS
BEGIN
    DELETE FROM SYS_USER_SCREEN_PERMISSION
    WHERE USER_ID = P_USER_ID AND SCREEN_ID = P_SCREEN_ID;
    
    COMMIT;
END;
/

-- =====================================================
-- Permission Resolution Function
-- =====================================================

-- Check if user has permission for a screen action
CREATE OR REPLACE FUNCTION FN_CHECK_USER_PERMISSION(
    P_USER_ID IN NUMBER,
    P_SCREEN_CODE IN NVARCHAR2,
    P_ACTION IN NVARCHAR2  -- 'VIEW', 'INSERT', 'UPDATE', 'DELETE'
) RETURN CHAR
AS
    V_IS_SUPER_ADMIN CHAR(1);
    V_IS_ACTIVE CHAR(1);
    V_COMPANY_ID NUMBER;
    V_SCREEN_ID NUMBER;
    V_SYSTEM_ID NUMBER;
    V_SYSTEM_ALLOWED NUMBER;
    V_USER_OVERRIDE_COUNT NUMBER;
    V_USER_PERMISSION CHAR(1);
    V_ROLE_PERMISSION CHAR(1) := '0';
BEGIN
    -- Step 0: Check if Super Admin
    SELECT IS_SUPER_ADMIN, IS_ACTIVE, BRANCH_ID
    INTO V_IS_SUPER_ADMIN, V_IS_ACTIVE, V_COMPANY_ID
    FROM SYS_USERS
    WHERE ROW_ID = P_USER_ID;
    
    IF V_IS_SUPER_ADMIN = '1' THEN
        RETURN '1';  -- Super Admin has all permissions
    END IF;
    
    -- Step 1: Check if user is active
    IF V_IS_ACTIVE = '0' THEN
        RETURN '0';
    END IF;
    
    -- Get screen and system info
    SELECT s.ROW_ID, s.SYSTEM_ID
    INTO V_SCREEN_ID, V_SYSTEM_ID
    FROM SYS_SCREEN s
    WHERE s.SCREEN_CODE = P_SCREEN_CODE AND s.IS_ACTIVE = '1';
    
    -- Step 2: Check if system is allowed for company (via branch)
    SELECT COUNT(*)
    INTO V_SYSTEM_ALLOWED
    FROM SYS_COMPANY_SYSTEM cs
    INNER JOIN SYS_BRANCH b ON cs.COMPANY_ID = b.PAR_ROW_ID
    WHERE b.ROW_ID = V_COMPANY_ID
      AND cs.SYSTEM_ID = V_SYSTEM_ID
      AND cs.IS_ALLOWED = '1';
    
    IF V_SYSTEM_ALLOWED = 0 THEN
        RETURN '0';  -- System not allowed for this company
    END IF;
    
    -- Step 3: Check user-level override
    SELECT COUNT(*)
    INTO V_USER_OVERRIDE_COUNT
    FROM SYS_USER_SCREEN_PERMISSION
    WHERE USER_ID = P_USER_ID AND SCREEN_ID = V_SCREEN_ID;
    
    IF V_USER_OVERRIDE_COUNT > 0 THEN
        -- User override exists, use it
        IF P_ACTION = 'VIEW' THEN
            SELECT CAN_VIEW INTO V_USER_PERMISSION
            FROM SYS_USER_SCREEN_PERMISSION
            WHERE USER_ID = P_USER_ID AND SCREEN_ID = V_SCREEN_ID;
        ELSIF P_ACTION = 'INSERT' THEN
            SELECT CAN_INSERT INTO V_USER_PERMISSION
            FROM SYS_USER_SCREEN_PERMISSION
            WHERE USER_ID = P_USER_ID AND SCREEN_ID = V_SCREEN_ID;
        ELSIF P_ACTION = 'UPDATE' THEN
            SELECT CAN_UPDATE INTO V_USER_PERMISSION
            FROM SYS_USER_SCREEN_PERMISSION
            WHERE USER_ID = P_USER_ID AND SCREEN_ID = V_SCREEN_ID;
        ELSIF P_ACTION = 'DELETE' THEN
            SELECT CAN_DELETE INTO V_USER_PERMISSION
            FROM SYS_USER_SCREEN_PERMISSION
            WHERE USER_ID = P_USER_ID AND SCREEN_ID = V_SCREEN_ID;
        END IF;
        
        RETURN V_USER_PERMISSION;
    END IF;
    
    -- Step 4: Check role permissions (OR logic across all roles)
    IF P_ACTION = 'VIEW' THEN
        SELECT MAX(rsp.CAN_VIEW)
        INTO V_ROLE_PERMISSION
        FROM SYS_USER_ROLE ur
        INNER JOIN SYS_ROLE_SCREEN_PERMISSION rsp ON ur.ROLE_ID = rsp.ROLE_ID
        WHERE ur.USER_ID = P_USER_ID AND rsp.SCREEN_ID = V_SCREEN_ID;
    ELSIF P_ACTION = 'INSERT' THEN
        SELECT MAX(rsp.CAN_INSERT)
        INTO V_ROLE_PERMISSION
        FROM SYS_USER_ROLE ur
        INNER JOIN SYS_ROLE_SCREEN_PERMISSION rsp ON ur.ROLE_ID = rsp.ROLE_ID
        WHERE ur.USER_ID = P_USER_ID AND rsp.SCREEN_ID = V_SCREEN_ID;
    ELSIF P_ACTION = 'UPDATE' THEN
        SELECT MAX(rsp.CAN_UPDATE)
        INTO V_ROLE_PERMISSION
        FROM SYS_USER_ROLE ur
        INNER JOIN SYS_ROLE_SCREEN_PERMISSION rsp ON ur.ROLE_ID = rsp.ROLE_ID
        WHERE ur.USER_ID = P_USER_ID AND rsp.SCREEN_ID = V_SCREEN_ID;
    ELSIF P_ACTION = 'DELETE' THEN
        SELECT MAX(rsp.CAN_DELETE)
        INTO V_ROLE_PERMISSION
        FROM SYS_USER_ROLE ur
        INNER JOIN SYS_ROLE_SCREEN_PERMISSION rsp ON ur.ROLE_ID = rsp.ROLE_ID
        WHERE ur.USER_ID = P_USER_ID AND rsp.SCREEN_ID = V_SCREEN_ID;
    END IF;
    
    RETURN NVL(V_ROLE_PERMISSION, '0');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN '0';
    WHEN OTHERS THEN
        RETURN '0';
END;
/

COMMIT;

-- =====================================================
-- Script Execution Complete
-- =====================================================
