-- Extend SYS_AUDIT_LOG table for Full Traceability System
-- This script adds columns needed for comprehensive audit logging, request tracing, and compliance monitoring

-- Add new columns to existing SYS_AUDIT_LOG table
ALTER TABLE SYS_AUDIT_LOG ADD (
    CORRELATION_ID NVARCHAR2(100),
    BRANCH_ID NUMBER(19),
    HTTP_METHOD NVARCHAR2(10),
    ENDPOINT_PATH NVARCHAR2(500),
    REQUEST_PAYLOAD CLOB,
    RESPONSE_PAYLOAD CLOB,
    EXECUTION_TIME_MS NUMBER(19),
    STATUS_CODE NUMBER(5),
    EXCEPTION_TYPE NVARCHAR2(200),
    EXCEPTION_MESSAGE NVARCHAR2(4000),
    STACK_TRACE CLOB,
    SEVERITY NVARCHAR2(20) DEFAULT 'Info',
    EVENT_CATEGORY NVARCHAR2(50) DEFAULT 'DataChange',
    METADATA CLOB
);

-- Add foreign key constraint for branch
ALTER TABLE SYS_AUDIT_LOG ADD CONSTRAINT FK_AUDIT_LOG_BRANCH 
    FOREIGN KEY (BRANCH_ID) REFERENCES SYS_BRANCH(ROW_ID);

-- Add comments for new columns
COMMENT ON COLUMN SYS_AUDIT_LOG.CORRELATION_ID IS 'Unique identifier tracking request through system';
COMMENT ON COLUMN SYS_AUDIT_LOG.BRANCH_ID IS 'Foreign key to SYS_BRANCH table for multi-tenant operations';
COMMENT ON COLUMN SYS_AUDIT_LOG.HTTP_METHOD IS 'HTTP method of the API request (GET, POST, PUT, DELETE)';
COMMENT ON COLUMN SYS_AUDIT_LOG.ENDPOINT_PATH IS 'API endpoint path that was called';
COMMENT ON COLUMN SYS_AUDIT_LOG.REQUEST_PAYLOAD IS 'JSON request body (sensitive data masked)';
COMMENT ON COLUMN SYS_AUDIT_LOG.RESPONSE_PAYLOAD IS 'JSON response body (sensitive data masked)';
COMMENT ON COLUMN SYS_AUDIT_LOG.EXECUTION_TIME_MS IS 'Total execution time in milliseconds';
COMMENT ON COLUMN SYS_AUDIT_LOG.STATUS_CODE IS 'HTTP status code of the response';
COMMENT ON COLUMN SYS_AUDIT_LOG.EXCEPTION_TYPE IS 'Type of exception if error occurred';
COMMENT ON COLUMN SYS_AUDIT_LOG.EXCEPTION_MESSAGE IS 'Exception message if error occurred';
COMMENT ON COLUMN SYS_AUDIT_LOG.STACK_TRACE IS 'Full stack trace if exception occurred';
COMMENT ON COLUMN SYS_AUDIT_LOG.SEVERITY IS 'Severity level: Critical, Error, Warning, Info';
COMMENT ON COLUMN SYS_AUDIT_LOG.EVENT_CATEGORY IS 'Category: DataChange, Authentication, Permission, Exception, Configuration, Request';
COMMENT ON COLUMN SYS_AUDIT_LOG.METADATA IS 'Additional JSON metadata for extensibility';

-- Create indexes for query performance
CREATE INDEX IDX_AUDIT_LOG_CORRELATION ON SYS_AUDIT_LOG(CORRELATION_ID);
CREATE INDEX IDX_AUDIT_LOG_BRANCH ON SYS_AUDIT_LOG(BRANCH_ID);
CREATE INDEX IDX_AUDIT_LOG_ENDPOINT ON SYS_AUDIT_LOG(ENDPOINT_PATH);
CREATE INDEX IDX_AUDIT_LOG_CATEGORY ON SYS_AUDIT_LOG(EVENT_CATEGORY);
CREATE INDEX IDX_AUDIT_LOG_SEVERITY ON SYS_AUDIT_LOG(SEVERITY);

-- Composite indexes for common query patterns
CREATE INDEX IDX_AUDIT_LOG_COMPANY_DATE ON SYS_AUDIT_LOG(COMPANY_ID, CREATION_DATE);
CREATE INDEX IDX_AUDIT_LOG_ACTOR_DATE ON SYS_AUDIT_LOG(ACTOR_ID, CREATION_DATE);
CREATE INDEX IDX_AUDIT_LOG_ENTITY_DATE ON SYS_AUDIT_LOG(ENTITY_TYPE, ENTITY_ID, CREATION_DATE);

COMMIT;
