-- Create archive table for long-term audit log storage
-- This table stores audit logs that have exceeded their retention period

CREATE TABLE SYS_AUDIT_LOG_ARCHIVE (
    ROW_ID NUMBER(19) PRIMARY KEY,
    ACTOR_TYPE NVARCHAR2(50) NOT NULL,
    ACTOR_ID NUMBER(19) NOT NULL,
    COMPANY_ID NUMBER(19),
    BRANCH_ID NUMBER(19),
    ACTION NVARCHAR2(100) NOT NULL,
    ENTITY_TYPE NVARCHAR2(100) NOT NULL,
    ENTITY_ID NUMBER(19),
    OLD_VALUE CLOB,
    NEW_VALUE CLOB,
    IP_ADDRESS NVARCHAR2(50),
    USER_AGENT NVARCHAR2(500),
    CORRELATION_ID NVARCHAR2(100),
    HTTP_METHOD NVARCHAR2(10),
    ENDPOINT_PATH NVARCHAR2(500),
    REQUEST_PAYLOAD CLOB,
    RESPONSE_PAYLOAD CLOB,
    EXECUTION_TIME_MS NUMBER(19),
    STATUS_CODE NUMBER(5),
    EXCEPTION_TYPE NVARCHAR2(200),
    EXCEPTION_MESSAGE NVARCHAR2(4000),
    STACK_TRACE CLOB,
    SEVERITY NVARCHAR2(20) DEFAULT 'Info',
    EVENT_CATEGORY NVARCHAR2(50) DEFAULT 'DataChange',
    METADATA CLOB,
    CREATION_DATE DATE,
    ARCHIVED_DATE DATE DEFAULT SYSDATE,
    ARCHIVE_BATCH_ID NUMBER(19),
    CHECKSUM NVARCHAR2(64)
);

-- Create indexes for archive table (fewer than active table for storage efficiency)
CREATE INDEX IDX_ARCHIVE_COMPANY_DATE ON SYS_AUDIT_LOG_ARCHIVE(COMPANY_ID, CREATION_DATE);
CREATE INDEX IDX_ARCHIVE_CORRELATION ON SYS_AUDIT_LOG_ARCHIVE(CORRELATION_ID);
CREATE INDEX IDX_ARCHIVE_BATCH ON SYS_AUDIT_LOG_ARCHIVE(ARCHIVE_BATCH_ID);
CREATE INDEX IDX_ARCHIVE_CATEGORY_DATE ON SYS_AUDIT_LOG_ARCHIVE(EVENT_CATEGORY, CREATION_DATE);

-- Add comments
COMMENT ON TABLE SYS_AUDIT_LOG_ARCHIVE IS 'Archived audit logs for long-term retention and compliance';
COMMENT ON COLUMN SYS_AUDIT_LOG_ARCHIVE.ARCHIVED_DATE IS 'Date when the record was moved to archive';
COMMENT ON COLUMN SYS_AUDIT_LOG_ARCHIVE.ARCHIVE_BATCH_ID IS 'Batch identifier for archival process tracking';
COMMENT ON COLUMN SYS_AUDIT_LOG_ARCHIVE.CHECKSUM IS 'SHA-256 hash for integrity verification';

COMMIT;
