-- Create performance metrics tables for tracking system performance

-- Request performance metrics (aggregated hourly)
CREATE TABLE SYS_PERFORMANCE_METRICS (
    ROW_ID NUMBER(19) PRIMARY KEY,
    ENDPOINT_PATH NVARCHAR2(500) NOT NULL,
    HOUR_TIMESTAMP DATE NOT NULL,
    REQUEST_COUNT NUMBER(19) NOT NULL,
    AVG_EXECUTION_TIME_MS NUMBER(19),
    MIN_EXECUTION_TIME_MS NUMBER(19),
    MAX_EXECUTION_TIME_MS NUMBER(19),
    P50_EXECUTION_TIME_MS NUMBER(19),
    P95_EXECUTION_TIME_MS NUMBER(19),
    P99_EXECUTION_TIME_MS NUMBER(19),
    AVG_DATABASE_TIME_MS NUMBER(19),
    AVG_QUERY_COUNT NUMBER(10,2),
    ERROR_COUNT NUMBER(19),
    CREATION_DATE DATE DEFAULT SYSDATE
);

-- Create sequence for performance metrics
CREATE SEQUENCE SEQ_SYS_PERFORMANCE_METRICS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create index for performance metrics
CREATE INDEX IDX_PERF_ENDPOINT_HOUR ON SYS_PERFORMANCE_METRICS(ENDPOINT_PATH, HOUR_TIMESTAMP);
CREATE INDEX IDX_PERF_HOUR ON SYS_PERFORMANCE_METRICS(HOUR_TIMESTAMP);

-- Add comments
COMMENT ON TABLE SYS_PERFORMANCE_METRICS IS 'Aggregated hourly performance metrics per endpoint';
COMMENT ON COLUMN SYS_PERFORMANCE_METRICS.HOUR_TIMESTAMP IS 'Hour bucket for aggregated metrics';
COMMENT ON COLUMN SYS_PERFORMANCE_METRICS.P50_EXECUTION_TIME_MS IS '50th percentile (median) execution time';
COMMENT ON COLUMN SYS_PERFORMANCE_METRICS.P95_EXECUTION_TIME_MS IS '95th percentile execution time';
COMMENT ON COLUMN SYS_PERFORMANCE_METRICS.P99_EXECUTION_TIME_MS IS '99th percentile execution time';

-- Slow query log table
CREATE TABLE SYS_SLOW_QUERIES (
    ROW_ID NUMBER(19) PRIMARY KEY,
    CORRELATION_ID NVARCHAR2(100),
    SQL_STATEMENT CLOB NOT NULL,
    EXECUTION_TIME_MS NUMBER(19) NOT NULL,
    ROWS_AFFECTED NUMBER(19),
    ENDPOINT_PATH NVARCHAR2(500),
    USER_ID NUMBER(19),
    COMPANY_ID NUMBER(19),
    CREATION_DATE DATE DEFAULT SYSDATE
);

-- Create sequence for slow queries
CREATE SEQUENCE SEQ_SYS_SLOW_QUERIES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create indexes for slow queries
CREATE INDEX IDX_SLOW_QUERY_DATE ON SYS_SLOW_QUERIES(CREATION_DATE);
CREATE INDEX IDX_SLOW_QUERY_TIME ON SYS_SLOW_QUERIES(EXECUTION_TIME_MS);
CREATE INDEX IDX_SLOW_QUERY_CORRELATION ON SYS_SLOW_QUERIES(CORRELATION_ID);

-- Add comments
COMMENT ON TABLE SYS_SLOW_QUERIES IS 'Log of database queries exceeding performance thresholds';
COMMENT ON COLUMN SYS_SLOW_QUERIES.EXECUTION_TIME_MS IS 'Query execution time in milliseconds';

COMMIT;
