-- Create retention policy configuration table

CREATE TABLE SYS_RETENTION_POLICIES (
    ROW_ID NUMBER(19) PRIMARY KEY,
    EVENT_CATEGORY NVARCHAR2(50) NOT NULL UNIQUE,
    RETENTION_DAYS NUMBER(10) NOT NULL,
    ARCHIVE_ENABLED NUMBER(1) DEFAULT 1,
    DESCRIPTION NVARCHAR2(500),
    LAST_MODIFIED_DATE DATE DEFAULT SYSDATE,
    LAST_MODIFIED_BY NUMBER(19)
);

-- Create sequence for retention policies
CREATE SEQUENCE SEQ_SYS_RETENTION_POLICY
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create index for performance
CREATE INDEX IDX_RETENTION_POLICIES_CATEGORY ON SYS_RETENTION_POLICIES(EVENT_CATEGORY);

-- Add foreign key constraint
ALTER TABLE SYS_RETENTION_POLICIES 
ADD CONSTRAINT FK_RETENTION_POLICIES_USER 
FOREIGN KEY (LAST_MODIFIED_BY) REFERENCES SYS_USERS(ROW_ID);

-- Add comments
COMMENT ON TABLE SYS_RETENTION_POLICIES IS 'Data retention policies by event category for compliance';
COMMENT ON COLUMN SYS_RETENTION_POLICIES.EVENT_CATEGORY IS 'Event category: Authentication, DataChange, Financial, PersonalData, Security, Configuration, Request, PerformanceMetrics, PerformanceAggregated, Exception, Permission';
COMMENT ON COLUMN SYS_RETENTION_POLICIES.RETENTION_DAYS IS 'Number of days to retain data before archival';
COMMENT ON COLUMN SYS_RETENTION_POLICIES.ARCHIVE_ENABLED IS '1 = archive after retention, 0 = delete after retention';
COMMENT ON COLUMN SYS_RETENTION_POLICIES.DESCRIPTION IS 'Human-readable description of the retention policy';
COMMENT ON COLUMN SYS_RETENTION_POLICIES.LAST_MODIFIED_DATE IS 'Date when the policy was last modified';
COMMENT ON COLUMN SYS_RETENTION_POLICIES.LAST_MODIFIED_BY IS 'User ID who last modified the policy';

-- Insert default retention policies
INSERT INTO SYS_RETENTION_POLICIES (ROW_ID, EVENT_CATEGORY, RETENTION_DAYS, DESCRIPTION)
VALUES (SEQ_SYS_RETENTION_POLICY.NEXTVAL, 'Authentication', 365, 'Authentication events retained for 1 year');

INSERT INTO SYS_RETENTION_POLICIES (ROW_ID, EVENT_CATEGORY, RETENTION_DAYS, DESCRIPTION)
VALUES (SEQ_SYS_RETENTION_POLICY.NEXTVAL, 'DataChange', 1095, 'Data changes retained for 3 years');

INSERT INTO SYS_RETENTION_POLICIES (ROW_ID, EVENT_CATEGORY, RETENTION_DAYS, DESCRIPTION)
VALUES (SEQ_SYS_RETENTION_POLICY.NEXTVAL, 'Financial', 2555, 'Financial data retained for 7 years (SOX compliance)');

INSERT INTO SYS_RETENTION_POLICIES (ROW_ID, EVENT_CATEGORY, RETENTION_DAYS, DESCRIPTION)
VALUES (SEQ_SYS_RETENTION_POLICY.NEXTVAL, 'PersonalData', 1095, 'Personal data retained for 3 years (GDPR compliance)');

INSERT INTO SYS_RETENTION_POLICIES (ROW_ID, EVENT_CATEGORY, RETENTION_DAYS, DESCRIPTION)
VALUES (SEQ_SYS_RETENTION_POLICY.NEXTVAL, 'Security', 730, 'Security events retained for 2 years');

INSERT INTO SYS_RETENTION_POLICIES (ROW_ID, EVENT_CATEGORY, RETENTION_DAYS, DESCRIPTION)
VALUES (SEQ_SYS_RETENTION_POLICY.NEXTVAL, 'Configuration', 1825, 'Configuration changes retained for 5 years');

INSERT INTO SYS_RETENTION_POLICIES (ROW_ID, EVENT_CATEGORY, RETENTION_DAYS, DESCRIPTION)
VALUES (SEQ_SYS_RETENTION_POLICY.NEXTVAL, 'Request', 90, 'API request logs retained for 90 days');

INSERT INTO SYS_RETENTION_POLICIES (ROW_ID, EVENT_CATEGORY, RETENTION_DAYS, DESCRIPTION)
VALUES (SEQ_SYS_RETENTION_POLICY.NEXTVAL, 'PerformanceMetrics', 90, 'Performance metrics detailed data retained for 90 days');

INSERT INTO SYS_RETENTION_POLICIES (ROW_ID, EVENT_CATEGORY, RETENTION_DAYS, DESCRIPTION)
VALUES (SEQ_SYS_RETENTION_POLICY.NEXTVAL, 'PerformanceAggregated', 365, 'Performance metrics aggregated data retained for 1 year');

INSERT INTO SYS_RETENTION_POLICIES (ROW_ID, EVENT_CATEGORY, RETENTION_DAYS, DESCRIPTION)
VALUES (SEQ_SYS_RETENTION_POLICY.NEXTVAL, 'Exception', 365, 'Exception logs retained for 1 year');

INSERT INTO SYS_RETENTION_POLICIES (ROW_ID, EVENT_CATEGORY, RETENTION_DAYS, DESCRIPTION)
VALUES (SEQ_SYS_RETENTION_POLICY.NEXTVAL, 'Permission', 1095, 'Permission changes retained for 3 years');

COMMIT;
