-- =============================================
-- Company Request Tickets System - Table Creation Script
-- Description: Creates core ticket tables and sequences for the Company Request Tickets system
-- Requirements: 1.1-1.15, 14.1-14.8
-- =============================================

-- =============================================
-- Create Sequences for Ticket System
-- =============================================

-- Sequence for SYS_REQUEST_TICKET table
CREATE SEQUENCE SEQ_SYS_REQUEST_TICKET
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for SYS_TICKET_TYPE table
CREATE SEQUENCE SEQ_SYS_TICKET_TYPE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for SYS_TICKET_STATUS table
CREATE SEQUENCE SEQ_SYS_TICKET_STATUS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for SYS_TICKET_PRIORITY table
CREATE SEQUENCE SEQ_SYS_TICKET_PRIORITY
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for SYS_TICKET_CATEGORY table
CREATE SEQUENCE SEQ_SYS_TICKET_CATEGORY
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for SYS_TICKET_COMMENT table
CREATE SEQUENCE SEQ_SYS_TICKET_COMMENT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for SYS_TICKET_ATTACHMENT table
CREATE SEQUENCE SEQ_SYS_TICKET_ATTACHMENT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- =============================================
-- 1. SYS_TICKET_PRIORITY Table
-- Defines priority levels with SLA targets
-- =============================================
CREATE TABLE SYS_TICKET_PRIORITY (
    ROW_ID NUMBER(19) PRIMARY KEY,
    PRIORITY_NAME_AR NVARCHAR2(50) NOT NULL,
    PRIORITY_NAME_EN NVARCHAR2(50) NOT NULL,
    PRIORITY_LEVEL NUMBER(1) NOT NULL,
    SLA_TARGET_HOURS NUMBER(10,2) NOT NULL,
    ESCALATION_THRESHOLD_HOURS NUMBER(10,2) NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER NVARCHAR2(100),
    UPDATE_DATE DATE,
    
    CONSTRAINT UK_TICKET_PRIORITY_LEVEL UNIQUE (PRIORITY_LEVEL)
);

COMMENT ON TABLE SYS_TICKET_PRIORITY IS 'Ticket priority levels with SLA targets and escalation thresholds';
COMMENT ON COLUMN SYS_TICKET_PRIORITY.PRIORITY_LEVEL IS 'Numeric priority level (1=Critical, 2=High, 3=Medium, 4=Low)';
COMMENT ON COLUMN SYS_TICKET_PRIORITY.SLA_TARGET_HOURS IS 'Target resolution time in hours';
COMMENT ON COLUMN SYS_TICKET_PRIORITY.ESCALATION_THRESHOLD_HOURS IS 'Hours before escalation alert';

-- =============================================
-- 2. SYS_TICKET_STATUS Table
-- Defines ticket status workflow
-- =============================================
CREATE TABLE SYS_TICKET_STATUS (
    ROW_ID NUMBER(19) PRIMARY KEY,
    STATUS_NAME_AR NVARCHAR2(50) NOT NULL,
    STATUS_NAME_EN NVARCHAR2(50) NOT NULL,
    STATUS_CODE NVARCHAR2(20) NOT NULL UNIQUE,
    DISPLAY_ORDER NUMBER(3) NOT NULL,
    IS_FINAL_STATUS CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_FINAL_STATUS IN ('Y', 'N')),
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER NVARCHAR2(100),
    UPDATE_DATE DATE
);

COMMENT ON TABLE SYS_TICKET_STATUS IS 'Ticket status definitions for workflow management';
COMMENT ON COLUMN SYS_TICKET_STATUS.STATUS_CODE IS 'Unique code for programmatic status identification';
COMMENT ON COLUMN SYS_TICKET_STATUS.IS_FINAL_STATUS IS 'Y if status represents ticket completion (Closed/Cancelled)';
COMMENT ON COLUMN SYS_TICKET_STATUS.DISPLAY_ORDER IS 'Order for status display in UI';

-- =============================================
-- 3. SYS_TICKET_TYPE Table
-- Defines ticket types with default priorities and SLA
-- =============================================
CREATE TABLE SYS_TICKET_TYPE (
    ROW_ID NUMBER(19) PRIMARY KEY,
    TYPE_NAME_AR NVARCHAR2(100) NOT NULL,
    TYPE_NAME_EN NVARCHAR2(100) NOT NULL,
    DESCRIPTION_AR NVARCHAR2(500),
    DESCRIPTION_EN NVARCHAR2(500),
    DEFAULT_PRIORITY_ID NUMBER(19) NOT NULL,
    SLA_TARGET_HOURS NUMBER(10,2) NOT NULL,
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER NVARCHAR2(100),
    UPDATE_DATE DATE,
    
    CONSTRAINT FK_TYPE_DEFAULT_PRIORITY FOREIGN KEY (DEFAULT_PRIORITY_ID) REFERENCES SYS_TICKET_PRIORITY(ROW_ID)
);

COMMENT ON TABLE SYS_TICKET_TYPE IS 'Ticket type definitions with default priority and SLA settings';
COMMENT ON COLUMN SYS_TICKET_TYPE.DEFAULT_PRIORITY_ID IS 'Default priority assigned to new tickets of this type';
COMMENT ON COLUMN SYS_TICKET_TYPE.SLA_TARGET_HOURS IS 'Type-specific SLA target (overrides priority default if specified)';

-- =============================================
-- 4. SYS_TICKET_CATEGORY Table
-- Optional categorization for tickets
-- =============================================
CREATE TABLE SYS_TICKET_CATEGORY (
    ROW_ID NUMBER(19) PRIMARY KEY,
    CATEGORY_NAME_AR NVARCHAR2(100) NOT NULL,
    CATEGORY_NAME_EN NVARCHAR2(100) NOT NULL,
    DESCRIPTION_AR NVARCHAR2(500),
    DESCRIPTION_EN NVARCHAR2(500),
    PARENT_CATEGORY_ID NUMBER(19),
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER NVARCHAR2(100),
    UPDATE_DATE DATE,
    
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES SYS_TICKET_CATEGORY(ROW_ID)
);

COMMENT ON TABLE SYS_TICKET_CATEGORY IS 'Optional ticket categorization with hierarchical support';
COMMENT ON COLUMN SYS_TICKET_CATEGORY.PARENT_CATEGORY_ID IS 'Parent category for hierarchical organization';

-- =============================================
-- 5. SYS_REQUEST_TICKET Table (Main Ticket Entity)
-- Core ticket information with multilingual support
-- =============================================
CREATE TABLE SYS_REQUEST_TICKET (
    ROW_ID NUMBER(19) PRIMARY KEY,
    TITLE_AR NVARCHAR2(200) NOT NULL,
    TITLE_EN NVARCHAR2(200) NOT NULL,
    DESCRIPTION NCLOB NOT NULL,
    COMPANY_ID NUMBER(19) NOT NULL,
    BRANCH_ID NUMBER(19) NOT NULL,
    REQUESTER_ID NUMBER(19) NOT NULL,
    ASSIGNEE_ID NUMBER(19),
    TICKET_TYPE_ID NUMBER(19) NOT NULL,
    TICKET_STATUS_ID NUMBER(19) NOT NULL,
    TICKET_PRIORITY_ID NUMBER(19) NOT NULL,
    TICKET_CATEGORY_ID NUMBER(19),
    EXPECTED_RESOLUTION_DATE DATE,
    ACTUAL_RESOLUTION_DATE DATE,
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER NVARCHAR2(100),
    UPDATE_DATE DATE,
    
    -- Foreign Key Constraints
    CONSTRAINT FK_TICKET_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES SYS_COMPANY(ROW_ID),
    CONSTRAINT FK_TICKET_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES SYS_BRANCH(ROW_ID),
    CONSTRAINT FK_TICKET_REQUESTER FOREIGN KEY (REQUESTER_ID) REFERENCES SYS_USERS(ROW_ID),
    CONSTRAINT FK_TICKET_ASSIGNEE FOREIGN KEY (ASSIGNEE_ID) REFERENCES SYS_USERS(ROW_ID),
    CONSTRAINT FK_TICKET_TYPE FOREIGN KEY (TICKET_TYPE_ID) REFERENCES SYS_TICKET_TYPE(ROW_ID),
    CONSTRAINT FK_TICKET_STATUS FOREIGN KEY (TICKET_STATUS_ID) REFERENCES SYS_TICKET_STATUS(ROW_ID),
    CONSTRAINT FK_TICKET_PRIORITY FOREIGN KEY (TICKET_PRIORITY_ID) REFERENCES SYS_TICKET_PRIORITY(ROW_ID),
    CONSTRAINT FK_TICKET_CATEGORY FOREIGN KEY (TICKET_CATEGORY_ID) REFERENCES SYS_TICKET_CATEGORY(ROW_ID),
    
    -- Business Rule Constraints
    CONSTRAINT CHK_RESOLUTION_DATE CHECK (ACTUAL_RESOLUTION_DATE IS NULL OR ACTUAL_RESOLUTION_DATE >= CREATION_DATE),
    CONSTRAINT CHK_EXPECTED_DATE CHECK (EXPECTED_RESOLUTION_DATE IS NULL OR EXPECTED_RESOLUTION_DATE >= CREATION_DATE)
);

COMMENT ON TABLE SYS_REQUEST_TICKET IS 'Main ticket entity with multilingual support and comprehensive tracking';
COMMENT ON COLUMN SYS_REQUEST_TICKET.TITLE_AR IS 'Ticket title in Arabic';
COMMENT ON COLUMN SYS_REQUEST_TICKET.TITLE_EN IS 'Ticket title in English';
COMMENT ON COLUMN SYS_REQUEST_TICKET.DESCRIPTION IS 'Detailed ticket description supporting rich text up to 5000 characters';
COMMENT ON COLUMN SYS_REQUEST_TICKET.EXPECTED_RESOLUTION_DATE IS 'Calculated based on SLA targets and priority';
COMMENT ON COLUMN SYS_REQUEST_TICKET.ACTUAL_RESOLUTION_DATE IS 'Set when ticket status changes to Resolved';

-- =============================================
-- 6. SYS_TICKET_COMMENT Table
-- Ticket comments and communication
-- =============================================
CREATE TABLE SYS_TICKET_COMMENT (
    ROW_ID NUMBER(19) PRIMARY KEY,
    TICKET_ID NUMBER(19) NOT NULL,
    COMMENT_TEXT NCLOB NOT NULL,
    IS_INTERNAL CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_INTERNAL IN ('Y', 'N')),
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT FK_COMMENT_TICKET FOREIGN KEY (TICKET_ID) REFERENCES SYS_REQUEST_TICKET(ROW_ID)
);

COMMENT ON TABLE SYS_TICKET_COMMENT IS 'Ticket comments and communication history';
COMMENT ON COLUMN SYS_TICKET_COMMENT.IS_INTERNAL IS 'Y for admin-only comments, N for public comments';
COMMENT ON COLUMN SYS_TICKET_COMMENT.COMMENT_TEXT IS 'Comment text supporting rich text formatting up to 2000 characters';

-- =============================================
-- 7. SYS_TICKET_ATTACHMENT Table
-- File attachments with Base64 storage
-- =============================================
CREATE TABLE SYS_TICKET_ATTACHMENT (
    ROW_ID NUMBER(19) PRIMARY KEY,
    TICKET_ID NUMBER(19) NOT NULL,
    FILE_NAME NVARCHAR2(255) NOT NULL,
    FILE_SIZE NUMBER(19) NOT NULL,
    MIME_TYPE NVARCHAR2(100) NOT NULL,
    FILE_CONTENT BLOB NOT NULL,
    CREATION_USER NVARCHAR2(100) NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT FK_ATTACHMENT_TICKET FOREIGN KEY (TICKET_ID) REFERENCES SYS_REQUEST_TICKET(ROW_ID),
    CONSTRAINT CHK_FILE_SIZE CHECK (FILE_SIZE > 0 AND FILE_SIZE <= 10485760) -- 10MB limit
);

COMMENT ON TABLE SYS_TICKET_ATTACHMENT IS 'File attachments stored as BLOB with metadata';
COMMENT ON COLUMN SYS_TICKET_ATTACHMENT.FILE_SIZE IS 'File size in bytes (max 10MB)';
COMMENT ON COLUMN SYS_TICKET_ATTACHMENT.MIME_TYPE IS 'File MIME type for validation and download';
COMMENT ON COLUMN SYS_TICKET_ATTACHMENT.FILE_CONTENT IS 'Binary file content stored as BLOB';

-- =============================================
-- Performance Indexes
-- =============================================

-- Indexes for frequent queries on SYS_REQUEST_TICKET
CREATE INDEX IDX_TICKET_COMPANY_BRANCH ON SYS_REQUEST_TICKET(COMPANY_ID, BRANCH_ID);
CREATE INDEX IDX_TICKET_STATUS_PRIORITY ON SYS_REQUEST_TICKET(TICKET_STATUS_ID, TICKET_PRIORITY_ID);
CREATE INDEX IDX_TICKET_ASSIGNEE ON SYS_REQUEST_TICKET(ASSIGNEE_ID);
CREATE INDEX IDX_TICKET_REQUESTER ON SYS_REQUEST_TICKET(REQUESTER_ID);
CREATE INDEX IDX_TICKET_TYPE ON SYS_REQUEST_TICKET(TICKET_TYPE_ID);
CREATE INDEX IDX_TICKET_CREATION_DATE ON SYS_REQUEST_TICKET(CREATION_DATE);
CREATE INDEX IDX_TICKET_RESOLUTION_DATE ON SYS_REQUEST_TICKET(ACTUAL_RESOLUTION_DATE);
CREATE INDEX IDX_TICKET_ACTIVE ON SYS_REQUEST_TICKET(IS_ACTIVE);
CREATE INDEX IDX_TICKET_EXPECTED_DATE ON SYS_REQUEST_TICKET(EXPECTED_RESOLUTION_DATE);

-- Full-text search indexes for titles
CREATE INDEX IDX_TICKET_TITLE_AR ON SYS_REQUEST_TICKET(TITLE_AR);
CREATE INDEX IDX_TICKET_TITLE_EN ON SYS_REQUEST_TICKET(TITLE_EN);

-- Indexes for SYS_TICKET_COMMENT
CREATE INDEX IDX_COMMENT_TICKET ON SYS_TICKET_COMMENT(TICKET_ID);
CREATE INDEX IDX_COMMENT_DATE ON SYS_TICKET_COMMENT(CREATION_DATE);
CREATE INDEX IDX_COMMENT_USER ON SYS_TICKET_COMMENT(CREATION_USER);

-- Indexes for SYS_TICKET_ATTACHMENT
CREATE INDEX IDX_ATTACHMENT_TICKET ON SYS_TICKET_ATTACHMENT(TICKET_ID);
CREATE INDEX IDX_ATTACHMENT_DATE ON SYS_TICKET_ATTACHMENT(CREATION_DATE);

-- Indexes for lookup tables
CREATE INDEX IDX_TICKET_TYPE_ACTIVE ON SYS_TICKET_TYPE(IS_ACTIVE);
CREATE INDEX IDX_TICKET_STATUS_ACTIVE ON SYS_TICKET_STATUS(IS_ACTIVE);
CREATE INDEX IDX_TICKET_PRIORITY_ACTIVE ON SYS_TICKET_PRIORITY(IS_ACTIVE);
CREATE INDEX IDX_TICKET_CATEGORY_ACTIVE ON SYS_TICKET_CATEGORY(IS_ACTIVE);

-- =============================================
-- Insert Default Data
-- =============================================

-- Insert Default Ticket Priorities
INSERT INTO SYS_TICKET_PRIORITY (ROW_ID, PRIORITY_NAME_AR, PRIORITY_NAME_EN, PRIORITY_LEVEL, SLA_TARGET_HOURS, ESCALATION_THRESHOLD_HOURS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_PRIORITY.NEXTVAL, 'حرج', 'Critical', 1, 2, 1, 'system');

INSERT INTO SYS_TICKET_PRIORITY (ROW_ID, PRIORITY_NAME_AR, PRIORITY_NAME_EN, PRIORITY_LEVEL, SLA_TARGET_HOURS, ESCALATION_THRESHOLD_HOURS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_PRIORITY.NEXTVAL, 'عالي', 'High', 2, 8, 6, 'system');

INSERT INTO SYS_TICKET_PRIORITY (ROW_ID, PRIORITY_NAME_AR, PRIORITY_NAME_EN, PRIORITY_LEVEL, SLA_TARGET_HOURS, ESCALATION_THRESHOLD_HOURS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_PRIORITY.NEXTVAL, 'متوسط', 'Medium', 3, 24, 18, 'system');

INSERT INTO SYS_TICKET_PRIORITY (ROW_ID, PRIORITY_NAME_AR, PRIORITY_NAME_EN, PRIORITY_LEVEL, SLA_TARGET_HOURS, ESCALATION_THRESHOLD_HOURS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_PRIORITY.NEXTVAL, 'منخفض', 'Low', 4, 72, 60, 'system');

-- Insert Default Ticket Statuses
INSERT INTO SYS_TICKET_STATUS (ROW_ID, STATUS_NAME_AR, STATUS_NAME_EN, STATUS_CODE, DISPLAY_ORDER, IS_FINAL_STATUS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_STATUS.NEXTVAL, 'مفتوح', 'Open', 'OPEN', 1, 'N', 'system');

INSERT INTO SYS_TICKET_STATUS (ROW_ID, STATUS_NAME_AR, STATUS_NAME_EN, STATUS_CODE, DISPLAY_ORDER, IS_FINAL_STATUS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_STATUS.NEXTVAL, 'قيد التنفيذ', 'In Progress', 'IN_PROGRESS', 2, 'N', 'system');

INSERT INTO SYS_TICKET_STATUS (ROW_ID, STATUS_NAME_AR, STATUS_NAME_EN, STATUS_CODE, DISPLAY_ORDER, IS_FINAL_STATUS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_STATUS.NEXTVAL, 'في انتظار العميل', 'Pending Customer', 'PENDING_CUSTOMER', 3, 'N', 'system');

INSERT INTO SYS_TICKET_STATUS (ROW_ID, STATUS_NAME_AR, STATUS_NAME_EN, STATUS_CODE, DISPLAY_ORDER, IS_FINAL_STATUS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_STATUS.NEXTVAL, 'محلول', 'Resolved', 'RESOLVED', 4, 'N', 'system');

INSERT INTO SYS_TICKET_STATUS (ROW_ID, STATUS_NAME_AR, STATUS_NAME_EN, STATUS_CODE, DISPLAY_ORDER, IS_FINAL_STATUS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_STATUS.NEXTVAL, 'مغلق', 'Closed', 'CLOSED', 5, 'Y', 'system');

INSERT INTO SYS_TICKET_STATUS (ROW_ID, STATUS_NAME_AR, STATUS_NAME_EN, STATUS_CODE, DISPLAY_ORDER, IS_FINAL_STATUS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_STATUS.NEXTVAL, 'ملغي', 'Cancelled', 'CANCELLED', 6, 'Y', 'system');

-- Insert Default Ticket Types
INSERT INTO SYS_TICKET_TYPE (ROW_ID, TYPE_NAME_AR, TYPE_NAME_EN, DESCRIPTION_AR, DESCRIPTION_EN, DEFAULT_PRIORITY_ID, SLA_TARGET_HOURS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_TYPE.NEXTVAL, 'دعم فني', 'Technical Support', 'طلبات الدعم الفني والمساعدة التقنية', 'Technical support and assistance requests', 3, 24, 'system');

INSERT INTO SYS_TICKET_TYPE (ROW_ID, TYPE_NAME_AR, TYPE_NAME_EN, DESCRIPTION_AR, DESCRIPTION_EN, DEFAULT_PRIORITY_ID, SLA_TARGET_HOURS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_TYPE.NEXTVAL, 'تغيير الحساب', 'Account Changes', 'طلبات تعديل بيانات الحساب والصلاحيات', 'Account information and permission change requests', 3, 24, 'system');

INSERT INTO SYS_TICKET_TYPE (ROW_ID, TYPE_NAME_AR, TYPE_NAME_EN, DESCRIPTION_AR, DESCRIPTION_EN, DEFAULT_PRIORITY_ID, SLA_TARGET_HOURS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_TYPE.NEXTVAL, 'طلب خدمة', 'Service Request', 'طلبات الخدمات العامة والاستفسارات', 'General service requests and inquiries', 4, 48, 'system');

INSERT INTO SYS_TICKET_TYPE (ROW_ID, TYPE_NAME_AR, TYPE_NAME_EN, DESCRIPTION_AR, DESCRIPTION_EN, DEFAULT_PRIORITY_ID, SLA_TARGET_HOURS, CREATION_USER)
VALUES (SEQ_SYS_TICKET_TYPE.NEXTVAL, 'بلاغ خطأ', 'Bug Report', 'تقارير الأخطاء والمشاكل التقنية', 'Bug reports and technical issues', 2, 8, 'system');

-- Insert Default Categories
INSERT INTO SYS_TICKET_CATEGORY (ROW_ID, CATEGORY_NAME_AR, CATEGORY_NAME_EN, DESCRIPTION_AR, DESCRIPTION_EN, CREATION_USER)
VALUES (SEQ_SYS_TICKET_CATEGORY.NEXTVAL, 'النظام', 'System', 'مشاكل وطلبات متعلقة بالنظام', 'System-related issues and requests', 'system');

INSERT INTO SYS_TICKET_CATEGORY (ROW_ID, CATEGORY_NAME_AR, CATEGORY_NAME_EN, DESCRIPTION_AR, DESCRIPTION_EN, CREATION_USER)
VALUES (SEQ_SYS_TICKET_CATEGORY.NEXTVAL, 'المحاسبة', 'Accounting', 'طلبات متعلقة بالمحاسبة والمالية', 'Accounting and financial requests', 'system');

INSERT INTO SYS_TICKET_CATEGORY (ROW_ID, CATEGORY_NAME_AR, CATEGORY_NAME_EN, DESCRIPTION_AR, DESCRIPTION_EN, CREATION_USER)
VALUES (SEQ_SYS_TICKET_CATEGORY.NEXTVAL, 'المستخدمين', 'Users', 'إدارة المستخدمين والصلاحيات', 'User management and permissions', 'system');

INSERT INTO SYS_TICKET_CATEGORY (ROW_ID, CATEGORY_NAME_AR, CATEGORY_NAME_EN, DESCRIPTION_AR, DESCRIPTION_EN, CREATION_USER)
VALUES (SEQ_SYS_TICKET_CATEGORY.NEXTVAL, 'التقارير', 'Reports', 'طلبات التقارير والبيانات', 'Reports and data requests', 'system');

COMMIT;

-- =============================================
-- Verification Queries
-- =============================================

-- Verify sequences were created
SELECT sequence_name, min_value, max_value, increment_by, last_number
FROM user_sequences
WHERE sequence_name LIKE 'SEQ_SYS_TICKET%' OR sequence_name = 'SEQ_SYS_REQUEST_TICKET'
ORDER BY sequence_name;

-- Verify tables were created
SELECT table_name, num_rows
FROM user_tables
WHERE table_name LIKE 'SYS_TICKET%' OR table_name = 'SYS_REQUEST_TICKET'
ORDER BY table_name;

-- Verify foreign key constraints
SELECT constraint_name, table_name, r_constraint_name, status
FROM user_constraints
WHERE table_name IN ('SYS_REQUEST_TICKET', 'SYS_TICKET_TYPE', 'SYS_TICKET_COMMENT', 'SYS_TICKET_ATTACHMENT')
AND constraint_type = 'R'
ORDER BY table_name, constraint_name;

-- Verify indexes were created
SELECT index_name, table_name, uniqueness
FROM user_indexes
WHERE table_name LIKE 'SYS_TICKET%' OR table_name = 'SYS_REQUEST_TICKET'
ORDER BY table_name, index_name;

-- Display sample data
SELECT 'Ticket Priorities:' AS INFO FROM DUAL;
SELECT ROW_ID, PRIORITY_NAME_EN, PRIORITY_LEVEL, SLA_TARGET_HOURS FROM SYS_TICKET_PRIORITY ORDER BY PRIORITY_LEVEL;

SELECT 'Ticket Statuses:' AS INFO FROM DUAL;
SELECT ROW_ID, STATUS_NAME_EN, STATUS_CODE, DISPLAY_ORDER, IS_FINAL_STATUS FROM SYS_TICKET_STATUS ORDER BY DISPLAY_ORDER;

SELECT 'Ticket Types:' AS INFO FROM DUAL;
SELECT ROW_ID, TYPE_NAME_EN, DEFAULT_PRIORITY_ID, SLA_TARGET_HOURS FROM SYS_TICKET_TYPE ORDER BY ROW_ID;

SELECT 'Ticket Categories:' AS INFO FROM DUAL;
SELECT ROW_ID, CATEGORY_NAME_EN, PARENT_CATEGORY_ID FROM SYS_TICKET_CATEGORY ORDER BY ROW_ID;
