-- Fix SYS_AUDIT_LOG column data types and sizes to match Full Traceability System requirements
-- This script corrects data types from VARCHAR2 to NVARCHAR2 and increases EXCEPTION_MESSAGE size

-- Modify CORRELATION_ID to use NVARCHAR2
ALTER TABLE SYS_AUDIT_LOG MODIFY (CORRELATION_ID NVARCHAR2(100));

-- Modify HTTP_METHOD to use NVARCHAR2
ALTER TABLE SYS_AUDIT_LOG MODIFY (HTTP_METHOD NVARCHAR2(10));

-- Modify ENDPOINT_PATH to use NVARCHAR2
ALTER TABLE SYS_AUDIT_LOG MODIFY (ENDPOINT_PATH NVARCHAR2(500));

-- Modify EXCEPTION_TYPE to use NVARCHAR2
ALTER TABLE SYS_AUDIT_LOG MODIFY (EXCEPTION_TYPE NVARCHAR2(200));

-- Modify EXCEPTION_MESSAGE to use NVARCHAR2 and increase size to 4000
ALTER TABLE SYS_AUDIT_LOG MODIFY (EXCEPTION_MESSAGE NVARCHAR2(4000));

-- Modify SEVERITY to use NVARCHAR2
ALTER TABLE SYS_AUDIT_LOG MODIFY (SEVERITY NVARCHAR2(20) DEFAULT 'Info');

-- Modify EVENT_CATEGORY to use NVARCHAR2
ALTER TABLE SYS_AUDIT_LOG MODIFY (EVENT_CATEGORY NVARCHAR2(50) DEFAULT 'DataChange');

-- Update column comments to reflect the changes
COMMENT ON COLUMN SYS_AUDIT_LOG.CORRELATION_ID IS 'Unique identifier tracking request through system (NVARCHAR2)';
COMMENT ON COLUMN SYS_AUDIT_LOG.HTTP_METHOD IS 'HTTP method of the API request (GET, POST, PUT, DELETE) - NVARCHAR2';
COMMENT ON COLUMN SYS_AUDIT_LOG.ENDPOINT_PATH IS 'API endpoint path that was called - NVARCHAR2';
COMMENT ON COLUMN SYS_AUDIT_LOG.EXCEPTION_TYPE IS 'Type of exception if error occurred - NVARCHAR2';
COMMENT ON COLUMN SYS_AUDIT_LOG.EXCEPTION_MESSAGE IS 'Exception message if error occurred (up to 4000 chars) - NVARCHAR2';
COMMENT ON COLUMN SYS_AUDIT_LOG.SEVERITY IS 'Severity level: Critical, Error, Warning, Info - NVARCHAR2';
COMMENT ON COLUMN SYS_AUDIT_LOG.EVENT_CATEGORY IS 'Category: DataChange, Authentication, Permission, Exception, Configuration, Request - NVARCHAR2';

COMMIT;

-- Verify the changes
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, CHAR_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'SYS_AUDIT_LOG' 
AND COLUMN_NAME IN ('CORRELATION_ID', 'HTTP_METHOD', 'ENDPOINT_PATH', 'EXCEPTION_TYPE', 'EXCEPTION_MESSAGE', 'SEVERITY', 'EVENT_CATEGORY')
ORDER BY COLUMN_NAME;