-- Create SYS_AUDIT_STATUS_TRACKING table for error resolution workflow
-- Task 1.4: Create SYS_AUDIT_STATUS_TRACKING table for status workflow (Unresolved, In Progress, Resolved, Critical)
-- This table supports status tracking for exception-type audit entries only

-- Create sequence for SYS_AUDIT_STATUS_TRACKING table
CREATE SEQUENCE SEQ_SYS_AUDIT_STATUS_TRACKING
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Create SYS_AUDIT_STATUS_TRACKING table
CREATE TABLE SYS_AUDIT_STATUS_TRACKING (
    ROW_ID NUMBER(19) PRIMARY KEY,
    AUDIT_LOG_ID NUMBER(19) NOT NULL,
    STATUS NVARCHAR2(20) NOT NULL,
    ASSIGNED_TO_USER_ID NUMBER(19),
    RESOLUTION_NOTES NVARCHAR2(4000),
    STATUS_CHANGED_BY NUMBER(19) NOT NULL,
    STATUS_CHANGED_DATE DATE DEFAULT SYSDATE,
    
    -- Foreign key constraints
    CONSTRAINT FK_STATUS_AUDIT_LOG FOREIGN KEY (AUDIT_LOG_ID) REFERENCES SYS_AUDIT_LOG(ROW_ID),
    CONSTRAINT FK_STATUS_ASSIGNED_USER FOREIGN KEY (ASSIGNED_TO_USER_ID) REFERENCES SYS_USERS(ROW_ID),
    CONSTRAINT FK_STATUS_CHANGED_BY FOREIGN KEY (STATUS_CHANGED_BY) REFERENCES SYS_USERS(ROW_ID),
    
    -- Check constraint for valid status values
    CONSTRAINT CHK_STATUS_VALUES CHECK (STATUS IN ('Unresolved', 'In Progress', 'Resolved', 'Critical'))
);

-- Create indexes for performance
CREATE INDEX IDX_STATUS_TRACKING_AUDIT ON SYS_AUDIT_STATUS_TRACKING(AUDIT_LOG_ID);
CREATE INDEX IDX_STATUS_TRACKING_STATUS ON SYS_AUDIT_STATUS_TRACKING(STATUS);
CREATE INDEX IDX_STATUS_TRACKING_ASSIGNED ON SYS_AUDIT_STATUS_TRACKING(ASSIGNED_TO_USER_ID);
CREATE INDEX IDX_STATUS_TRACKING_CHANGED_BY ON SYS_AUDIT_STATUS_TRACKING(STATUS_CHANGED_BY);
CREATE INDEX IDX_STATUS_TRACKING_DATE ON SYS_AUDIT_STATUS_TRACKING(STATUS_CHANGED_DATE);

-- Composite indexes for common query patterns
CREATE INDEX IDX_STATUS_TRACKING_STATUS_DATE ON SYS_AUDIT_STATUS_TRACKING(STATUS, STATUS_CHANGED_DATE);
CREATE INDEX IDX_STATUS_TRACKING_ASSIGNED_STATUS ON SYS_AUDIT_STATUS_TRACKING(ASSIGNED_TO_USER_ID, STATUS);

-- Add table and column comments
COMMENT ON TABLE SYS_AUDIT_STATUS_TRACKING IS 'Status tracking for audit log entries - supports error resolution workflow for exception-type entries only';
COMMENT ON COLUMN SYS_AUDIT_STATUS_TRACKING.ROW_ID IS 'Primary key - unique identifier for status tracking record';
COMMENT ON COLUMN SYS_AUDIT_STATUS_TRACKING.AUDIT_LOG_ID IS 'Foreign key to SYS_AUDIT_LOG table - links to the audit entry being tracked';
COMMENT ON COLUMN SYS_AUDIT_STATUS_TRACKING.STATUS IS 'Current status of the audit entry: Unresolved, In Progress, Resolved, Critical';
COMMENT ON COLUMN SYS_AUDIT_STATUS_TRACKING.ASSIGNED_TO_USER_ID IS 'Foreign key to SYS_USERS - user assigned to resolve this issue (nullable)';
COMMENT ON COLUMN SYS_AUDIT_STATUS_TRACKING.RESOLUTION_NOTES IS 'Text field for resolution details and notes';
COMMENT ON COLUMN SYS_AUDIT_STATUS_TRACKING.STATUS_CHANGED_BY IS 'Foreign key to SYS_USERS - user who changed the status';
COMMENT ON COLUMN SYS_AUDIT_STATUS_TRACKING.STATUS_CHANGED_DATE IS 'Timestamp when the status was changed';

COMMIT;

-- Verify table creation
SELECT TABLE_NAME, TABLESPACE_NAME, STATUS
FROM USER_TABLES 
WHERE TABLE_NAME = 'SYS_AUDIT_STATUS_TRACKING';

-- Verify sequence creation
SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, LAST_NUMBER
FROM USER_SEQUENCES 
WHERE SEQUENCE_NAME = 'SEQ_SYS_AUDIT_STATUS_TRACKING';

-- Verify constraints
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, SEARCH_CONDITION
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME = 'SYS_AUDIT_STATUS_TRACKING'
ORDER BY CONSTRAINT_TYPE, CONSTRAINT_NAME;

-- Verify indexes
SELECT INDEX_NAME, INDEX_TYPE, STATUS, UNIQUENESS
FROM USER_INDEXES 
WHERE TABLE_NAME = 'SYS_AUDIT_STATUS_TRACKING'
ORDER BY INDEX_NAME;

-- Display table structure
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, CHAR_LENGTH, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'SYS_AUDIT_STATUS_TRACKING'
ORDER BY COLUMN_ID;

-- Display foreign key relationships
SELECT 
    c.CONSTRAINT_NAME,
    c.COLUMN_NAME,
    r.TABLE_NAME AS REFERENCED_TABLE,
    r.COLUMN_NAME AS REFERENCED_COLUMN
FROM USER_CONS_COLUMNS c
JOIN USER_CONSTRAINTS con ON c.CONSTRAINT_NAME = con.CONSTRAINT_NAME
JOIN USER_CONS_COLUMNS r ON con.R_CONSTRAINT_NAME = r.CONSTRAINT_NAME
WHERE c.TABLE_NAME = 'SYS_AUDIT_STATUS_TRACKING'
AND con.CONSTRAINT_TYPE = 'R'
ORDER BY c.CONSTRAINT_NAME;