-- =============================================================================
-- ThinkOn ERP - Consolidate Legacy Tenant Audit Logs into THINKON_AUDIT
-- Script 96: Merge legacy rows from THINKONERP_A17 & THINKONERP_KM and create synonyms
-- =============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;

DECLARE
    v_inserted NUMBER := 0;
BEGIN
    -- 1. Merge THINKONERP_A17
    BEGIN
        INSERT INTO THINKON_AUDIT.SYS_AUDIT_LOG (
            CORRELATION_ID, ACTOR_TYPE, ACTOR_ID, COMPANY_ID, BRANCH_ID, ACTION,
            ENTITY_TYPE, ENTITY_ID, OLD_VALUE, NEW_VALUE, IP_ADDRESS, USER_AGENT,
            HTTP_METHOD, ENDPOINT_PATH, REQUEST_PAYLOAD, RESPONSE_PAYLOAD,
            EXECUTION_TIME_MS, STATUS_CODE, EXCEPTION_TYPE, EXCEPTION_MESSAGE,
            STACK_TRACE, SEVERITY, EVENT_CATEGORY, METADATA, STATUS, CREATION_DATE,
            BUSINESS_MODULE, DEVICE_IDENTIFIER, ERROR_CODE, BUSINESS_DESCRIPTION
        )
        SELECT 
            CORRELATION_ID, ACTOR_TYPE, ACTOR_ID, COMPANY_ID, BRANCH_ID, ACTION,
            ENTITY_TYPE, ENTITY_ID, OLD_VALUE, NEW_VALUE, IP_ADDRESS, USER_AGENT,
            HTTP_METHOD, ENDPOINT_PATH, REQUEST_PAYLOAD, RESPONSE_PAYLOAD,
            EXECUTION_TIME_MS, STATUS_CODE, EXCEPTION_TYPE, EXCEPTION_MESSAGE,
            STACK_TRACE, SEVERITY, EVENT_CATEGORY, METADATA, STATUS, CREATION_DATE,
            BUSINESS_MODULE, DEVICE_IDENTIFIER, ERROR_CODE, BUSINESS_DESCRIPTION
        FROM THINKONERP_A17.SYS_AUDIT_LOG;
        
        v_inserted := SQL%ROWCOUNT;
        DBMS_OUTPUT.PUT_LINE('Migrated ' || v_inserted || ' records from THINKONERP_A17.SYS_AUDIT_LOG');
        
        EXECUTE IMMEDIATE 'DROP TABLE THINKONERP_A17.SYS_AUDIT_LOG CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE 'CREATE SYNONYM THINKONERP_A17.SYS_AUDIT_LOG FOR THINKON_AUDIT.SYS_AUDIT_LOG';
        DBMS_OUTPUT.PUT_LINE('Created synonym THINKONERP_A17.SYS_AUDIT_LOG -> THINKON_AUDIT.SYS_AUDIT_LOG');
    EXCEPTION WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error migrating THINKONERP_A17: ' || SQLERRM);
    END;

    -- 2. Merge THINKONERP_KM
    BEGIN
        INSERT INTO THINKON_AUDIT.SYS_AUDIT_LOG (
            CORRELATION_ID, ACTOR_TYPE, ACTOR_ID, COMPANY_ID, BRANCH_ID, ACTION,
            ENTITY_TYPE, ENTITY_ID, OLD_VALUE, NEW_VALUE, IP_ADDRESS, USER_AGENT,
            HTTP_METHOD, ENDPOINT_PATH, REQUEST_PAYLOAD, RESPONSE_PAYLOAD,
            EXECUTION_TIME_MS, STATUS_CODE, EXCEPTION_TYPE, EXCEPTION_MESSAGE,
            STACK_TRACE, SEVERITY, EVENT_CATEGORY, METADATA, STATUS, CREATION_DATE,
            BUSINESS_MODULE, DEVICE_IDENTIFIER, ERROR_CODE, BUSINESS_DESCRIPTION
        )
        SELECT 
            CORRELATION_ID, ACTOR_TYPE, ACTOR_ID, COMPANY_ID, BRANCH_ID, ACTION,
            ENTITY_TYPE, ENTITY_ID, OLD_VALUE, NEW_VALUE, IP_ADDRESS, USER_AGENT,
            HTTP_METHOD, ENDPOINT_PATH, REQUEST_PAYLOAD, RESPONSE_PAYLOAD,
            EXECUTION_TIME_MS, STATUS_CODE, EXCEPTION_TYPE, EXCEPTION_MESSAGE,
            STACK_TRACE, SEVERITY, EVENT_CATEGORY, METADATA, STATUS, CREATION_DATE,
            BUSINESS_MODULE, DEVICE_IDENTIFIER, ERROR_CODE, BUSINESS_DESCRIPTION
        FROM THINKONERP_KM.SYS_AUDIT_LOG;
        
        v_inserted := SQL%ROWCOUNT;
        DBMS_OUTPUT.PUT_LINE('Migrated ' || v_inserted || ' records from THINKONERP_KM.SYS_AUDIT_LOG');
        
        EXECUTE IMMEDIATE 'DROP TABLE THINKONERP_KM.SYS_AUDIT_LOG CASCADE CONSTRAINTS';
        EXECUTE IMMEDIATE 'CREATE SYNONYM THINKONERP_KM.SYS_AUDIT_LOG FOR THINKON_AUDIT.SYS_AUDIT_LOG';
        DBMS_OUTPUT.PUT_LINE('Created synonym THINKONERP_KM.SYS_AUDIT_LOG -> THINKON_AUDIT.SYS_AUDIT_LOG');
    EXCEPTION WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error migrating THINKONERP_KM: ' || SQLERRM);
    END;

    COMMIT;
END;
/
EXIT;
