using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ThinkOnErp.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class SeedDataSql : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_COMPANY_SYSTEMS"" (""Id"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""IS_ALLOWED"", ""NOTES"", ""REVOKED_DATE"", ""SYSTEM_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'),1, NULL, NULL, 1, NULL, NULL);
INSERT INTO ""SYS_COMPANY_SYSTEMS"" (""Id"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""IS_ALLOWED"", ""NOTES"", ""REVOKED_DATE"", ""SYSTEM_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'),1, NULL, NULL, 2, NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_CURRENCY"" (""Id"", ""SUM_DESC"", ""SUM_DESC_E"", ""CREATION_DATE"", ""CREATION_USER"", ""CURR_RATE"", ""CURR_RATE_DATE"", ""NAME_AR"", ""NAME_EN"", ""DUAL_DESC"", ""DUAL_DESC_E"", ""FRAC_DESC"", ""FRAC_DESC_E"", ""SHORT_DESC"", ""SHORT_DESC_E"", ""SINGULER_DESC"", ""SINGULER_DESC_E"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, N'??????', N'Riyals', TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1.0, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'???? ?????', N'Saudi Riyal', N'??????', N'Two Riyals', N'????', N'Halala', N'?.?', N'SAR', N'????', N'Riyal', NULL, NULL);
INSERT INTO ""SYS_CURRENCY"" (""Id"", ""SUM_DESC"", ""SUM_DESC_E"", ""CREATION_DATE"", ""CREATION_USER"", ""CURR_RATE"", ""CURR_RATE_DATE"", ""NAME_AR"", ""NAME_EN"", ""DUAL_DESC"", ""DUAL_DESC_E"", ""FRAC_DESC"", ""FRAC_DESC_E"", ""SHORT_DESC"", ""SHORT_DESC_E"", ""SINGULER_DESC"", ""SINGULER_DESC_E"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2, N'???????', N'Dollars', TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 3.75, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'????? ??????', N'US Dollar', N'???????', N'Two Dollars', N'???', N'Cent', N'?????', N'USD', N'?????', N'Dollar', NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_REPORT_SCHEDULE"" (""Id"", ""CREATED_AT"", ""CREATED_BY_USER_ID"", ""DAY_OF_MONTH"", ""DAY_OF_WEEK"", ""EXPORT_FORMAT"", ""FREQUENCY"", ""IS_ACTIVE"", ""LAST_ERROR_MESSAGE"", ""LAST_GENERATED_AT"", ""LAST_GENERATION_STATUS"", ""PARAMETERS"", ""RECIPIENTS"", ""REPORT_TYPE"", ""TIME_OF_DAY"")
VALUES (1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), 1, NULL, NULL, N'PDF', N'Daily', 1, NULL, NULL, NULL, NULL, N'managers@techcompany.com', N'TicketSummary', N'08:00');
INSERT INTO ""SYS_REPORT_SCHEDULE"" (""Id"", ""CREATED_AT"", ""CREATED_BY_USER_ID"", ""DAY_OF_MONTH"", ""DAY_OF_WEEK"", ""EXPORT_FORMAT"", ""FREQUENCY"", ""IS_ACTIVE"", ""LAST_ERROR_MESSAGE"", ""LAST_GENERATED_AT"", ""LAST_GENERATION_STATUS"", ""PARAMETERS"", ""RECIPIENTS"", ""REPORT_TYPE"", ""TIME_OF_DAY"")
VALUES (2, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), 1, NULL, 1, N'Excel', N'Weekly', 1, NULL, NULL, NULL, NULL, N'support-team@techcompany.com', N'SlaCompliance', N'09:00');
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_RETENTION_POLICIES"" (""Id"", ""ARCHIVE_ENABLED"", ""DESCRIPTION"", ""EVENT_CATEGORY"", ""LAST_MODIFIED_BY"", ""LAST_MODIFIED_DATE"", ""RETENTION_DAYS"")
VALUES (1, 1, N'Keep authentication logs for 1 year, then archive', N'Authentication', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), 365);
INSERT INTO ""SYS_RETENTION_POLICIES"" (""Id"", ""ARCHIVE_ENABLED"", ""DESCRIPTION"", ""EVENT_CATEGORY"", ""LAST_MODIFIED_BY"", ""LAST_MODIFIED_DATE"", ""RETENTION_DAYS"")
VALUES (2, 1, N'Keep data change audit logs for 2 years, then archive', N'DataChange', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), 730);
INSERT INTO ""SYS_RETENTION_POLICIES"" (""Id"", ""ARCHIVE_ENABLED"", ""DESCRIPTION"", ""EVENT_CATEGORY"", ""LAST_MODIFIED_BY"", ""LAST_MODIFIED_DATE"", ""RETENTION_DAYS"")
VALUES (3, 1, N'Keep security events for 5 years', N'Security', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), 1825);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_ROLE"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""IS_ACTIVE"", ""NOTE"", ""NAME_AR"", ""NAME_EN"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed',1, N'Full system access', N'????', N'Administrator', NULL, NULL);
INSERT INTO ""SYS_ROLE"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""IS_ACTIVE"", ""NOTE"", ""NAME_AR"", ""NAME_EN"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed',1, N'Support ticket management', N'??? ???', N'Support Technician', NULL, NULL);
INSERT INTO ""SYS_ROLE"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""IS_ACTIVE"", ""NOTE"", ""NAME_AR"", ""NAME_EN"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (3, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed',1, N'Read-only access', N'?????', N'Viewer', NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_SUPER_ADMIN"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""EMAIL"", ""IS_ACTIVE"", ""LAST_LOGIN_DATE"", ""NAME_AR"", ""NAME_EN"", ""PASSWORD"", ""PHONE"", ""TWO_FA_ENABLED"", ""TWO_FA_SECRET"", ""UPDATE_DATE"", ""UPDATE_USER"", ""USER_NAME"")
VALUES (1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', N'admin@thinkonerp.com',1, NULL, N'???? ??????', N'System Administrator', N'p5LZHbA7E+eKQDaCsTCd2Z7Yj6pSAHSmLoV/+DsSXW/WK1+tJChWAtXG8VKQm4fS', N'+966500000001', 0, NULL, NULL, NULL, N'admin');
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_SYSTEM"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION"", ""DESCRIPTION_E"", ""DISPLAY_ORDER"", ""ICON"", ""IS_ACTIVE"", ""SYSTEM_CODE"", ""SYSTEM_NAME"", ""SYSTEM_NAME_E"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', N'???? ????? ????? ?????', N'Technical support ticketing system', 1, N'headset',1, N'support', N'???? ???????', N'Customer Support', NULL, NULL);
INSERT INTO ""SYS_SYSTEM"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION"", ""DESCRIPTION_E"", ""DISPLAY_ORDER"", ""ICON"", ""IS_ACTIVE"", ""SYSTEM_CODE"", ""SYSTEM_NAME"", ""SYSTEM_NAME_E"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', N'???? ????? ??????? ???????', N'HR management system', 2, N'people',1, N'hr', N'??????? ???????', N'Human Resources', NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_TICKET_CATEGORY"" (""Id"", ""CATEGORY_NAME_AR"", ""CATEGORY_NAME_EN"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION_AR"", ""DESCRIPTION_EN"", ""DISPLAY_ORDER"", ""IS_ACTIVE"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, N'?????', N'Network', TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, NULL, 1,1, NULL, NULL);
INSERT INTO ""SYS_TICKET_CATEGORY"" (""Id"", ""CATEGORY_NAME_AR"", ""CATEGORY_NAME_EN"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION_AR"", ""DESCRIPTION_EN"", ""DISPLAY_ORDER"", ""IS_ACTIVE"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2, N'???????', N'Software', TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, NULL, 2,1, NULL, NULL);
INSERT INTO ""SYS_TICKET_CATEGORY"" (""Id"", ""CATEGORY_NAME_AR"", ""CATEGORY_NAME_EN"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION_AR"", ""DESCRIPTION_EN"", ""DISPLAY_ORDER"", ""IS_ACTIVE"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (3, N'?????', N'Hardware', TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, NULL, 3,1, NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_TICKET_CONFIG"" (""Id"", ""CONFIG_KEY"", ""CONFIG_TYPE"", ""CONFIG_VALUE"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION_AR"", ""DESCRIPTION_EN"", ""IS_ACTIVE"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, N'SLA.Priority.Critical.Hours', N'SLA', N'1', TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, NULL,1, NULL, NULL);
INSERT INTO ""SYS_TICKET_CONFIG"" (""Id"", ""CONFIG_KEY"", ""CONFIG_TYPE"", ""CONFIG_VALUE"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION_AR"", ""DESCRIPTION_EN"", ""IS_ACTIVE"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2, N'SLA.Priority.High.Hours', N'SLA', N'4', TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, NULL,1, NULL, NULL);
INSERT INTO ""SYS_TICKET_CONFIG"" (""Id"", ""CONFIG_KEY"", ""CONFIG_TYPE"", ""CONFIG_VALUE"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION_AR"", ""DESCRIPTION_EN"", ""IS_ACTIVE"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (3, N'Attachment.MaxFileSize', N'FileAttachment', N'10485760', TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, NULL,1, NULL, NULL);
INSERT INTO ""SYS_TICKET_CONFIG"" (""Id"", ""CONFIG_KEY"", ""CONFIG_TYPE"", ""CONFIG_VALUE"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION_AR"", ""DESCRIPTION_EN"", ""IS_ACTIVE"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (4, N'Attachment.AllowedExtensions', N'FileAttachment', N'.pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png,.txt', TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, NULL,1, NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_TICKET_PRIORITY"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""ESCALATION_THRESHOLD_HOURS"", ""IS_ACTIVE"", ""PRIORITY_LEVEL"", ""PRIORITY_NAME_AR"", ""PRIORITY_NAME_EN"", ""SLA_TARGET_HOURS"")
VALUES (1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 0.5,1, 1, N'???', N'Critical', 1.0);
INSERT INTO ""SYS_TICKET_PRIORITY"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""ESCALATION_THRESHOLD_HOURS"", ""IS_ACTIVE"", ""PRIORITY_LEVEL"", ""PRIORITY_NAME_AR"", ""PRIORITY_NAME_EN"", ""SLA_TARGET_HOURS"")
VALUES (2, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 2.0,1, 2, N'?????', N'High', 4.0);
INSERT INTO ""SYS_TICKET_PRIORITY"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""ESCALATION_THRESHOLD_HOURS"", ""IS_ACTIVE"", ""PRIORITY_LEVEL"", ""PRIORITY_NAME_AR"", ""PRIORITY_NAME_EN"", ""SLA_TARGET_HOURS"")
VALUES (3, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 4.0,1, 3, N'??????', N'Medium', 8.0);
INSERT INTO ""SYS_TICKET_PRIORITY"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""ESCALATION_THRESHOLD_HOURS"", ""IS_ACTIVE"", ""PRIORITY_LEVEL"", ""PRIORITY_NAME_AR"", ""PRIORITY_NAME_EN"", ""SLA_TARGET_HOURS"")
VALUES (4, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 12.0,1, 4, N'??????', N'Low', 24.0);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_TICKET_STATUS"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DISPLAY_ORDER"", ""IS_ACTIVE"", ""IS_FINAL_STATUS"", ""STATUS_CODE"", ""STATUS_NAME_AR"", ""STATUS_NAME_EN"")
VALUES (1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1,1, 0, N'OPEN', N'??????', N'Open');
INSERT INTO ""SYS_TICKET_STATUS"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DISPLAY_ORDER"", ""IS_ACTIVE"", ""IS_FINAL_STATUS"", ""STATUS_CODE"", ""STATUS_NAME_AR"", ""STATUS_NAME_EN"")
VALUES (2, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 2,1, 0, N'IN_PROGRESS', N'??? ????????', N'In Progress');
INSERT INTO ""SYS_TICKET_STATUS"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DISPLAY_ORDER"", ""IS_ACTIVE"", ""IS_FINAL_STATUS"", ""STATUS_CODE"", ""STATUS_NAME_AR"", ""STATUS_NAME_EN"")
VALUES (3, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 3,1, 0, N'RESOLVED', N'?? ????', N'Resolved');
INSERT INTO ""SYS_TICKET_STATUS"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DISPLAY_ORDER"", ""IS_ACTIVE"", ""IS_FINAL_STATUS"", ""STATUS_CODE"", ""STATUS_NAME_AR"", ""STATUS_NAME_EN"")
VALUES (4, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 4,1,1, N'CLOSED', N'?????', N'Closed');
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_USERS"" (""Id"", ""BRANCH_ID"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""EMAIL"", ""FORCE_LOGOUT_DATE"", ""NAME_AR"", ""NAME_EN"", ""IS_ACTIVE"", ""IS_ADMIN"", ""LAST_LOGIN_DATE"", ""PASSWORD"", ""PHONE"", ""PHONE2"", ""REFRESH_TOKEN"", ""REFRESH_TOKEN_EXPIRY"", ""ROLE"", ""UPDATE_DATE"", ""UPDATE_USER"", ""USER_NAME"")
VALUES (1, 1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', N'ahmed@techcompany.com', NULL, N'???? ????', N'Ahmed Mohammed',1,1, NULL, N'57O450lBBpooooMgzpwo5RVeuRO6i2um9jn/Bh+qyf+jxw6M6PZ6pyhk3lujV22r', N'+966500000002', NULL, NULL, NULL, 1, NULL, NULL, N'ahmed');
INSERT INTO ""SYS_USERS"" (""Id"", ""BRANCH_ID"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""EMAIL"", ""FORCE_LOGOUT_DATE"", ""NAME_AR"", ""NAME_EN"", ""IS_ACTIVE"", ""IS_ADMIN"", ""LAST_LOGIN_DATE"", ""PASSWORD"", ""PHONE"", ""PHONE2"", ""REFRESH_TOKEN"", ""REFRESH_TOKEN_EXPIRY"", ""ROLE"", ""UPDATE_DATE"", ""UPDATE_USER"", ""USER_NAME"")
VALUES (2, 1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', N'sara@techcompany.com', NULL, N'???? ????', N'Sara Khaled',1, 0, NULL, N'57O450lBBpooooMgzpwo5RVeuRO6i2um9jn/Bh+qyf+jxw6M6PZ6pyhk3lujV22r', N'+966500000003', NULL, NULL, NULL, 2, NULL, NULL, N'sara');
INSERT INTO ""SYS_USERS"" (""Id"", ""BRANCH_ID"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""EMAIL"", ""FORCE_LOGOUT_DATE"", ""NAME_AR"", ""NAME_EN"", ""IS_ACTIVE"", ""IS_ADMIN"", ""LAST_LOGIN_DATE"", ""PASSWORD"", ""PHONE"", ""PHONE2"", ""REFRESH_TOKEN"", ""REFRESH_TOKEN_EXPIRY"", ""ROLE"", ""UPDATE_DATE"", ""UPDATE_USER"", ""USER_NAME"")
VALUES (3, 2, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', N'khaled@techcompany.com', NULL, N'???? ???', N'Khaled Omar',1, 0, NULL, N'57O450lBBpooooMgzpwo5RVeuRO6i2um9jn/Bh+qyf+jxw6M6PZ6pyhk3lujV22r', N'+966500000004', NULL, NULL, NULL, 3, NULL, NULL, N'khaled');
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_COMPANY"" (""Id"", ""COMPANY_CODE"", ""COMPANY_LOGO"", ""NAME_AR"", ""NAME_EN"", ""COUNTRY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""CURR_ID"", ""DEFAULT_BRANCH_ID"", ""IS_ACTIVE"", ""LEGAL_NAME"", ""LEGAL_NAME_E"", ""TAX_NUMBER"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, N'TECH01', NULL, N'???? ?????', N'Tech Company', NULL, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, NULL,1, N'Tech Company For Information Technology', N'Tech Company For Information Technology', N'300123456700003', NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_SAVED_SEARCH"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""IS_ACTIVE"", ""IS_DEFAULT"", ""IS_PUBLIC"", ""LAST_USED_DATE"", ""SEARCH_CRITERIA"", ""SEARCH_DESCRIPTION"", ""SEARCH_NAME"", ""UPDATE_DATE"", ""UPDATE_USER"", ""USAGE_COUNT"", ""USER_ID"")
VALUES (1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'ahmed',1,1, 0, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_CLOB('{""status"":""OPEN"",""assigneeId"":""current""}'), N'All open tickets assigned to me', N'My Open Tickets', NULL, NULL, 5, 1);
INSERT INTO ""SYS_SAVED_SEARCH"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""IS_ACTIVE"", ""IS_DEFAULT"", ""IS_PUBLIC"", ""LAST_USED_DATE"", ""SEARCH_CRITERIA"", ""SEARCH_DESCRIPTION"", ""SEARCH_NAME"", ""UPDATE_DATE"", ""UPDATE_USER"", ""USAGE_COUNT"", ""USER_ID"")
VALUES (2, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'sara',1, 0,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_CLOB('{""priority"":""CRITICAL"",""assigneeId"":null}'), N'All unassigned critical tickets', N'Critical Tickets', NULL, NULL, 12, 2);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_SCREEN"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION"", ""DESCRIPTION_E"", ""DISPLAY_ORDER"", ""ICON"", ""IS_ACTIVE"", ""PARENT_SCREEN_ID"", ""ROUTE"", ""SCREEN_CODE"", ""SCREEN_NAME"", ""SCREEN_NAME_E"", ""SYSTEM_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, NULL, 1, N'grid',1, NULL, N'/support/dashboard', N'support-dashboard', N'???? ??????', N'Dashboard', 1, NULL, NULL);
INSERT INTO ""SYS_SCREEN"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION"", ""DESCRIPTION_E"", ""DISPLAY_ORDER"", ""ICON"", ""IS_ACTIVE"", ""PARENT_SCREEN_ID"", ""ROUTE"", ""SCREEN_CODE"", ""SCREEN_NAME"", ""SCREEN_NAME_E"", ""SYSTEM_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, NULL, 2, N'ticket',1, NULL, N'/support/tickets', N'support-tickets', N'???????', N'Tickets', 1, NULL, NULL);
INSERT INTO ""SYS_SCREEN"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION"", ""DESCRIPTION_E"", ""DISPLAY_ORDER"", ""ICON"", ""IS_ACTIVE"", ""PARENT_SCREEN_ID"", ""ROUTE"", ""SCREEN_CODE"", ""SCREEN_NAME"", ""SCREEN_NAME_E"", ""SYSTEM_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (3, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, NULL, 3, N'chart',1, NULL, N'/support/reports', N'support-reports', N'????????', N'Reports', 1, NULL, NULL);
INSERT INTO ""SYS_SCREEN"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION"", ""DESCRIPTION_E"", ""DISPLAY_ORDER"", ""ICON"", ""IS_ACTIVE"", ""PARENT_SCREEN_ID"", ""ROUTE"", ""SCREEN_CODE"", ""SCREEN_NAME"", ""SCREEN_NAME_E"", ""SYSTEM_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (4, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, NULL, 1, N'person',1, NULL, N'/hr/employees', N'hr-employees', N'????????', N'Employees', 2, NULL, NULL);
INSERT INTO ""SYS_SCREEN"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION"", ""DESCRIPTION_E"", ""DISPLAY_ORDER"", ""ICON"", ""IS_ACTIVE"", ""PARENT_SCREEN_ID"", ""ROUTE"", ""SCREEN_CODE"", ""SCREEN_NAME"", ""SCREEN_NAME_E"", ""SYSTEM_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (5, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, NULL, 2, N'clock',1, NULL, N'/hr/attendance', N'hr-attendance', N'?????? ?????????', N'Attendance', 2, NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_TICKET_TYPE"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DEFAULT_PRIORITY_ID"", ""DESCRIPTION_AR"", ""DESCRIPTION_EN"", ""IS_ACTIVE"", ""SLA_TARGET_HOURS"", ""TYPE_NAME_AR"", ""TYPE_NAME_EN"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 2, NULL, NULL,1, 4.0, N'??? ?????', N'Bug Report', NULL, NULL);
INSERT INTO ""SYS_TICKET_TYPE"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DEFAULT_PRIORITY_ID"", ""DESCRIPTION_AR"", ""DESCRIPTION_EN"", ""IS_ACTIVE"", ""SLA_TARGET_HOURS"", ""TYPE_NAME_AR"", ""TYPE_NAME_EN"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 3, NULL, NULL,1, 24.0, N'??? ?????', N'Feature Request', NULL, NULL);
INSERT INTO ""SYS_TICKET_TYPE"" (""Id"", ""CREATION_DATE"", ""CREATION_USER"", ""DEFAULT_PRIORITY_ID"", ""DESCRIPTION_AR"", ""DESCRIPTION_EN"", ""IS_ACTIVE"", ""SLA_TARGET_HOURS"", ""TYPE_NAME_AR"", ""TYPE_NAME_EN"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (3, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 4, NULL, NULL,1, 48.0, N'???????', N'Inquiry', NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_USERS_ROLES"" (""Id"", ""ASSIGNED_BY"", ""ASSIGNED_DATE"", ""CREATION_DATE"", ""CREATION_USER"", ""ROLE_ID"", ""USER_ID"")
VALUES (1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, 1);
INSERT INTO ""SYS_USERS_ROLES"" (""Id"", ""ASSIGNED_BY"", ""ASSIGNED_DATE"", ""CREATION_DATE"", ""CREATION_USER"", ""ROLE_ID"", ""USER_ID"")
VALUES (2, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 2, 2);
INSERT INTO ""SYS_USERS_ROLES"" (""Id"", ""ASSIGNED_BY"", ""ASSIGNED_DATE"", ""CREATION_DATE"", ""CREATION_USER"", ""ROLE_ID"", ""USER_ID"")
VALUES (3, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 3, 3);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_BRANCH"" (""Id"", ""BASE_CURRENCY_ID"", ""BRANCH_LOGO"", ""NAME_AR"", ""NAME_EN"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""DEFAULT_LANG"", ""EMAIL"", ""FAX"", ""IS_ACTIVE"", ""IS_HEAD_BRANCH"", ""MOBILE"", ""PHONE"", ""ROUNDING_RULES"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, 1, NULL, N'?????? ???????', N'Headquarters', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, N'hq@techcompany.com', NULL,1,1, N'+966501234567', N'+966112345678', NULL, NULL, NULL);
INSERT INTO ""SYS_BRANCH"" (""Id"", ""BASE_CURRENCY_ID"", ""BRANCH_LOGO"", ""NAME_AR"", ""NAME_EN"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""DEFAULT_LANG"", ""EMAIL"", ""FAX"", ""IS_ACTIVE"", ""IS_HEAD_BRANCH"", ""MOBILE"", ""PHONE"", ""ROUNDING_RULES"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2, 1, NULL, N'??? ??????', N'Riyadh Branch', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, N'riyadh@techcompany.com', NULL,1, 0, N'+966501234568', N'+966112345679', NULL, NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_COMPANY_SCREEN_PERMISSIONS"" (""Id"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""NOTES"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1,1,1,1,1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, 1, NULL, NULL);
INSERT INTO ""SYS_COMPANY_SCREEN_PERMISSIONS"" (""Id"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""NOTES"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2,1,1,1,1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, 2, NULL, NULL);
INSERT INTO ""SYS_COMPANY_SCREEN_PERMISSIONS"" (""Id"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""NOTES"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (3,1,1,1,1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, 3, NULL, NULL);
INSERT INTO ""SYS_COMPANY_SCREEN_PERMISSIONS"" (""Id"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""NOTES"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (4,1,1,1,1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, 4, NULL, NULL);
INSERT INTO ""SYS_COMPANY_SCREEN_PERMISSIONS"" (""Id"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""NOTES"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (5,1,1,1,1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, 5, NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_ROLE_SCREEN_PERMISSIONS"" (""Id"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""ROLE_ID"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1,1,1,1,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, 1, NULL, NULL);
INSERT INTO ""SYS_ROLE_SCREEN_PERMISSIONS"" (""Id"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""ROLE_ID"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2,1,1,1,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, 2, NULL, NULL);
INSERT INTO ""SYS_ROLE_SCREEN_PERMISSIONS"" (""Id"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""ROLE_ID"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (3,1,1,1,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, 3, NULL, NULL);
INSERT INTO ""SYS_ROLE_SCREEN_PERMISSIONS"" (""Id"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""ROLE_ID"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (4,1,1,1,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, 4, NULL, NULL);
INSERT INTO ""SYS_ROLE_SCREEN_PERMISSIONS"" (""Id"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""ROLE_ID"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (5,1,1,1,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, 5, NULL, NULL);
INSERT INTO ""SYS_ROLE_SCREEN_PERMISSIONS"" (""Id"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""ROLE_ID"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (6, 0,1,1,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 2, 1, NULL, NULL);
INSERT INTO ""SYS_ROLE_SCREEN_PERMISSIONS"" (""Id"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""ROLE_ID"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (7, 0,1,1,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 2, 2, NULL, NULL);
INSERT INTO ""SYS_ROLE_SCREEN_PERMISSIONS"" (""Id"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""ROLE_ID"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (8, 0, 0, 0,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 3, 1, NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_USER_SCREEN_PERMISSIONS"" (""Id"", ""ASSIGNED_BY"", ""AssignedDate"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""NOTES"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"", ""USER_ID"")
VALUES (1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), 0, 0, 0,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', NULL, 3, NULL, NULL, 2);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_BRANCH_SCREEN_PERMISSIONS"" (""Id"", ""BRANCH_ID"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""NOTES"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, 1,1,1,1,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, 1, NULL, NULL);
INSERT INTO ""SYS_BRANCH_SCREEN_PERMISSIONS"" (""Id"", ""BRANCH_ID"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""NOTES"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2, 1,1,1,1,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, 2, NULL, NULL);
INSERT INTO ""SYS_BRANCH_SCREEN_PERMISSIONS"" (""Id"", ""BRANCH_ID"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""NOTES"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (3, 1,1,1,1,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, 3, NULL, NULL);
INSERT INTO ""SYS_BRANCH_SCREEN_PERMISSIONS"" (""Id"", ""BRANCH_ID"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""NOTES"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (4, 1,1,1,1,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, 4, NULL, NULL);
INSERT INTO ""SYS_BRANCH_SCREEN_PERMISSIONS"" (""Id"", ""BRANCH_ID"", ""CAN_DELETE"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_VIEW"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""NOTES"", ""SCREEN_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (5, 1,1,1,1,1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, 5, NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_BRANCH_SYSTEMS"" (""Id"", ""BRANCH_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""IS_ALLOWED"", ""NOTES"", ""REVOKED_DATE"", ""SYSTEM_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'),1, NULL, NULL, 1, NULL, NULL);
INSERT INTO ""SYS_BRANCH_SYSTEMS"" (""Id"", ""BRANCH_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""IS_ALLOWED"", ""NOTES"", ""REVOKED_DATE"", ""SYSTEM_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'),1, NULL, NULL, 2, NULL, NULL);
INSERT INTO ""SYS_BRANCH_SYSTEMS"" (""Id"", ""BRANCH_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""IS_ALLOWED"", ""NOTES"", ""REVOKED_DATE"", ""SYSTEM_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (3, 2, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'),1, NULL, NULL, 1, NULL, NULL);
INSERT INTO ""SYS_BRANCH_SYSTEMS"" (""Id"", ""BRANCH_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""GRANTED_BY"", ""GRANTED_DATE"", ""IS_ALLOWED"", ""NOTES"", ""REVOKED_DATE"", ""SYSTEM_ID"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (4, 2, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'),1, NULL, NULL, 2, NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_FISCAL_YEAR"" (""Id"", ""BRANCH_ID"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""END_DATE"", ""FISCAL_YEAR_CODE"", ""NAME_AR"", ""NAME_EN"", ""IS_ACTIVE"", ""IS_CLOSED"", ""START_DATE"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, 1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', TO_TIMESTAMP('2025-12-31 23:59:59.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'FY2025', N'????? ??????? 2025', N'Fiscal Year 2025',1, 0, TO_TIMESTAMP('2025-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL);
INSERT INTO ""SYS_FISCAL_YEAR"" (""Id"", ""BRANCH_ID"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""END_DATE"", ""FISCAL_YEAR_CODE"", ""NAME_AR"", ""NAME_EN"", ""IS_ACTIVE"", ""IS_CLOSED"", ""START_DATE"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2, 1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'seed', TO_TIMESTAMP('2026-12-31 23:59:59.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'FY2026', N'????? ??????? 2026', N'Fiscal Year 2026',1, 0, TO_TIMESTAMP('2026-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_REQUEST_TICKET"" (""Id"", ""ACTUAL_RESOLUTION_DATE"", ""ASSIGNEE_ID"", ""BRANCH_ID"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION"", ""EXPECTED_RESOLUTION_DATE"", ""IS_ACTIVE"", ""REQUESTER_ID"", ""TICKET_CATEGORY_ID"", ""TICKET_PRIORITY_ID"", ""TICKET_STATUS_ID"", ""TICKET_TYPE_ID"", ""TITLE_AR"", ""TITLE_EN"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (1, NULL, 2, 1, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'ahmed', TO_NCLOB(N'All network services are down at HQ since 9:00 AM.'), NULL,1, 1, 1, 1, 2, 1, N'???? ?????? ?? ????? ???????', N'Network outage at headquarters', NULL, NULL);
INSERT INTO ""SYS_REQUEST_TICKET"" (""Id"", ""ACTUAL_RESOLUTION_DATE"", ""ASSIGNEE_ID"", ""BRANCH_ID"", ""COMPANY_ID"", ""CREATION_DATE"", ""CREATION_USER"", ""DESCRIPTION"", ""EXPECTED_RESOLUTION_DATE"", ""IS_ACTIVE"", ""REQUESTER_ID"", ""TICKET_CATEGORY_ID"", ""TICKET_PRIORITY_ID"", ""TICKET_STATUS_ID"", ""TICKET_TYPE_ID"", ""TITLE_AR"", ""TITLE_EN"", ""UPDATE_DATE"", ""UPDATE_USER"")
VALUES (2, NULL, 2, 2, 1, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'khaled', TO_NCLOB(N'Need to install accounting software on 5 new machines.'), NULL,1, 3, 2, 3, 1, 2, N'??? ????? ?????? ??????', N'Request to install accounting software', NULL, NULL);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_SEARCH_ANALYTICS"" (""Id"", ""BRANCH_ID"", ""COMPANY_ID"", ""EXECUTION_TIME_MS"", ""FILTER_LOGIC"", ""RESULT_COUNT"", ""SEARCH_CRITERIA"", ""SEARCH_DATE"", ""SEARCH_TERM"", ""USER_ID"")
VALUES (1, 1, 1, 45, N'OR', 3, NULL, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'network', 1);
INSERT INTO ""SYS_SEARCH_ANALYTICS"" (""Id"", ""BRANCH_ID"", ""COMPANY_ID"", ""EXECUTION_TIME_MS"", ""FILTER_LOGIC"", ""RESULT_COUNT"", ""SEARCH_CRITERIA"", ""SEARCH_DATE"", ""SEARCH_TERM"", ""USER_ID"")
VALUES (2, 1, 1, 120, NULL, 15, NULL, TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'open tickets', 2);
END;");

            migrationBuilder.Sql(@"BEGIN
INSERT INTO ""SYS_TICKET_COMMENT"" (""Id"", ""COMMENT_TEXT"", ""CREATION_DATE"", ""CREATION_USER"", ""IS_INTERNAL"", ""TICKET_ID"")
VALUES (1, N'We are investigating the issue. Will provide update in 30 minutes.', TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'sara', 0, 1);
INSERT INTO ""SYS_TICKET_COMMENT"" (""Id"", ""COMMENT_TEXT"", ""CREATION_DATE"", ""CREATION_USER"", ""IS_INTERNAL"", ""TICKET_ID"")
VALUES (2, N'Internal note: Check the main switch in server room.', TO_TIMESTAMP('2026-05-17 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF'), N'sara',1, 1);
END;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"BEGIN
DELETE FROM ""SYS_TICKET_COMMENT"" WHERE ""Id"" IN (1, 2);
DELETE FROM ""SYS_SEARCH_ANALYTICS"" WHERE ""Id"" IN (1, 2);
DELETE FROM ""SYS_REQUEST_TICKET"" WHERE ""Id"" IN (1, 2);
DELETE FROM ""SYS_FISCAL_YEAR"" WHERE ""Id"" IN (1, 2);
DELETE FROM ""SYS_BRANCH_SYSTEMS"" WHERE ""Id"" IN (1, 2, 3, 4);
DELETE FROM ""SYS_BRANCH_SCREEN_PERMISSIONS"" WHERE ""Id"" IN (1, 2, 3, 4, 5);
DELETE FROM ""SYS_USER_SCREEN_PERMISSIONS"" WHERE ""Id"" = 1;
DELETE FROM ""SYS_ROLE_SCREEN_PERMISSIONS"" WHERE ""Id"" IN (1, 2, 3, 4, 5, 6, 7, 8);
DELETE FROM ""SYS_COMPANY_SCREEN_PERMISSIONS"" WHERE ""Id"" IN (1, 2, 3, 4, 5);
DELETE FROM ""SYS_BRANCH"" WHERE ""Id"" IN (1, 2);
DELETE FROM ""SYS_USERS_ROLES"" WHERE ""Id"" IN (1, 2, 3);
DELETE FROM ""SYS_TICKET_TYPE"" WHERE ""Id"" IN (1, 2, 3);
DELETE FROM ""SYS_SCREEN"" WHERE ""Id"" IN (1, 2, 3, 4, 5);
DELETE FROM ""SYS_SAVED_SEARCH"" WHERE ""Id"" IN (1, 2);
DELETE FROM ""SYS_COMPANY"" WHERE ""Id"" = 1;
DELETE FROM ""SYS_USERS"" WHERE ""Id"" IN (1, 2, 3);
DELETE FROM ""SYS_TICKET_STATUS"" WHERE ""Id"" IN (1, 2, 3, 4);
DELETE FROM ""SYS_TICKET_PRIORITY"" WHERE ""Id"" IN (1, 2, 3, 4);
DELETE FROM ""SYS_TICKET_CONFIG"" WHERE ""Id"" IN (1, 2, 3, 4);
DELETE FROM ""SYS_TICKET_CATEGORY"" WHERE ""Id"" IN (1, 2, 3);
DELETE FROM ""SYS_SYSTEM"" WHERE ""Id"" IN (1, 2);
DELETE FROM ""SYS_SUPER_ADMIN"" WHERE ""Id"" = 1;
DELETE FROM ""SYS_ROLE"" WHERE ""Id"" IN (1, 2, 3);
DELETE FROM ""SYS_RETENTION_POLICIES"" WHERE ""Id"" IN (1, 2, 3);
DELETE FROM ""SYS_REPORT_SCHEDULE"" WHERE ""Id"" IN (1, 2);
DELETE FROM ""SYS_CURRENCY"" WHERE ""Id"" IN (1, 2);
DELETE FROM ""SYS_COMPANY_SYSTEMS"" WHERE ""Id"" IN (1, 2);
END;");
        }
    }
}

