using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ThinkOnErp.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class RecreateDroppedTablesWithSeedData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Drop existing tables gracefully (ignore if not found)
            foreach (var tbl in new[] { "SYS_USER_SCREEN_PERMISSIONS", "SYS_ROLE_SCREEN_PERMISSIONS", "SYS_USERS_ROLES", "SYS_SETTINGS", "SYS_USERS", "SYS_ROLE" })
            {
                migrationBuilder.Sql($@"
                    BEGIN
                        EXECUTE IMMEDIATE 'DROP TABLE ""{tbl}"" CASCADE CONSTRAINTS PURGE';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -942 THEN RAISE; END IF;
                    END;
                ");
            }

            // 1. SYS_ROLE
            migrationBuilder.Sql(@"
                CREATE TABLE ""SYS_ROLE"" (
                    ""Id"" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
                    ""NAME_LOCAL"" NVARCHAR2(200) NOT NULL,
                    ""NAME_EN"" NVARCHAR2(200) NOT NULL,
                    ""NOTE"" NVARCHAR2(500) NULL,
                    ""IS_ACTIVE"" NUMBER(1) NOT NULL,
                    ""CREATION_USER"" NVARCHAR2(100) NOT NULL,
                    ""CREATION_DATE"" TIMESTAMP(7) NULL,
                    ""UPDATE_USER"" NVARCHAR2(100) NULL,
                    ""UPDATE_DATE"" TIMESTAMP(7) NULL,
                    CONSTRAINT ""PK_SYS_ROLE"" PRIMARY KEY (""Id"")
                )
            ");

            // 2. SYS_USERS (unique index on USER_NAME added after table creation)
            migrationBuilder.Sql(@"
                CREATE TABLE ""SYS_USERS"" (
                    ""Id"" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
                    ""NAME_LOCAL"" NVARCHAR2(200) NOT NULL,
                    ""NAME_EN"" NVARCHAR2(200) NOT NULL,
                    ""USER_NAME"" NVARCHAR2(100) NOT NULL,
                    ""PASSWORD"" NVARCHAR2(500) NOT NULL,
                    ""PHONE"" NVARCHAR2(50) NULL,
                    ""PHONE2"" NVARCHAR2(50) NULL,
                    ""ROLE"" NUMBER(19) NULL,
                    ""BRANCH_ID"" NUMBER(19) NULL,
                    ""COMPANY_ID"" NUMBER(19) NULL,
                    ""EMAIL"" NVARCHAR2(200) NULL,
                    ""LAST_LOGIN_DATE"" TIMESTAMP(7) NULL,
                    ""IS_ACTIVE"" NUMBER(1) NOT NULL,
                    ""IS_ADMIN"" NUMBER(1) NOT NULL,
                    ""CREATION_USER"" NVARCHAR2(100) NOT NULL,
                    ""CREATION_DATE"" TIMESTAMP(7) NULL,
                    ""UPDATE_USER"" NVARCHAR2(100) NULL,
                    ""UPDATE_DATE"" TIMESTAMP(7) NULL,
                    ""REFRESH_TOKEN"" NVARCHAR2(500) NULL,
                    ""REFRESH_TOKEN_EXPIRY"" TIMESTAMP(7) NULL,
                    ""FORCE_LOGOUT_DATE"" TIMESTAMP(7) NULL,
                    CONSTRAINT ""PK_SYS_USERS"" PRIMARY KEY (""Id"")
                )
            ");
            migrationBuilder.Sql(@"CREATE UNIQUE INDEX ""IX_SYS_USERS_USER_NAME"" ON ""SYS_USERS"" (""USER_NAME"")");

            // 3. SYS_SETTINGS
            migrationBuilder.Sql(@"
                CREATE TABLE ""SYS_SETTINGS"" (
                    ""SETTING_CODE"" NUMBER(10) NOT NULL,
                    ""SETTING_DESC"" NVARCHAR2(500) NOT NULL,
                    ""SETTING_VALUE"" NVARCHAR2(2000) NOT NULL,
                    CONSTRAINT ""PK_SYS_SETTINGS"" PRIMARY KEY (""SETTING_CODE"")
                )
            ");

            // 4. SYS_USERS_ROLES
            migrationBuilder.Sql(@"
                CREATE TABLE ""SYS_USERS_ROLES"" (
                    ""Id"" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
                    ""USER_ID"" NUMBER(19) NOT NULL,
                    ""ROLE_ID"" NUMBER(19) NOT NULL,
                    ""ASSIGNED_BY"" NUMBER(19) NULL,
                    ""ASSIGNED_DATE"" TIMESTAMP(7) NULL,
                    ""CREATION_USER"" NVARCHAR2(100) NOT NULL,
                    ""CREATION_DATE"" TIMESTAMP(7) NULL,
                    CONSTRAINT ""PK_SYS_USERS_ROLES"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_SYS_USERS_ROLES_SYS_ROLE_ROLE_ID"" FOREIGN KEY (""ROLE_ID"") REFERENCES ""SYS_ROLE"" (""Id""),
                    CONSTRAINT ""FK_SYS_USERS_ROLES_SYS_USERS_USER_ID"" FOREIGN KEY (""USER_ID"") REFERENCES ""SYS_USERS"" (""Id"") ON DELETE CASCADE
                )
            ");
            migrationBuilder.Sql(@"CREATE INDEX ""IX_SYS_USERS_ROLES_ROLE_ID"" ON ""SYS_USERS_ROLES"" (""ROLE_ID"")");
            migrationBuilder.Sql(@"CREATE INDEX ""IX_SYS_USERS_ROLES_USER_ID"" ON ""SYS_USERS_ROLES"" (""USER_ID"")");

            // 5. SYS_ROLE_SCREEN_PERMISSIONS
            migrationBuilder.Sql(@"
                CREATE TABLE ""SYS_ROLE_SCREEN_PERMISSIONS"" (
                    ""Id"" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
                    ""ROLE_ID"" NUMBER(19) NOT NULL,
                    ""SCREEN_ID"" NUMBER(19) NOT NULL,
                    ""CAN_VIEW"" NUMBER(1) NOT NULL,
                    ""CAN_INSERT"" NUMBER(1) NOT NULL,
                    ""CAN_UPDATE"" NUMBER(1) NOT NULL,
                    ""CAN_DELETE"" NUMBER(1) NOT NULL,
                    ""CREATION_USER"" NVARCHAR2(100) NOT NULL,
                    ""CREATION_DATE"" TIMESTAMP(7) NULL,
                    ""UPDATE_USER"" NVARCHAR2(100) NULL,
                    ""UPDATE_DATE"" TIMESTAMP(7) NULL,
                    CONSTRAINT ""PK_SYS_ROLE_SCREEN_PERMISSIONS"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_SYS_ROLE_SCREEN_PERMISSIONS_SYS_ROLE_ROLE_ID"" FOREIGN KEY (""ROLE_ID"") REFERENCES ""SYS_ROLE"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_SYS_ROLE_SCREEN_PERMISSIONS_SYS_SCREEN_SCREEN_ID"" FOREIGN KEY (""SCREEN_ID"") REFERENCES ""SYS_SCREEN"" (""Id"")
                )
            ");
            migrationBuilder.Sql(@"CREATE INDEX ""IX_SYS_ROLE_SCREEN_PERMISSIONS_ROLE_ID"" ON ""SYS_ROLE_SCREEN_PERMISSIONS"" (""ROLE_ID"")");
            migrationBuilder.Sql(@"CREATE INDEX ""IX_SYS_ROLE_SCREEN_PERMISSIONS_SCREEN_ID"" ON ""SYS_ROLE_SCREEN_PERMISSIONS"" (""SCREEN_ID"")");

            // 6. SYS_USER_SCREEN_PERMISSIONS
            migrationBuilder.Sql(@"
                CREATE TABLE ""SYS_USER_SCREEN_PERMISSIONS"" (
                    ""Id"" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
                    ""USER_ID"" NUMBER(19) NOT NULL,
                    ""SCREEN_ID"" NUMBER(19) NOT NULL,
                    ""CAN_VIEW"" NUMBER(1) NOT NULL,
                    ""CAN_INSERT"" NUMBER(1) NOT NULL,
                    ""CAN_UPDATE"" NUMBER(1) NOT NULL,
                    ""CAN_DELETE"" NUMBER(1) NOT NULL,
                    ""ASSIGNED_BY"" NUMBER(19) NULL,
                    ""AssignedDate"" TIMESTAMP(7) NULL,
                    ""NOTES"" NVARCHAR2(500) NULL,
                    ""CREATION_USER"" NVARCHAR2(100) NOT NULL,
                    ""CREATION_DATE"" TIMESTAMP(7) NULL,
                    ""UPDATE_USER"" NVARCHAR2(100) NULL,
                    ""UPDATE_DATE"" TIMESTAMP(7) NULL,
                    CONSTRAINT ""PK_SYS_USER_SCREEN_PERMISSIONS"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_SYS_USER_SCREEN_PERMISSIONS_SYS_SCREEN_SCREEN_ID"" FOREIGN KEY (""SCREEN_ID"") REFERENCES ""SYS_SCREEN"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_SYS_USER_SCREEN_PERMISSIONS_SYS_USERS_USER_ID"" FOREIGN KEY (""USER_ID"") REFERENCES ""SYS_USERS"" (""Id"") ON DELETE CASCADE
                )
            ");
            migrationBuilder.Sql(@"CREATE INDEX ""IX_SYS_USER_SCREEN_PERMISSIONS_SCREEN_ID"" ON ""SYS_USER_SCREEN_PERMISSIONS"" (""SCREEN_ID"")");
            migrationBuilder.Sql(@"CREATE INDEX ""IX_SYS_USER_SCREEN_PERMISSIONS_USER_ID"" ON ""SYS_USER_SCREEN_PERMISSIONS"" (""USER_ID"")");

            // === SEED DATA ===

            // Seed SYS_SETTINGS (6 settings)
            migrationBuilder.Sql(@"
                MERGE INTO ""SYS_SETTINGS"" t
                USING (
                    SELECT 1 AS SETTING_CODE, CAST('Upload files path' AS NVARCHAR2(500)) AS SETTING_DESC, CAST('/THINKON_FILES/UPLOADS/' AS NVARCHAR2(2000)) AS SETTING_VALUE FROM DUAL UNION ALL
                    SELECT 2, CAST('Maximum file size (bytes)' AS NVARCHAR2(500)), CAST('52428800' AS NVARCHAR2(2000)) FROM DUAL UNION ALL
                    SELECT 3, CAST('Allowed file extensions' AS NVARCHAR2(500)), CAST('.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.csv,.jpg,.jpeg,.png,.gif,.zip,.rar,.7z' AS NVARCHAR2(2000)) FROM DUAL UNION ALL
                    SELECT 4, CAST('Logs path' AS NVARCHAR2(500)), CAST('/THINKON_FILES/LOGS/' AS NVARCHAR2(2000)) FROM DUAL UNION ALL
                    SELECT 5, CAST('Audit fallback path' AS NVARCHAR2(500)), CAST('/THINKON_FILES/LOGS/audit-fallback/' AS NVARCHAR2(2000)) FROM DUAL UNION ALL
                    SELECT 6, CAST('Logos path' AS NVARCHAR2(500)), CAST('/THINKON_FILES/LOGOS/' AS NVARCHAR2(2000)) FROM DUAL
                ) s
                ON (t.""SETTING_CODE"" = s.SETTING_CODE)
                WHEN NOT MATCHED THEN
                    INSERT (""SETTING_CODE"", ""SETTING_DESC"", ""SETTING_VALUE"")
                    VALUES (s.SETTING_CODE, s.SETTING_DESC, s.SETTING_VALUE)
            ");

            // Seed SYS_ROLE: 3 roles (Administrator, Support Technician, Viewer)
            migrationBuilder.Sql(@"
                MERGE INTO ""SYS_ROLE"" t
                USING (
                    SELECT 1 AS Id, N'مدير' AS NAME_LOCAL, 'Administrator' AS NAME_EN, 'Full system access' AS NOTE, 1 AS IS_ACTIVE, 'system' AS CREATION_USER, SYSTIMESTAMP AS CREATION_DATE FROM DUAL UNION ALL
                    SELECT 2, N'فني دعم', 'Support Technician', 'Support ticket management', 1, 'system', SYSTIMESTAMP FROM DUAL UNION ALL
                    SELECT 3, N'مشاهد', 'Viewer', 'Read-only access', 1, 'system', SYSTIMESTAMP FROM DUAL
                ) s
                ON (t.""Id"" = s.Id)
                WHEN NOT MATCHED THEN
                    INSERT (""Id"", ""NAME_LOCAL"", ""NAME_EN"", ""NOTE"", ""IS_ACTIVE"", ""CREATION_USER"", ""CREATION_DATE"")
                    VALUES (s.Id, s.NAME_LOCAL, s.NAME_EN, s.NOTE, s.IS_ACTIVE, s.CREATION_USER, s.CREATION_DATE)
            ");

            // Seed SYS_USERS: 3 users (ahmed, sara, khaled)
            // Passwords: ahmed@123, sara@123, khaled@123 (PBKDF2 with random salt)
            migrationBuilder.Sql(@"
                MERGE INTO ""SYS_USERS"" t
                USING (
                    SELECT
                        1 AS Id,
                        N'أحمد محمد' AS NAME_LOCAL,
                        'Ahmed Mohammed' AS NAME_EN,
                        'ahmed' AS USER_NAME,
                        'js0GFI6EYw/J8uXnfoSYjW1gpLsX/ZmyIex5Dj31OFP3Zbv3hYQaKYlZTebLjNfp' AS PASSWORD,
                        '+966500000002' AS PHONE,
                        NULL AS PHONE2,
                        1 AS ROLE,
                        (SELECT ""Id"" FROM ""SYS_BRANCH"" WHERE ROWNUM = 1) AS BRANCH_ID,
                        (SELECT ""Id"" FROM ""SYS_COMPANY"" WHERE ROWNUM = 1) AS COMPANY_ID,
                        'ahmed@techcompany.com' AS EMAIL,
                        NULL AS LAST_LOGIN_DATE,
                        1 AS IS_ACTIVE,
                        1 AS IS_ADMIN,
                        'system' AS CREATION_USER,
                        SYSTIMESTAMP AS CREATION_DATE,
                        NULL AS UPDATE_USER,
                        NULL AS UPDATE_DATE,
                        NULL AS REFRESH_TOKEN,
                        NULL AS REFRESH_TOKEN_EXPIRY,
                        NULL AS FORCE_LOGOUT_DATE
                    FROM DUAL
                    UNION ALL
                    SELECT
                        2,
                        N'سارة خالد',
                        'Sara Khaled',
                        'sara',
                        'bnKXxv6+376h5swMA9SGi+Q4wnGEWhEhp9QqGjjp/TbkXbEqOB1ygg41DTaSH+OW',
                        '+966500000003',
                        NULL,
                        2,
                        (SELECT ""Id"" FROM ""SYS_BRANCH"" WHERE ROWNUM = 1),
                        (SELECT ""Id"" FROM ""SYS_COMPANY"" WHERE ROWNUM = 1),
                        'sara@techcompany.com',
                        NULL,
                        1,
                        0,
                        'system',
                        SYSTIMESTAMP,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL
                    FROM DUAL
                    UNION ALL
                    SELECT
                        3,
                        N'خالد عمر',
                        'Khaled Omar',
                        'khaled',
                        '2xol84MKMVY4qbVpKtKPNi/19DVKcqN4Bzxh1oH1sWOem2OR8X+0Sdlwc4ichARd',
                        '+966500000004',
                        NULL,
                        3,
                        (SELECT ""Id"" FROM ""SYS_BRANCH"" WHERE ROWNUM = 1) AS BRANCH_ID,
                        (SELECT ""Id"" FROM ""SYS_COMPANY"" WHERE ROWNUM = 1),
                        'khaled@techcompany.com',
                        NULL,
                        1,
                        0,
                        'system',
                        SYSTIMESTAMP,
                        NULL,
                        NULL,
                        NULL,
                        NULL,
                        NULL
                    FROM DUAL
                ) s
                ON (t.""Id"" = s.Id)
                WHEN NOT MATCHED THEN
                    INSERT (""Id"", ""NAME_LOCAL"", ""NAME_EN"", ""USER_NAME"", ""PASSWORD"", ""PHONE"", ""PHONE2"", ""ROLE"", ""BRANCH_ID"", ""COMPANY_ID"", ""EMAIL"", ""LAST_LOGIN_DATE"", ""IS_ACTIVE"", ""IS_ADMIN"", ""CREATION_USER"", ""CREATION_DATE"", ""REFRESH_TOKEN"", ""REFRESH_TOKEN_EXPIRY"", ""FORCE_LOGOUT_DATE"")
                    VALUES (s.Id, s.NAME_LOCAL, s.NAME_EN, s.USER_NAME, s.PASSWORD, s.PHONE, s.PHONE2, s.ROLE, s.BRANCH_ID, s.COMPANY_ID, s.EMAIL, s.LAST_LOGIN_DATE, s.IS_ACTIVE, s.IS_ADMIN, s.CREATION_USER, s.CREATION_DATE, s.REFRESH_TOKEN, s.REFRESH_TOKEN_EXPIRY, s.FORCE_LOGOUT_DATE)
            ");

            // Seed SYS_USERS_ROLES: 3 assignments
            migrationBuilder.Sql(@"
                MERGE INTO ""SYS_USERS_ROLES"" t
                USING (
                    SELECT 1 AS Id, 1 AS USER_ID, 1 AS ROLE_ID, (SELECT ""Id"" FROM ""SYS_SUPER_ADMIN"" WHERE ROWNUM = 1) AS ASSIGNED_BY, SYSTIMESTAMP AS ASSIGNED_DATE, 'system' AS CREATION_USER, SYSTIMESTAMP AS CREATION_DATE FROM DUAL UNION ALL
                    SELECT 2, 2, 2, (SELECT ""Id"" FROM ""SYS_SUPER_ADMIN"" WHERE ROWNUM = 1), SYSTIMESTAMP, 'system', SYSTIMESTAMP FROM DUAL UNION ALL
                    SELECT 3, 3, 3, (SELECT ""Id"" FROM ""SYS_SUPER_ADMIN"" WHERE ROWNUM = 1), SYSTIMESTAMP, 'system', SYSTIMESTAMP FROM DUAL
                ) s
                ON (t.""Id"" = s.Id)
                WHEN NOT MATCHED THEN
                    INSERT (""Id"", ""USER_ID"", ""ROLE_ID"", ""ASSIGNED_BY"", ""ASSIGNED_DATE"", ""CREATION_USER"", ""CREATION_DATE"")
                    VALUES (s.Id, s.USER_ID, s.ROLE_ID, s.ASSIGNED_BY, s.ASSIGNED_DATE, s.CREATION_USER, s.CREATION_DATE)
            ");

            // Seed SYS_ROLE_SCREEN_PERMISSIONS: Admin gets all CRUD on all screens
            migrationBuilder.Sql(@"
                MERGE INTO ""SYS_ROLE_SCREEN_PERMISSIONS"" t
                USING (
                    SELECT 1 AS ROLE_ID, s.""Id"" AS SCREEN_ID, 1 AS CAN_VIEW, 1 AS CAN_INSERT, 1 AS CAN_UPDATE, 1 AS CAN_DELETE, 'system' AS CREATION_USER, SYSTIMESTAMP AS CREATION_DATE
                    FROM ""SYS_SCREEN"" s
                    CROSS JOIN (SELECT 1 AS ROLE_ID FROM DUAL)
                ) src
                ON (t.""ROLE_ID"" = src.ROLE_ID AND t.""SCREEN_ID"" = src.SCREEN_ID)
                WHEN NOT MATCHED THEN
                    INSERT (""ROLE_ID"", ""SCREEN_ID"", ""CAN_VIEW"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_DELETE"", ""CREATION_USER"", ""CREATION_DATE"")
                    VALUES (src.ROLE_ID, src.SCREEN_ID, src.CAN_VIEW, src.CAN_INSERT, src.CAN_UPDATE, src.CAN_DELETE, src.CREATION_USER, src.CREATION_DATE)
            ");

            // Support role gets View/Insert/Update on Dashboard and Tickets
            migrationBuilder.Sql(@"
                MERGE INTO ""SYS_ROLE_SCREEN_PERMISSIONS"" t
                USING (
                    SELECT 2 AS ROLE_ID, s.""Id"" AS SCREEN_ID, 1 AS CAN_VIEW, 1 AS CAN_INSERT, 1 AS CAN_UPDATE, 0 AS CAN_DELETE, 'system' AS CREATION_USER, SYSTIMESTAMP AS CREATION_DATE
                    FROM ""SYS_SCREEN"" s
                    WHERE s.""SCREEN_CODE"" IN ('support-dashboard', 'support-tickets')
                ) src
                ON (t.""ROLE_ID"" = src.ROLE_ID AND t.""SCREEN_ID"" = src.SCREEN_ID)
                WHEN NOT MATCHED THEN
                    INSERT (""ROLE_ID"", ""SCREEN_ID"", ""CAN_VIEW"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_DELETE"", ""CREATION_USER"", ""CREATION_DATE"")
                    VALUES (src.ROLE_ID, src.SCREEN_ID, src.CAN_VIEW, src.CAN_INSERT, src.CAN_UPDATE, src.CAN_DELETE, src.CREATION_USER, src.CREATION_DATE)
            ");

            // Viewer role gets View only on Dashboard
            migrationBuilder.Sql(@"
                MERGE INTO ""SYS_ROLE_SCREEN_PERMISSIONS"" t
                USING (
                    SELECT 3 AS ROLE_ID, s.""Id"" AS SCREEN_ID, 1 AS CAN_VIEW, 0 AS CAN_INSERT, 0 AS CAN_UPDATE, 0 AS CAN_DELETE, 'system' AS CREATION_USER, SYSTIMESTAMP AS CREATION_DATE
                    FROM ""SYS_SCREEN"" s
                    WHERE s.""SCREEN_CODE"" = 'support-dashboard'
                ) src
                ON (t.""ROLE_ID"" = src.ROLE_ID AND t.""SCREEN_ID"" = src.SCREEN_ID)
                WHEN NOT MATCHED THEN
                    INSERT (""ROLE_ID"", ""SCREEN_ID"", ""CAN_VIEW"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_DELETE"", ""CREATION_USER"", ""CREATION_DATE"")
                    VALUES (src.ROLE_ID, src.SCREEN_ID, src.CAN_VIEW, src.CAN_INSERT, src.CAN_UPDATE, src.CAN_DELETE, src.CREATION_USER, src.CREATION_DATE)
            ");

            // Seed SYS_USER_SCREEN_PERMISSIONS: Sara gets read-only access to Reports
            migrationBuilder.Sql(@"
                MERGE INTO ""SYS_USER_SCREEN_PERMISSIONS"" t
                USING (
                    SELECT
                        1 AS Id,
                        2 AS USER_ID,
                        (SELECT s.""Id"" FROM ""SYS_SCREEN"" s WHERE s.""SCREEN_CODE"" = 'support-reports') AS SCREEN_ID,
                        1 AS CAN_VIEW,
                        0 AS CAN_INSERT,
                        0 AS CAN_UPDATE,
                        0 AS CAN_DELETE,
                        (SELECT sa.""Id"" FROM ""SYS_SUPER_ADMIN"" sa WHERE ROWNUM = 1) AS ASSIGNED_BY,
                        SYSTIMESTAMP AS ASSIGNED_DATE,
                        N'Additional read access to reports' AS NOTES,
                        'system' AS CREATION_USER,
                        SYSTIMESTAMP AS CREATION_DATE,
                        NULL AS UPDATE_USER,
                        NULL AS UPDATE_DATE
                    FROM DUAL
                ) s
                ON (t.""Id"" = s.Id)
                WHEN NOT MATCHED THEN
                    INSERT (""Id"", ""USER_ID"", ""SCREEN_ID"", ""CAN_VIEW"", ""CAN_INSERT"", ""CAN_UPDATE"", ""CAN_DELETE"", ""ASSIGNED_BY"", ""AssignedDate"", ""NOTES"", ""CREATION_USER"", ""CREATION_DATE"")
                    VALUES (s.Id, s.USER_ID, s.SCREEN_ID, s.CAN_VIEW, s.CAN_INSERT, s.CAN_UPDATE, s.CAN_DELETE, s.ASSIGNED_BY, s.ASSIGNED_DATE, s.NOTES, s.CREATION_USER, s.CREATION_DATE)
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE ""SYS_USER_SCREEN_PERMISSIONS"" CASCADE CONSTRAINTS");
            migrationBuilder.Sql(@"DROP TABLE ""SYS_ROLE_SCREEN_PERMISSIONS"" CASCADE CONSTRAINTS");
            migrationBuilder.Sql(@"DROP TABLE ""SYS_USERS_ROLES"" CASCADE CONSTRAINTS");
            migrationBuilder.Sql(@"DROP TABLE ""SYS_SETTINGS"" CASCADE CONSTRAINTS");
            migrationBuilder.Sql(@"DROP TABLE ""SYS_USERS"" CASCADE CONSTRAINTS");
            migrationBuilder.Sql(@"DROP TABLE ""SYS_ROLE"" CASCADE CONSTRAINTS");
        }
    }
}
