-- =============================================
-- Rollback Script: ROLLBACK_13_Extend_SYS_AUDIT_LOG_For_Traceability.sql
-- Description: Rollback script for 13_Extend_SYS_AUDIT_LOG_For_Traceability.sql
-- Purpose: Removes all columns and indexes added to SYS_AUDIT_LOG table for traceability
-- Author: System
-- Date: 2024
-- =============================================

-- WARNING: This script will remove all traceability columns from SYS_AUDIT_LOG
-- Data in these columns will be permanently lost
-- Ensure you have a backup before executing this rollback

SET SERVEROUTPUT ON;

BEGIN
    DBMS_OUTPUT.PUT_LINE('Starting rollback of SYS_AUDIT_LOG traceability extensions...');
END;
/

-- Drop composite indexes first (Task 1.6)
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_AUDIT_LOG_ENTITY_DATE';
    DBMS_OUTPUT.PUT_LINE('Dropped index: IDX_AUDIT_LOG_ENTITY_DATE');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1418 THEN
            DBMS_OUTPUT.PUT_LINE('Index IDX_AUDIT_LOG_ENTITY_DATE does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_AUDIT_LOG_ACTOR_DATE';
    DBMS_OUTPUT.PUT_LINE('Dropped index: IDX_AUDIT_LOG_ACTOR_DATE');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1418 THEN
            DBMS_OUTPUT.PUT_LINE('Index IDX_AUDIT_LOG_ACTOR_DATE does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_AUDIT_LOG_COMPANY_DATE';
    DBMS_OUTPUT.PUT_LINE('Dropped index: IDX_AUDIT_LOG_COMPANY_DATE');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1418 THEN
            DBMS_OUTPUT.PUT_LINE('Index IDX_AUDIT_LOG_COMPANY_DATE does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

-- Drop performance indexes (Task 1.5)
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_AUDIT_LOG_SEVERITY';
    DBMS_OUTPUT.PUT_LINE('Dropped index: IDX_AUDIT_LOG_SEVERITY');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1418 THEN
            DBMS_OUTPUT.PUT_LINE('Index IDX_AUDIT_LOG_SEVERITY does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_AUDIT_LOG_CATEGORY';
    DBMS_OUTPUT.PUT_LINE('Dropped index: IDX_AUDIT_LOG_CATEGORY');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1418 THEN
            DBMS_OUTPUT.PUT_LINE('Index IDX_AUDIT_LOG_CATEGORY does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_AUDIT_LOG_ENDPOINT';
    DBMS_OUTPUT.PUT_LINE('Dropped index: IDX_AUDIT_LOG_ENDPOINT');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1418 THEN
            DBMS_OUTPUT.PUT_LINE('Index IDX_AUDIT_LOG_ENDPOINT does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_AUDIT_LOG_BRANCH';
    DBMS_OUTPUT.PUT_LINE('Dropped index: IDX_AUDIT_LOG_BRANCH');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1418 THEN
            DBMS_OUTPUT.PUT_LINE('Index IDX_AUDIT_LOG_BRANCH does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_AUDIT_LOG_CORRELATION';
    DBMS_OUTPUT.PUT_LINE('Dropped index: IDX_AUDIT_LOG_CORRELATION');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -1418 THEN
            DBMS_OUTPUT.PUT_LINE('Index IDX_AUDIT_LOG_CORRELATION does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

-- Drop foreign key constraint (Task 1.3)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP CONSTRAINT FK_AUDIT_LOG_BRANCH';
    DBMS_OUTPUT.PUT_LINE('Dropped foreign key constraint: FK_AUDIT_LOG_BRANCH');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -2443 THEN
            DBMS_OUTPUT.PUT_LINE('Constraint FK_AUDIT_LOG_BRANCH does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

-- Remove column comments
BEGIN
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.CORRELATION_ID IS NULL';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.BRANCH_ID IS NULL';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.HTTP_METHOD IS NULL';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.ENDPOINT_PATH IS NULL';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.REQUEST_PAYLOAD IS NULL';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.RESPONSE_PAYLOAD IS NULL';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.EXECUTION_TIME_MS IS NULL';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.STATUS_CODE IS NULL';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.EXCEPTION_TYPE IS NULL';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.EXCEPTION_MESSAGE IS NULL';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.STACK_TRACE IS NULL';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.SEVERITY IS NULL';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.EVENT_CATEGORY IS NULL';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN SYS_AUDIT_LOG.METADATA IS NULL';
    DBMS_OUTPUT.PUT_LINE('Removed column comments');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Warning: Could not remove all column comments');
END;
/

-- Drop columns added for traceability (Tasks 1.1 and 1.2)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN METADATA';
    DBMS_OUTPUT.PUT_LINE('Dropped column: METADATA');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column METADATA does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN EVENT_CATEGORY';
    DBMS_OUTPUT.PUT_LINE('Dropped column: EVENT_CATEGORY');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column EVENT_CATEGORY does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN SEVERITY';
    DBMS_OUTPUT.PUT_LINE('Dropped column: SEVERITY');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column SEVERITY does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN STACK_TRACE';
    DBMS_OUTPUT.PUT_LINE('Dropped column: STACK_TRACE');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column STACK_TRACE does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN EXCEPTION_MESSAGE';
    DBMS_OUTPUT.PUT_LINE('Dropped column: EXCEPTION_MESSAGE');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column EXCEPTION_MESSAGE does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN EXCEPTION_TYPE';
    DBMS_OUTPUT.PUT_LINE('Dropped column: EXCEPTION_TYPE');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column EXCEPTION_TYPE does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN STATUS_CODE';
    DBMS_OUTPUT.PUT_LINE('Dropped column: STATUS_CODE');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column STATUS_CODE does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN EXECUTION_TIME_MS';
    DBMS_OUTPUT.PUT_LINE('Dropped column: EXECUTION_TIME_MS');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column EXECUTION_TIME_MS does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN RESPONSE_PAYLOAD';
    DBMS_OUTPUT.PUT_LINE('Dropped column: RESPONSE_PAYLOAD');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column RESPONSE_PAYLOAD does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN REQUEST_PAYLOAD';
    DBMS_OUTPUT.PUT_LINE('Dropped column: REQUEST_PAYLOAD');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column REQUEST_PAYLOAD does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN ENDPOINT_PATH';
    DBMS_OUTPUT.PUT_LINE('Dropped column: ENDPOINT_PATH');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column ENDPOINT_PATH does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN HTTP_METHOD';
    DBMS_OUTPUT.PUT_LINE('Dropped column: HTTP_METHOD');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column HTTP_METHOD does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN BRANCH_ID';
    DBMS_OUTPUT.PUT_LINE('Dropped column: BRANCH_ID');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column BRANCH_ID does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYS_AUDIT_LOG DROP COLUMN CORRELATION_ID';
    DBMS_OUTPUT.PUT_LINE('Dropped column: CORRELATION_ID');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -904 THEN
            DBMS_OUTPUT.PUT_LINE('Column CORRELATION_ID does not exist');
        ELSE
            RAISE;
        END IF;
END;
/

COMMIT;

BEGIN
    DBMS_OUTPUT.PUT_LINE('Rollback completed successfully!');
    DBMS_OUTPUT.PUT_LINE('SYS_AUDIT_LOG table has been restored to its original state.');
END;
/

-- Verification query
SELECT 
    COLUMN_NAME, 
    DATA_TYPE, 
    DATA_LENGTH, 
    NULLABLE
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'SYS_AUDIT_LOG'
ORDER BY COLUMN_ID;
