using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Oracle.ManagedDataAccess.Client;
using ThinkOnErp.Domain.Entities;
using ThinkOnErp.Domain.Interfaces;
using ThinkOnErp.Infrastructure.Data;

namespace ThinkOnErp.Infrastructure.Services;

public class OracleSchemaService : IOracleSchemaService
{
    private readonly IServiceScopeFactory _scopeFactory;
    private readonly ILogger<OracleSchemaService> _logger;
    private readonly string _masterConnectionString;
    private readonly string _pdbConnectionString;
    private readonly PasswordHashingService _passwordHashingService;
    private readonly string _devSchemaName;
    private readonly string _devSchemaPassword;
    private readonly List<string> _objectTypesToClone;

    private static readonly HashSet<string> GlobalTables = new(StringComparer.OrdinalIgnoreCase)
    {
        "SYS_SUPER_ADMIN", "SYS_COMPANY", "SYS_SYSTEM", "SYS_SCREEN",
        "SYS_FEATURE", "SYS_SCREEN_FEATURE", "SYS_CURRENCY",
        "SYS_PERFORMANCE_METRICS", "SYS_SLOW_QUERIES", "SYS_SECURITY_THREATS", "SYS_FAILED_LOGINS",
        "__EFMigrationsHistory"
    };

    public OracleSchemaService(
        IServiceScopeFactory scopeFactory,
        IConfiguration configuration,
        ILogger<OracleSchemaService> logger,
        PasswordHashingService passwordHashingService)
    {
        _scopeFactory = scopeFactory;
        _masterConnectionString = configuration.GetConnectionString("OracleDb")
            ?? throw new InvalidOperationException("Connection string 'OracleDb' not found.");
        _pdbConnectionString = _masterConnectionString.Replace(
            "SERVICE_NAME=free)", "SERVICE_NAME=FREEPDB1)", StringComparison.OrdinalIgnoreCase);
        _logger = logger;
        _passwordHashingService = passwordHashingService;

        _devSchemaName = configuration["TenantProvisioning:DeveloperSchemaName"] ?? "DEV_TEMPLATE";
        _devSchemaPassword = configuration["TenantProvisioning:DeveloperSchemaPassword"] ?? "DEV_TEMPLATE";
        _objectTypesToClone = configuration.GetSection("TenantProvisioning:ObjectTypesToClone").Get<List<string>>() 
            ?? new List<string> { "TABLE", "INDEX", "SEQUENCE", "TRIGGER", "CONSTRAINT" };
    }

    public async Task CreateCompanySchemaAsync(string schemaName, string password)
    {
        schemaName = schemaName.ToUpperInvariant();
        _logger.LogInformation("Creating Oracle schema: {SchemaName}", schemaName);

        await using var masterConn = new OracleConnection(_masterConnectionString);
        await masterConn.OpenAsync();

        // Enable Oracle 12c+ script mode to allow regular usernames in CDB
        await ExecuteRawAsync(masterConn, "ALTER SESSION SET \"_ORACLE_SCRIPT\" = TRUE");

        // 1. Create the Oracle user (schema)
        try
        {
            await ExecuteRawAsync(masterConn, $"CREATE USER \"{schemaName}\" IDENTIFIED BY \"{password}\"");
            _logger.LogInformation("User created: {SchemaName}", schemaName);
        }
        catch (OracleException ex) when (ex.Number == 1920)
        {
            _logger.LogWarning("Schema already exists: {SchemaName}", schemaName);
        }

        // 2. Grant necessary privileges, tablespace quota, and ensure account is unlocked
        await ExecuteRawAsync(masterConn,
            $"GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE SYNONYM TO \"{schemaName}\"");
        await ExecuteRawAsync(masterConn,
            $"ALTER USER \"{schemaName}\" QUOTA UNLIMITED ON USERS");
        await ExecuteRawAsync(masterConn,
            $"ALTER USER \"{schemaName}\" ACCOUNT UNLOCK");
        _logger.LogInformation("Privileges and quota granted to: {SchemaName}", schemaName);

        // 3. Clone tenant tables from developer schema
        await CloneFromDeveloperSchemaAsync(masterConn, schemaName);

        // Reset identity sequences for tenant tables in the new schema to start from 1
        var tablesToResetTo1 = new[]
        {
            "SYS_BRANCH", "SYS_USERS", "SYS_USERS_ROLES", "SYS_USER_BRANCHES",
            "SYS_FISCAL_YEAR", "SYS_ROLE", "SYS_SAVED_SEARCH", "SYS_REQUEST_TICKET",
            "SYS_TICKET_COMMENT", "SYS_TICKET_ATTACHMENT"
        };
        foreach (var table in tablesToResetTo1)
        {
            try
            {
                await ExecuteRawAsync(masterConn, $"ALTER TABLE \"{schemaName}\".\"{table}\" MODIFY \"Id\" GENERATED BY DEFAULT AS IDENTITY (START WITH 1)");
                _logger.LogDebug("Reset identity sequence to START WITH 1 for {Schema}.{Table}", schemaName, table);
            }
            catch (Exception ex)
            {
                _logger.LogDebug("Sequence reset skipped for {Schema}.{Table}: {Msg}", schemaName, table, ex.Message);
            }
        }

        // 4. Grant privileges on tenant tables to master user for cross-schema access
        await GrantTenantTableAccessAsync(schemaName, password);

        // 5. Create synonyms for global tables in tenant schema so ALTER SESSION CURRENT_SCHEMA works
        await CreateGlobalSynonymsAsync(schemaName, password);

        _logger.LogInformation("Schema creation completed: {SchemaName}", schemaName);
    }

    public async Task SeedDefaultAdminAsync(string schemaName, string schemaPassword, string defaultPassword, long companyId, long branchId, string creationUser)
    {
        schemaName = schemaName.ToUpperInvariant();
        _logger.LogInformation("Seeding default admin user in schema: {SchemaName}", schemaName);

        await using var tenantConn = await OpenTenantConnectionAsync(schemaName, schemaPassword);

        var hashedPassword = _passwordHashingService.HashPassword(defaultPassword);

        var roleId = 1L;
        try
        {
            var roleSql = $"INSERT INTO \"{schemaName}\".\"SYS_ROLE\" " +
                $"(\"Id\", \"NAME_AR\", \"NAME_EN\", \"NOTE\", \"IS_ACTIVE\", \"CREATION_USER\", \"CREATION_DATE\") " +
                $"VALUES (:roleId, 'مدير النظام', 'Administrator', 'Default system administrator', 1, :creationUser, SYSDATE)";
            await using var roleCmd = tenantConn.CreateCommand();
            roleCmd.CommandText = roleSql;
            roleCmd.Parameters.Add(new OracleParameter("roleId", roleId));
            roleCmd.Parameters.Add(new OracleParameter("creationUser", creationUser));
            await roleCmd.ExecuteNonQueryAsync();
            _logger.LogInformation("Default Administrator role created in {SchemaName}", schemaName);
        }
        catch (OracleException ex) when (ex.Number == 1)
        {
            _logger.LogDebug("Default role already exists in {SchemaName}", schemaName);
        }

        try
        {
            var userSql = $"INSERT INTO \"{schemaName}\".\"SYS_USERS\" " +
                $"(\"Id\", \"NAME_AR\", \"NAME_EN\", \"USER_NAME\", \"PASSWORD\", \"ROLE\", \"COMPANY_ID\", " +
                $"\"IS_ACTIVE\", \"IS_ADMIN\", \"CREATION_USER\", \"CREATION_DATE\") " +
                $"VALUES (1, 'مدير النظام', 'Admin', 'admin', :password, :roleId, :companyId, 1, 1, :creationUser, SYSDATE)";
            await using var userCmd = tenantConn.CreateCommand();
            userCmd.CommandText = userSql;
            userCmd.Parameters.Add(new OracleParameter("password", hashedPassword));
            userCmd.Parameters.Add(new OracleParameter("roleId", roleId));
            userCmd.Parameters.Add(new OracleParameter("companyId", companyId));
            userCmd.Parameters.Add(new OracleParameter("creationUser", creationUser));
            await userCmd.ExecuteNonQueryAsync();
            _logger.LogInformation("Default admin user created in {SchemaName}", schemaName);
        }
        catch (OracleException ex) when (ex.Number == 1)
        {
            _logger.LogDebug("Default admin user already exists in {SchemaName}", schemaName);
        }

        try
        {
            var userBranchSql = $"INSERT INTO \"{schemaName}\".\"SYS_USER_BRANCHES\" " +
                $"(\"USER_ID\", \"BRANCH_ID\", \"IS_PRIMARY\", \"ASSIGNED_BY\", \"ASSIGNED_AT\") " +
                $"VALUES (1, :branchId, 1, :creationUser, SYSDATE)";
            await using var ubCmd = tenantConn.CreateCommand();
            ubCmd.CommandText = userBranchSql;
            ubCmd.Parameters.Add(new OracleParameter("branchId", branchId));
            ubCmd.Parameters.Add(new OracleParameter("creationUser", creationUser));
            await ubCmd.ExecuteNonQueryAsync();
            _logger.LogInformation("Default admin user mapped to branch {BranchId} in {SchemaName}", branchId, schemaName);
        }
        catch (OracleException ex) when (ex.Number == 1)
        {
            _logger.LogDebug("Default admin user branch mapping already exists in {SchemaName}", schemaName);
        }
    }

    private static string BuildTenantConnectionString(string baseConnectionString, string schemaName, string schemaPassword)
    {
        var csb = new OracleConnectionStringBuilder(baseConnectionString)
        {
            UserID = schemaName,
            Password = schemaPassword
        };
        return csb.ConnectionString;
    }

    /// <summary>
    /// Creates a tenant connection, trying PDB (FREEPDB1) first for manually-created schemas,
    /// then falling back to CDB$ROOT for schemas created via the API.
    /// </summary>
    private async Task<OracleConnection> OpenTenantConnectionAsync(string schemaName, string schemaPassword)
    {
        // Try PDB first
        var pdbCs = BuildTenantConnectionString(_pdbConnectionString, schemaName, schemaPassword);
        try
        {
            var conn = new OracleConnection(pdbCs);
            await conn.OpenAsync();
            return conn;
        }
        catch (OracleException ex) when (ex.Number == 1017)
        {
            _logger.LogDebug("PDB connection failed for {Schema}, falling back to CDB", schemaName);
        }

        // Fallback to CDB$ROOT
        var cdbCs = BuildTenantConnectionString(_masterConnectionString, schemaName, schemaPassword);
        var cdbConn = new OracleConnection(cdbCs);
        await cdbConn.OpenAsync();
        return cdbConn;
    }

    /// <summary>
    /// Opens a connection as the master user (THINKON_ERP), trying PDB first then CDB$ROOT.
    /// </summary>
    private async Task<OracleConnection> OpenMasterConnectionAsync()
    {
        // Try PDB first for environments where THINKON_ERP exists there
        try
        {
            var conn = new OracleConnection(_pdbConnectionString);
            await conn.OpenAsync();
            return conn;
        }
        catch (OracleException ex) when (ex.Number == 1017)
        {
            _logger.LogDebug("PDB master connection failed, falling back to CDB");
        }

        var cdbConn = new OracleConnection(_masterConnectionString);
        await cdbConn.OpenAsync();
        return cdbConn;
    }

    public async Task GrantUserPrivilegesAsync(string schemaName)
    {
        schemaName = schemaName.ToUpperInvariant();
        await using var conn = await OpenMasterConnectionAsync();
        await ExecuteRawAsync(conn, $"GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE SYNONYM TO \"{schemaName}\"");
        await ExecuteRawAsync(conn, $"ALTER USER \"{schemaName}\" QUOTA UNLIMITED ON USERS");
    }

    public async Task<bool> UnlockUserAccountAsync(string schemaName)
    {
        schemaName = schemaName.ToUpperInvariant();
        try
        {
            await using var conn = await OpenMasterConnectionAsync();
            await ExecuteRawAsync(conn, $"ALTER USER \"{schemaName}\" ACCOUNT UNLOCK");
            return true;
        }
        catch (OracleException ex) when (ex.Number == 1435 || ex.Number == 65048)
        {
            _logger.LogWarning("Cannot unlock user {Schema}: user does not exist", schemaName);
            return false;
        }
    }

    public async Task SaveRefreshTokenAsync(string schemaName, string schemaPassword, long userId, string refreshToken, DateTime expiryDate)
    {
        schemaName = schemaName.ToUpperInvariant();

        await using var tenantConn = await OpenTenantConnectionAsync(schemaName, schemaPassword);

        var sql = $"UPDATE \"{schemaName}\".\"SYS_USERS\" SET " +
                  $"\"REFRESH_TOKEN\" = :refreshToken, " +
                  $"\"REFRESH_TOKEN_EXPIRY\" = :expiryDate, " +
                  $"\"UPDATE_DATE\" = SYSDATE " +
                  $"WHERE \"Id\" = :userId";

        await using var cmd = tenantConn.CreateCommand();
        cmd.CommandText = sql;
        cmd.Parameters.Add(new OracleParameter("refreshToken", refreshToken));
        cmd.Parameters.Add(new OracleParameter("expiryDate", expiryDate));
        cmd.Parameters.Add(new OracleParameter("userId", userId));
        await cmd.ExecuteNonQueryAsync();
    }

    public async Task<SysUser?> GetUserByUserNameAsync(string schemaName, string schemaPassword, string userName)
    {
        schemaName = schemaName.ToUpperInvariant();

        await using var tenantConn = await OpenTenantConnectionAsync(schemaName, schemaPassword);

        var sql = $"SELECT u.\"Id\", u.\"NAME_AR\", u.\"NAME_EN\", u.\"USER_NAME\", u.\"PASSWORD\", u.\"ROLE\", ub.\"BRANCH_ID\", u.\"COMPANY_ID\", " +
                  $"u.\"IS_ACTIVE\", u.\"IS_ADMIN\", u.\"CREATION_USER\", u.\"CREATION_DATE\", u.\"UPDATE_USER\", u.\"UPDATE_DATE\", " +
                  $"u.\"REFRESH_TOKEN\", u.\"REFRESH_TOKEN_EXPIRY\", u.\"FORCE_LOGOUT_DATE\" " +
                  $"FROM \"{schemaName}\".\"SYS_USERS\" u " +
                  $"LEFT JOIN \"{schemaName}\".\"SYS_USER_BRANCHES\" ub ON u.\"Id\" = ub.\"USER_ID\" AND ub.\"IS_PRIMARY\" = 1 " +
                  $"WHERE u.\"USER_NAME\" = :userName AND u.\"IS_ACTIVE\" = 1";

        await using var cmd = tenantConn.CreateCommand();
        cmd.CommandText = sql;
        cmd.Parameters.Add(new OracleParameter("userName", userName));

        await using var reader = await cmd.ExecuteReaderAsync();
        if (await reader.ReadAsync())
        {
            return new SysUser
            {
                Id = reader.GetInt64(0),
                FullNameAr = reader.GetString(1),
                FullNameEn = reader.GetString(2),
                UserName = reader.GetString(3),
                Password = reader.GetString(4),
                RoleId = reader.IsDBNull(5) ? null : reader.GetInt64(5),
                BranchId = reader.IsDBNull(6) ? null : reader.GetInt64(6),
                CompanyId = reader.IsDBNull(7) ? null : reader.GetInt64(7),
                IsActive = reader.GetInt64(8) == 1,
                IsAdmin = reader.GetInt64(9) == 1,
                CreationUser = reader.GetString(10),
                CreationDate = reader.IsDBNull(11) ? null : reader.GetDateTime(11),
                UpdateUser = reader.IsDBNull(12) ? null : reader.GetString(12),
                UpdateDate = reader.IsDBNull(13) ? null : reader.GetDateTime(13),
                RefreshToken = reader.IsDBNull(14) ? null : reader.GetString(14),
                RefreshTokenExpiry = reader.IsDBNull(15) ? null : reader.GetDateTime(15),
                ForceLogoutDate = reader.IsDBNull(16) ? null : reader.GetDateTime(16)
            };
        }

        return null;
    }

    private async Task BootstrapTablesFromEfModelAsync(OracleConnection connection, string schemaName)
    {
        using var scope = _scopeFactory.CreateScope();
        await using var context = scope.ServiceProvider.GetRequiredService<OracleDbContext>();
        var model = context.Model;

        foreach (var entityType in model.GetEntityTypes())
        {
            var tableName = entityType.GetTableName();
            if (string.IsNullOrEmpty(tableName) || GlobalTables.Contains(tableName))
                continue;

            var createSql = GenerateCreateTableSql(entityType, schemaName, tableName);
            _logger.LogDebug("Creating table {SchemaName}.{TableName}", schemaName, tableName);
            try
            {
                await ExecuteRawAsync(connection, createSql);
            }
            catch (OracleException ex) when (ex.Number == 955)
            {
                _logger.LogDebug("Table {SchemaName}.{TableName} already exists, skipping", schemaName, tableName);
            }
        }
    }

    private static string GenerateCreateTableSql(IEntityType entityType, string schemaName, string tableName)
    {
        var columns = new List<string>();
        var primaryKeys = new List<string>();

        foreach (var prop in entityType.GetProperties())
        {
            var storeId = StoreObjectIdentifier.Table(tableName);
            var colName = prop.GetColumnName(storeId);
            var colType = prop.GetColumnType();

            if (prop.GetValueConverter() != null || string.IsNullOrEmpty(colType))
                colType = GetOracleType(prop);

            var nullable = prop.IsNullable ? "NULL" : "NOT NULL";
            var identity = IsIdentityColumn(prop) ? " GENERATED BY DEFAULT AS IDENTITY" : string.Empty;
            var colDef = $"    \"{colName}\" {colType}{identity} {nullable}";

            columns.Add(colDef);

            if (prop.IsPrimaryKey())
                primaryKeys.Add($"\"{colName}\"");
        }

        var sql = $"CREATE TABLE \"{schemaName}\".\"{tableName}\"\n(\n";
        sql += string.Join(",\n", columns);

        if (primaryKeys.Count > 0)
        {
            sql += $",\n    PRIMARY KEY ({string.Join(", ", primaryKeys)})";
        }

        sql += "\n)";
        return sql;
    }

    private static bool IsIdentityColumn(IProperty prop)
    {
        if (!prop.IsPrimaryKey() || prop.ValueGenerated != ValueGenerated.OnAdd)
            return false;

        var clrType = Nullable.GetUnderlyingType(prop.ClrType) ?? prop.ClrType;
        return clrType == typeof(short)
            || clrType == typeof(int)
            || clrType == typeof(long);
    }

    private static string GetOracleType(IProperty prop)
    {
        var converter = prop.GetValueConverter();
        var clrType = converter != null ? converter.ProviderClrType : prop.ClrType;
        clrType = Nullable.GetUnderlyingType(clrType) ?? clrType;
        var maxLength = prop.GetMaxLength();

        if (clrType == typeof(bool)) return "NUMBER(1)";
        if (clrType == typeof(byte)) return "NUMBER(3)";
        if (clrType == typeof(short)) return "NUMBER(6)";
        if (clrType == typeof(int)) return "NUMBER(10)";
        if (clrType == typeof(long)) return "NUMBER(19)";
        if (clrType == typeof(float)) return "BINARY_FLOAT";
        if (clrType == typeof(double)) return "BINARY_DOUBLE";
        if (clrType == typeof(decimal)) return "NUMBER(18,2)";
        if (clrType == typeof(DateTime)) return "DATE";
        if (clrType == typeof(DateTimeOffset)) return "TIMESTAMP WITH TIME ZONE";
        if (clrType == typeof(TimeSpan)) return "INTERVAL DAY TO SECOND";
        if (clrType == typeof(Guid)) return "RAW(16)";
        if (clrType == typeof(string))
        {
            if (maxLength.HasValue && maxLength > 0 && maxLength <= 4000)
                return $"NVARCHAR2({maxLength})";
            if (maxLength > 4000)
                return "NCLOB";
            return "NVARCHAR2(2000)";
        }
        if (clrType == typeof(byte[]))
        {
            if (maxLength.HasValue && maxLength <= 2000)
                return $"RAW({maxLength})";
            return "BLOB";
        }

        return "NVARCHAR2(255)";
    }

    private static readonly HashSet<string> TenantOnlyTables = new(StringComparer.OrdinalIgnoreCase)
    {
        "SYS_ROLE", "SYS_USERS", "SYS_USERS_ROLES", "SYS_USER_BRANCHES",
        "SYS_FISCAL_YEAR", "SYS_SAVED_SEARCH", "SYS_SEARCH_ANALYTICS",
        "SYS_ROLE_SCREEN_PERMISSIONS", "SYS_USER_SCREEN_PERMISSIONS",
        "SYS_BRANCH", "SYS_BRANCH_FEATURES", "SYS_BRANCH_SCREENS", "SYS_BRANCH_SYSTEMS",
        "SYS_AUDIT_LOG", "SYS_AUDIT_LOG_ARCHIVE", "SYS_RETENTION_POLICIES", "SYS_SETTINGS", "SYS_CODE",
        "SYS_DOCUMENT", "SYS_REQUEST_TICKET", "SYS_TICKET_ATTACHMENT", "SYS_TICKET_CATEGORY", "SYS_TICKET_COMMENT",
        "SYS_TICKET_CONFIG", "SYS_TICKET_PRIORITY", "SYS_TICKET_STATUS", "SYS_TICKET_TYPE"
    };

    private async Task GrantTenantTableAccessAsync(string schemaName, string password)
    {
        await using var tenantConn = await OpenTenantConnectionAsync(schemaName, password);

        var masterUser = "THINKON_ERP";
        foreach (var table in TenantOnlyTables)
        {
            try
            {
                await ExecuteRawAsync(tenantConn,
                    $"GRANT SELECT, INSERT, UPDATE, DELETE ON \"{table}\" TO \"{masterUser}\"");
                _logger.LogDebug("Granted access on {Schema}.{Table} to {User}", schemaName, table, masterUser);
            }
            catch (OracleException ex) when (ex.Number == 942)
            {
                _logger.LogDebug("Table {Schema}.{Table} not found, skipping grant", schemaName, table);
            }
        }
    }

    private async Task CreateGlobalSynonymsAsync(string schemaName, string password)
    {
        await using var tenantConn = await OpenTenantConnectionAsync(schemaName, password);

        // Create a synonym in the tenant schema for each global table
        foreach (var table in GlobalTables)
        {
            if (table == "__EFMigrationsHistory")
                continue;

            try
            {
                await ExecuteRawAsync(tenantConn,
                    $"CREATE SYNONYM \"{table}\" FOR \"THINKON_ERP\".\"{table}\"");
                _logger.LogDebug("Synonym created: {Schema}.{Table} -> THINKON_ERP.{Table}", schemaName, table);
            }
            catch (OracleException ex) when (ex.Number == 955)
            {
                _logger.LogDebug("Synonym already exists: {Schema}.{Table}", schemaName, table);
            }
        }
    }

    private static async Task ExecuteRawAsync(OracleConnection connection, string sql)
    {
        await using var cmd = connection.CreateCommand();
        cmd.CommandText = sql;
        await cmd.ExecuteNonQueryAsync();
    }

    public async Task UpgradeExistingTenantSchemasAsync()
    {
        _logger.LogInformation("Upgrading all existing tenant schemas against template {SourceSchema}", _devSchemaName);
        
        await using var masterConn = await OpenMasterConnectionAsync();

        // Get all company schemas
        var schemas = new List<string>();
        try
        {
            await using var cmd = masterConn.CreateCommand();
            cmd.CommandText = "SELECT COMPANY_SCHEMA FROM \"THINKON_ERP\".\"SYS_COMPANY\" WHERE COMPANY_SCHEMA IS NOT NULL";
            await using var reader = await cmd.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var schema = reader.GetString(0);
                if (!string.IsNullOrEmpty(schema))
                    schemas.Add(schema);
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to query company schemas for upgrade");
            return;
        }

        if (schemas.Count == 0)
        {
            _logger.LogInformation("No existing tenant schemas to upgrade");
            return;
        }

        foreach (var schema in schemas)
        {
            // Skip the template schema itself if it is in the list
            if (string.Equals(schema, _devSchemaName, StringComparison.OrdinalIgnoreCase))
                continue;

            try
            {
                _logger.LogInformation("Syncing schema: {Schema}", schema);
                await CloneFromDeveloperSchemaAsync(masterConn, schema);
                
                // Regenerate synonyms & table access grants to ensure everything is correct
                await GrantTenantTableAccessAsync(schema, schema);
                await CreateGlobalSynonymsAsync(schema, schema);
                
                _logger.LogInformation("Upgraded and synced tenant schema: {Schema}", schema);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to upgrade tenant schema: {Schema}", schema);
            }
        }
    }

    public async Task SyncTenantSchemaAsync(string schemaName, string schemaPassword)
    {
        schemaName = schemaName.ToUpperInvariant();
        _logger.LogInformation("Syncing tenant schema {SchemaName} with template {SourceSchema}", schemaName, _devSchemaName);
        
        await using var masterConn = await OpenMasterConnectionAsync();
        await CloneFromDeveloperSchemaAsync(masterConn, schemaName);
        
        // Ensure access privileges and synonyms are up to date
        await GrantTenantTableAccessAsync(schemaName, schemaPassword);
        await CreateGlobalSynonymsAsync(schemaName, schemaPassword);
    }

    public async Task ProvisionDeveloperSchemaAsync()
    {
        _logger.LogInformation("Ensuring developer template schema exists: {SchemaName}", _devSchemaName);

        await using var masterConn = await OpenMasterConnectionAsync();

        // Enable Oracle 12c+ script mode
        await ExecuteRawAsync(masterConn, "ALTER SESSION SET \"_ORACLE_SCRIPT\" = TRUE");

        // 1. Create the Oracle user for developer template if not exists
        try
        {
            await ExecuteRawAsync(masterConn, $"CREATE USER \"{_devSchemaName}\" IDENTIFIED BY \"{_devSchemaPassword}\"");
            _logger.LogInformation("Developer template user created: {SchemaName}", _devSchemaName);
        }
        catch (OracleException ex) when (ex.Number == 1920)
        {
            _logger.LogDebug("Developer template schema already exists: {SchemaName}", _devSchemaName);
        }

        // 2. Grant privileges and tablespace quota
        await ExecuteRawAsync(masterConn,
            $"GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE SYNONYM TO \"{_devSchemaName}\"");
        await ExecuteRawAsync(masterConn,
            $"ALTER USER \"{_devSchemaName}\" QUOTA UNLIMITED ON USERS");
        await ExecuteRawAsync(masterConn,
            $"ALTER USER \"{_devSchemaName}\" ACCOUNT UNLOCK");

        // 3. Bootstrap tables from EF model into the template schema
        await BootstrapTablesFromEfModelAsync(masterConn, _devSchemaName);
        
        // 4. Create synonyms for global tables in the developer template schema so it has full connectivity
        await CreateGlobalSynonymsAsync(_devSchemaName, _devSchemaPassword);

        // 5. Seed the template schema with comprehensive test data
        try
        {
            await SeedDeveloperTemplateAsync();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to seed developer template schema during provisioning");
        }

        _logger.LogInformation("Developer template schema provisioning/verification completed: {SchemaName}", _devSchemaName);
    }

    public async Task SeedDeveloperTemplateAsync()
    {
        _logger.LogInformation("Seeding developer template schema: {SchemaName}", _devSchemaName);

        string scriptPath = Path.Combine(AppContext.BaseDirectory, "Database", "Scripts", "92_Seed_Developer_Template.sql");
        if (!File.Exists(scriptPath))
        {
            var dir = AppContext.BaseDirectory;
            while (!string.IsNullOrEmpty(dir))
            {
                var candidate = Path.Combine(dir, "Database", "Scripts", "92_Seed_Developer_Template.sql");
                if (File.Exists(candidate))
                {
                    scriptPath = candidate;
                    break;
                }
                dir = Path.GetDirectoryName(dir);
            }
        }

        if (!File.Exists(scriptPath))
        {
            _logger.LogWarning("Seed script not found: {Path}", scriptPath);
            return;
        }

        var scriptContent = await File.ReadAllTextAsync(scriptPath);
        var statements = scriptContent
            .Split(new[] { "\r\n/\r\n", "\n/\n", "\r/\r", "\r\n/\n", "\n/\r\n" }, StringSplitOptions.RemoveEmptyEntries)
            .Select(s => s.Trim())
            .Where(s => !string.IsNullOrWhiteSpace(s))
            .ToList();

        var hashedPassword = _passwordHashingService.HashPassword("Password@123");

        await using var conn = await OpenTenantConnectionAsync(_devSchemaName, _devSchemaPassword);

        foreach (var stmt in statements)
        {
            var query = stmt.Replace("'TEMP_HASH'", $"'{hashedPassword}'", StringComparison.OrdinalIgnoreCase);
            
            // Clean up slash characters if they are still at the end of the query
            if (query.EndsWith("/", StringComparison.Ordinal))
            {
                query = query.Substring(0, query.Length - 1).Trim();
            }

            try
            {
                await ExecuteRawAsync(conn, query);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to run seed statement: {Stmt}", query.Length > 200 ? query.Substring(0, 200) + "..." : query);
                throw;
            }
        }

        // Reset identity sequences for tables with hardcoded IDs to prevent duplicate key errors on EF insertions
        var tablesToReset = new[]
        {
            "SYS_ROLE", "SYS_BRANCH", "SYS_USERS", "SYS_USERS_ROLES", "SYS_USER_BRANCHES",
            "SYS_FISCAL_YEAR", "SYS_RETENTION_POLICIES", "SYS_TICKET_PRIORITY", "SYS_TICKET_STATUS",
            "SYS_TICKET_TYPE", "SYS_TICKET_CATEGORY", "SYS_TICKET_CONFIG", "SYS_REQUEST_TICKET",
            "SYS_TICKET_COMMENT", "SYS_SAVED_SEARCH"
        };
        
        foreach (var table in tablesToReset)
        {
            try
            {
                try
                {
                    await ExecuteRawAsync(conn, $"ALTER TABLE \"{_devSchemaName}\".\"{table}\" MODIFY \"Id\" GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)");
                    _logger.LogDebug("Reset identity sequence for table {Table} using START WITH LIMIT VALUE", table);
                }
                catch (Exception exLimit)
                {
                    _logger.LogDebug(exLimit, "START WITH LIMIT VALUE failed for table {Table}, falling back to dynamic start value", table);
                    long nextId = 1;
                    using (var cmd = conn.CreateCommand())
                    {
                        cmd.CommandText = $"SELECT NVL(MAX(\"Id\"), 0) FROM \"{_devSchemaName}\".\"{table}\"";
                        var maxVal = await cmd.ExecuteScalarAsync();
                        if (maxVal != null && maxVal != DBNull.Value)
                        {
                            nextId = Convert.ToInt64(maxVal) + 1;
                        }
                    }

                    await ExecuteRawAsync(conn, $"ALTER TABLE \"{_devSchemaName}\".\"{table}\" MODIFY \"Id\" GENERATED BY DEFAULT AS IDENTITY (START WITH {nextId})");
                    _logger.LogDebug("Reset identity sequence for table {Table} to next ID {NextId}", table, nextId);
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to reset identity sequence for table {Table}", table);
            }
        }

        _logger.LogInformation("Successfully seeded developer template schema: {SchemaName}", _devSchemaName);
    }

    private async Task CloneFromDeveloperSchemaAsync(OracleConnection connection, string targetSchema)
    {
        _logger.LogInformation("Cloning schema structure from {SourceSchema} to {TargetSchema}", _devSchemaName, targetSchema);

        var objects = new List<(string Name, string Type)>();
        
        var query = @"
            SELECT OBJECT_NAME, OBJECT_TYPE 
            FROM ALL_OBJECTS 
            WHERE OWNER = :sourceSchema 
              AND (
                (OBJECT_TYPE = 'TABLE' AND OBJECT_NAME NOT LIKE 'BIN$%') OR
                (OBJECT_TYPE = 'INDEX' AND OBJECT_NAME NOT LIKE 'SYS_%') OR
                (OBJECT_TYPE = 'SEQUENCE' AND OBJECT_NAME NOT LIKE 'ISEQ$$%')
              )
            ORDER BY 
              CASE OBJECT_TYPE 
                WHEN 'SEQUENCE' THEN 1
                WHEN 'TABLE' THEN 2
                WHEN 'INDEX' THEN 3
                ELSE 4
              END";

        await using (var cmd = connection.CreateCommand())
        {
            cmd.CommandText = query;
            cmd.Parameters.Add(new OracleParameter("sourceSchema", _devSchemaName));
            await using var reader = await cmd.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                objects.Add((reader.GetString(0), reader.GetString(1)));
            }
        }

        _logger.LogInformation("Found {Count} objects to clone from {SourceSchema}", objects.Count, _devSchemaName);

        // Set DBMS_METADATA session transform options for portable DDL
        try
        {
            await using (var cmd = connection.CreateCommand())
            {
                cmd.CommandText = "BEGIN DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', FALSE); END;";
                await cmd.ExecuteNonQueryAsync();
            }
            await using (var cmd = connection.CreateCommand())
            {
                cmd.CommandText = "BEGIN DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'TABLESPACE', FALSE); END;";
                await cmd.ExecuteNonQueryAsync();
            }
            await using (var cmd = connection.CreateCommand())
            {
                cmd.CommandText = "BEGIN DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', FALSE); END;";
                await cmd.ExecuteNonQueryAsync();
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to set DBMS_METADATA session transform parameters. Output DDL may contain storage clauses.");
        }

        foreach (var obj in objects)
        {
            if (GlobalTables.Contains(obj.Name))
                continue;

            if (!TenantOnlyTables.Contains(obj.Name) && obj.Type == "TABLE")
                continue;

            _logger.LogDebug("Retrieving DDL for {Type} {Name} from {SourceSchema}", obj.Type, obj.Name, _devSchemaName);

            string ddl = "";
            try
            {
                await using var cmd = connection.CreateCommand();
                cmd.CommandText = "SELECT DBMS_METADATA.GET_DDL(:objType, :objName, :sourceSchema) FROM DUAL";
                cmd.Parameters.Add(new OracleParameter("objType", obj.Type));
                cmd.Parameters.Add(new OracleParameter("objName", obj.Name));
                cmd.Parameters.Add(new OracleParameter("sourceSchema", _devSchemaName));

                var result = await cmd.ExecuteScalarAsync();
                ddl = result?.ToString() ?? "";
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Failed to get DDL for {Type} {Name}", obj.Type, obj.Name);
                continue;
            }

            if (string.IsNullOrWhiteSpace(ddl))
                continue;

            // Retarget DDL to the target schema name
            var pattern = $"\"{_devSchemaName}\".";
            var replacement = $"\"{targetSchema}\".";
            ddl = ddl.Replace(pattern, replacement, StringComparison.OrdinalIgnoreCase);
            ddl = ddl.Replace($"\"{_devSchemaName}\"", $"\"{targetSchema}\"", StringComparison.OrdinalIgnoreCase);

            _logger.LogDebug("Executing DDL for {Type} {TargetSchema}.{Name}", obj.Type, targetSchema, obj.Name);
            try
            {
                await using var cmd = connection.CreateCommand();
                cmd.CommandText = ddl;
                await cmd.ExecuteNonQueryAsync();
            }
            catch (OracleException ex) when (ex.Number == 955 || ex.Number == 2261 || ex.Number == 2264 || ex.Number == 1917)
            {
                _logger.LogDebug("Object/constraint {Name} already exists or is redundant: {Msg}", obj.Name, ex.Message);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Error creating cloned {Type} {TargetSchema}.{Name}. DDL was: {Ddl}", obj.Type, targetSchema, obj.Name, ddl);
            }
        }
    }

    public async Task<(long BranchId, long FiscalYearId)> ProvisionTenantBranchAndFiscalYearAsync(
        string schemaName,
        string schemaPassword,
        long companyId,
        string? branchNameAr, string? branchNameEn,
        string? branchPhone, string? branchMobile,
        string? branchFax, string? branchEmail,
        string? taxNumber, int defaultLang,
        long? baseCurrencyId, int roundingRules,
        string? branchLogoPath, string creationUser)
    {
        schemaName = schemaName.ToUpperInvariant();
        _logger.LogInformation("Provisioning tenant branch and fiscal year in schema: {SchemaName}", schemaName);

        await using var tenantConn = await OpenTenantConnectionAsync(schemaName, schemaPassword);

        // 1. Insert Branch
        var branchSql = $@"
            INSERT INTO ""{schemaName}"".""SYS_BRANCH"" 
            (""COMPANY_ID"", ""NAME_AR"", ""NAME_EN"", ""PHONE"", ""MOBILE"", ""FAX"", ""EMAIL"", ""IS_HEAD_BRANCH"", ""TAX_NUMBER"", ""DEFAULT_LANG"", ""BASE_CURRENCY_ID"", ""ROUNDING_RULES"", ""BRANCH_LOGO_PATH"", ""IS_ACTIVE"", ""CREATION_USER"", ""CREATION_DATE"")
            VALUES (:companyId, :nameAr, :nameEn, :phone, :mobile, :fax, :email, 1, :taxNumber, :defaultLang, :baseCurrencyId, :roundingRules, :logoPath, 1, :creationUser, SYSDATE)
            RETURNING ""Id"" INTO :branchId";

        await using var branchCmd = tenantConn.CreateCommand();
        branchCmd.CommandText = branchSql;
        branchCmd.Parameters.Add(new OracleParameter("companyId", companyId));
        branchCmd.Parameters.Add(new OracleParameter("nameAr", branchNameAr ?? "Default Branch"));
        branchCmd.Parameters.Add(new OracleParameter("nameEn", branchNameEn ?? "Default Branch"));
        branchCmd.Parameters.Add(new OracleParameter("phone", (object?)branchPhone ?? DBNull.Value));
        branchCmd.Parameters.Add(new OracleParameter("mobile", (object?)branchMobile ?? DBNull.Value));
        branchCmd.Parameters.Add(new OracleParameter("fax", (object?)branchFax ?? DBNull.Value));
        branchCmd.Parameters.Add(new OracleParameter("email", (object?)branchEmail ?? DBNull.Value));
        branchCmd.Parameters.Add(new OracleParameter("taxNumber", (object?)taxNumber ?? DBNull.Value));
        branchCmd.Parameters.Add(new OracleParameter("defaultLang", defaultLang));
        branchCmd.Parameters.Add(new OracleParameter("baseCurrencyId", baseCurrencyId ?? 1L));
        branchCmd.Parameters.Add(new OracleParameter("roundingRules", roundingRules));
        branchCmd.Parameters.Add(new OracleParameter("logoPath", (object?)branchLogoPath ?? DBNull.Value));
        branchCmd.Parameters.Add(new OracleParameter("creationUser", creationUser));

        var branchIdParam = new OracleParameter("branchId", OracleDbType.Decimal)
        {
            Direction = System.Data.ParameterDirection.Output
        };
        branchCmd.Parameters.Add(branchIdParam);
        await branchCmd.ExecuteNonQueryAsync();

        var branchId = Convert.ToInt64(branchIdParam.Value.ToString());
        _logger.LogInformation("Successfully created branch with ID {BranchId} in schema {SchemaName}", branchId, schemaName);

        // 2. Insert Fiscal Year
        var fyCode = $"FY{DateTime.Now.Year}";
        var fyNameAr = $"السنة المالية {DateTime.Now.Year}";
        var fyNameEn = $"Fiscal Year {DateTime.Now.Year}";
        var startDate = new DateTime(DateTime.Now.Year, 1, 1);
        var endDate = new DateTime(DateTime.Now.Year, 12, 31);

        var fySql = $@"
            INSERT INTO ""{schemaName}"".""SYS_FISCAL_YEAR""
            (""COMPANY_ID"", ""BRANCH_ID"", ""FISCAL_YEAR_CODE"", ""NAME_AR"", ""NAME_EN"", ""START_DATE"", ""END_DATE"", ""IS_CLOSED"", ""IS_ACTIVE"", ""CREATION_USER"", ""CREATION_DATE"")
            VALUES (:companyId, :branchId, :fyCode, :nameAr, :nameEn, :startDate, :endDate, 0, 1, :creationUser, SYSDATE)
            RETURNING ""Id"" INTO :fyId";

        await using var fyCmd = tenantConn.CreateCommand();
        fyCmd.CommandText = fySql;
        fyCmd.Parameters.Add(new OracleParameter("companyId", companyId));
        fyCmd.Parameters.Add(new OracleParameter("branchId", branchId));
        fyCmd.Parameters.Add(new OracleParameter("fyCode", fyCode));
        fyCmd.Parameters.Add(new OracleParameter("nameAr", fyNameAr));
        fyCmd.Parameters.Add(new OracleParameter("nameEn", fyNameEn));
        fyCmd.Parameters.Add(new OracleParameter("startDate", startDate));
        fyCmd.Parameters.Add(new OracleParameter("endDate", endDate));
        fyCmd.Parameters.Add(new OracleParameter("creationUser", creationUser));

        var fyIdParam = new OracleParameter("fyId", OracleDbType.Decimal)
        {
            Direction = System.Data.ParameterDirection.Output
        };
        fyCmd.Parameters.Add(fyIdParam);
        await fyCmd.ExecuteNonQueryAsync();

        var fiscalYearId = Convert.ToInt64(fyIdParam.Value.ToString());
        _logger.LogInformation("Successfully created fiscal year with ID {FiscalYearId} in schema {SchemaName}", fiscalYearId, schemaName);

        return (branchId, fiscalYearId);
    }

    public async Task UpdateTenantBranchLogoPathAsync(string schemaName, string schemaPassword, long branchId, string? logoPath, string updateUser)
    {
        schemaName = schemaName.ToUpperInvariant();
        await using var tenantConn = await OpenTenantConnectionAsync(schemaName, schemaPassword);
        await using var cmd = tenantConn.CreateCommand();
        cmd.CommandText = $@"
            UPDATE ""{schemaName}"".""SYS_BRANCH""
            SET ""BRANCH_LOGO_PATH"" = :logoPath, ""UPDATE_USER"" = :updateUser, ""UPDATE_DATE"" = SYSDATE
            WHERE ""Id"" = :branchId";
        cmd.Parameters.Add(new OracleParameter("logoPath", (object?)logoPath ?? DBNull.Value));
        cmd.Parameters.Add(new OracleParameter("updateUser", updateUser));
        cmd.Parameters.Add(new OracleParameter("branchId", branchId));
        await cmd.ExecuteNonQueryAsync();
        _logger.LogInformation("Updated branch logo path in tenant schema {SchemaName} for branch ID {BranchId}", schemaName, branchId);
    }

    public async Task<(string? BranchNameEn, string? BranchNameAr, string? BranchLogoPath)> GetBranchDetailsAsync(string schemaName, long branchId)
    {
        if (string.IsNullOrEmpty(schemaName) || branchId <= 0) return (null, null, null);
        try
        {
            await using var conn = await OpenMasterConnectionAsync();
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = $@"
                SELECT NAME_EN, NAME_AR, BRANCH_LOGO_PATH
                FROM ""{schemaName.ToUpperInvariant()}"".""SYS_BRANCH""
                WHERE ""Id"" = :branchId";
            cmd.Parameters.Add(new OracleParameter("branchId", branchId));
            await using var reader = await cmd.ExecuteReaderAsync();
            if (await reader.ReadAsync())
            {
                var nameEn = reader.IsDBNull(0) ? null : reader.GetString(0);
                var nameAr = reader.IsDBNull(1) ? null : reader.GetString(1);
                var logoPath = reader.IsDBNull(2) ? null : reader.GetString(2);
                return (nameEn, nameAr, logoPath);
            }
        }
        catch (Exception ex)
        {
            _logger.LogDebug(ex, "Failed to fetch branch details for schema {Schema}, branchId {BranchId}", schemaName, branchId);
        }
        return (null, null, null);
    }
}
