-- Apply only to DEV_TEMPLATE. Existing personnel and users remain unlinked.
-- Oracle DDL commits automatically. Run preflight before deploying the API.
WHENEVER SQLERROR EXIT SQL.SQLCODE
DECLARE
    column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO column_count FROM ALL_TAB_COLUMNS
    WHERE OWNER = 'DEV_TEMPLATE' AND TABLE_NAME = 'HR_EMPLOYEE' AND COLUMN_NAME = 'USER_ID';
    IF column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DEV_TEMPLATE.HR_EMPLOYEE ADD (USER_ID NUMBER(19) NULL)';
    END IF;
END;
/
DECLARE
    constraint_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO constraint_count FROM ALL_CONSTRAINTS
    WHERE OWNER = 'DEV_TEMPLATE' AND TABLE_NAME = 'HR_EMPLOYEE' AND CONSTRAINT_NAME = 'UX_HR_EMPLOYEE_USER_ID';
    IF constraint_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DEV_TEMPLATE.HR_EMPLOYEE ADD CONSTRAINT UX_HR_EMPLOYEE_USER_ID UNIQUE (USER_ID)';
    END IF;
    SELECT COUNT(*) INTO constraint_count FROM ALL_CONSTRAINTS
    WHERE OWNER = 'DEV_TEMPLATE' AND TABLE_NAME = 'HR_EMPLOYEE' AND CONSTRAINT_NAME = 'FK_HR_EMPLOYEE_USER';
    IF constraint_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE DEV_TEMPLATE.HR_EMPLOYEE ADD CONSTRAINT FK_HR_EMPLOYEE_USER FOREIGN KEY (USER_ID) REFERENCES DEV_TEMPLATE.SYS_USERS ("Id")';
    END IF;
END;
/
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE FROM ALL_TAB_COLUMNS
WHERE OWNER = 'DEV_TEMPLATE' AND TABLE_NAME = 'HR_EMPLOYEE' AND COLUMN_NAME = 'USER_ID';
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, VALIDATED, DELETE_RULE
FROM ALL_CONSTRAINTS WHERE OWNER = 'DEV_TEMPLATE' AND TABLE_NAME = 'HR_EMPLOYEE'
AND CONSTRAINT_NAME IN ('UX_HR_EMPLOYEE_USER_ID', 'FK_HR_EMPLOYEE_USER');
