using MediatR;
using ThinkOnErp.Application.DTOs.Auth;
using ThinkOnErp.Domain.Interfaces;

namespace ThinkOnErp.Application.Features.Auth.Commands.Login;

/// <summary>
/// Handler for LoginCommand.
/// Authenticates user credentials and generates JWT token.
/// Note: JWT token generation will be handled by Infrastructure layer service.
/// </summary>
public class LoginCommandHandler : IRequestHandler<LoginCommand, TokenDto?>
{
    private readonly IAuthRepository _authRepository;

    public LoginCommandHandler(IAuthRepository authRepository)
    {
        _authRepository = authRepository;
    }

    public async Task<TokenDto?> Handle(LoginCommand request, CancellationToken cancellationToken)
    {
        // Authenticate user (password hashing handled in Infrastructure layer)
        var user = await _authRepository.AuthenticateAsync(request.UserName, request.Password);

        if (user == null)
            return null;

        // Token generation will be handled by Infrastructure layer JWT service
        // This is a placeholder - actual implementation will be in the API layer
        // where we have access to the JWT service
        return new TokenDto
        {
            AccessToken = string.Empty, // Will be generated by JWT service
            ExpiresAt = DateTime.UtcNow.AddMinutes(60),
            TokenType = "Bearer"
        };
    }
}
