using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Oracle.ManagedDataAccess.Client;
using ThinkOnErp.Domain.Entities;
using ThinkOnErp.Infrastructure.Data;

internal static class HrRepair
{
    public static async Task Apply(OracleConnection connection, List<string> report)
    {
        async Task Run(string sql) { await using var c = connection.CreateCommand(); c.CommandText = sql; c.CommandTimeout = 30; await c.ExecuteNonQueryAsync(); }
        async Task<long> Count(string sql) { await using var c = connection.CreateCommand(); c.CommandText = sql; return Convert.ToInt64(await c.ExecuteScalarAsync()); }
        await Run("ALTER SESSION SET CURRENT_SCHEMA = DEV_TEMPLATE");
        if (await Count("SELECT COUNT(*) FROM ALL_CONSTRAINTS c WHERE c.OWNER='DEV_TEMPLATE' AND c.TABLE_NAME='HR_LEAVE_BALANCE' AND c.CONSTRAINT_TYPE='U' AND (SELECT LISTAGG(x.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY x.COLUMN_NAME) FROM ALL_CONS_COLUMNS x WHERE x.OWNER=c.OWNER AND x.CONSTRAINT_NAME=c.CONSTRAINT_NAME)='EMPLOYEE_CODE,LEAVE_TYPE_CODE,YEAR_NO'") == 0)
            await Run("ALTER TABLE DEV_TEMPLATE.HR_LEAVE_BALANCE ADD CONSTRAINT UX_HR_LEAVE_BALANCE_YEAR UNIQUE (EMPLOYEE_CODE,LEAVE_TYPE_CODE,YEAR_NO)");
        if (await Count("SELECT COUNT(*) FROM ALL_TABLES WHERE OWNER='DEV_TEMPLATE' AND TABLE_NAME='HR_GL_POSTING_CONFIG'") == 0)
        {
            await Run("CREATE TABLE DEV_TEMPLATE.HR_GL_POSTING_CONFIG (BRANCH_ID NUMBER(19) PRIMARY KEY, SALARYEXPENSE NVARCHAR2(100) NOT NULL, EMPLOYERSSCEXPENSE NVARCHAR2(100) NOT NULL, SALARYPAYABLE NVARCHAR2(100) NOT NULL, SSCPAYABLE NVARCHAR2(100) NOT NULL, TAXPAYABLE NVARCHAR2(100) NOT NULL, DEDUCTIONSPAYABLE NVARCHAR2(100) NOT NULL, CURRENCY_ID NUMBER(19) NOT NULL, VOUCHER_TYPE NUMBER(10) NOT NULL, CONSTRAINT FK_HR_GL_CONFIG_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES DEV_TEMPLATE.SYS_BRANCH (\"Id\"))");
            report.Add("Created HR_GL_POSTING_CONFIG. Posting accounts require explicit configuration; no account choices guessed.");
        }
        using var db = new OracleDbContext(new DbContextOptionsBuilder<OracleDbContext>().UseOracle(connection,
            o => o.UseOracleSQLCompatibility(OracleSQLCompatibility.DatabaseVersion19)).Options);
        foreach (var entity in db.Model.GetEntityTypes().Where(e => new[] { "HR_ATTENDANCE_DAY", "HR_ATTENDANCE_POLICY", "HR_RAW_ATTENDANCE" }.Contains(e.GetTableName())))
        {
            var table = entity.GetTableName()!;
            var identifier = StoreObjectIdentifier.Table(table, null);
            var defaults = Activator.CreateInstance(entity.ClrType)!;
            foreach (var p in entity.GetProperties())
            {
                var column = p.GetColumnName(identifier)!;
                if (await Count($"SELECT COUNT(*) FROM ALL_TAB_COLUMNS WHERE OWNER='DEV_TEMPLATE' AND TABLE_NAME='{table}' AND COLUMN_NAME='{column}'") > 0) continue;
                var value = p.PropertyInfo!.GetValue(defaults);
                var literal = value is bool b ? b ? "1" : "0" : value is string s ? "'" + s.Replace("'", "''") + "'" : Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture);
                var definition = p.GetColumnType() + (p.IsNullable ? " NULL" : $" DEFAULT {literal} NOT NULL");
                await Run($"ALTER TABLE DEV_TEMPLATE.\"{table}\" ADD (\"{column}\" {definition})");
                report.Add($"Added {table}.{column}: {definition}");
            }
        }
        foreach (var table in new[] { "HR_SALARY_STRUCTURE", "HR_SALARY_STRUCTURE_LINE", "HR_EMPLOYEE_SHIFT_ASSIGNMENT" })
            if (await Count($"SELECT COUNT(*) FROM ALL_TAB_IDENTITY_COLS WHERE OWNER='DEV_TEMPLATE' AND TABLE_NAME='{table}' AND COLUMN_NAME='ID'") > 0)
                await Run($"ALTER TABLE DEV_TEMPLATE.{table} MODIFY (ID GENERATED BY DEFAULT ON NULL AS IDENTITY)");
        await using (var transaction = connection.BeginTransaction())
        {
            foreach (var map in new[] {
                ("HR_EMP_SALARY_STRUCTURE", "HR_SALARY_STRUCTURE", "ID,EMPLOYEE_CODE,EFFECTIVE_FROM,EFFECTIVE_TO,BASIC_SALARY,CURRENCY_CODE,PAYMENT_METHOD,IS_ACTIVE,CREATION_USER,CREATION_DATE,UPDATE_USER,UPDATE_DATE", "ID,EMPLOYEE_CODE,EFFECTIVE_FROM,EFFECTIVE_TO,BASIC_SALARY,CURRENCY_CODE,PAYMENT_METHOD,IS_ACTIVE,CREATION_USER,CREATION_DATE,UPDATE_USER,UPDATE_DATE"),
                ("HR_EMP_SALARY_STRUCT_LINE", "HR_SALARY_STRUCTURE_LINE", "ID,STRUCTURE_ID,COMPONENT_CODE,AMOUNT,PERCENT,IS_ACTIVE,CREATION_USER,CREATION_DATE", "ID,STRUCTURE_ID,COMPONENT_CODE,AMOUNT,PERCENT_VALUE,IS_ACTIVE,CREATION_USER,CREATION_DATE"),
                ("HR_EMP_SHIFT_ASSIGNMENT", "HR_EMPLOYEE_SHIFT_ASSIGNMENT", "ID,EMPLOYEE_CODE,SHIFT_CODE,EFFECTIVE_FROM,EFFECTIVE_TO,IS_ACTIVE,CREATION_USER,CREATION_DATE,UPDATE_USER,UPDATE_DATE", "ID,EMPLOYEE_CODE,SHIFT_CODE,EFFECTIVE_FROM,EFFECTIVE_TO,IS_ACTIVE,CREATION_USER,CREATION_DATE,UPDATE_USER,UPDATE_DATE") })
            {
                var before = await Count($"SELECT COUNT(*) FROM DEV_TEMPLATE.{map.Item2}");
                // Retain original tables and stable IDs; repeat runs insert only missing IDs.
                await Run($"INSERT INTO DEV_TEMPLATE.{map.Item2} ({map.Item3}) SELECT {string.Join(',', map.Item4.Split(',').Select(c => "s."+c))} FROM DEV_TEMPLATE.{map.Item1} s WHERE NOT EXISTS (SELECT 1 FROM DEV_TEMPLATE.{map.Item2} t WHERE t.ID=s.ID)");
                var after = await Count($"SELECT COUNT(*) FROM DEV_TEMPLATE.{map.Item2}");
                report.Add($"Migrated {map.Item1} -> {map.Item2}: added {after-before}, total {after}; original retained.");
            }
            await transaction.CommitAsync();
        }
        foreach (var table in new[] { "HR_SALARY_STRUCTURE", "HR_SALARY_STRUCTURE_LINE", "HR_EMPLOYEE_SHIFT_ASSIGNMENT" })
            if (await Count($"SELECT COUNT(*) FROM ALL_TAB_IDENTITY_COLS WHERE OWNER='DEV_TEMPLATE' AND TABLE_NAME='{table}' AND COLUMN_NAME='ID'") > 0)
                await Run($"ALTER TABLE DEV_TEMPLATE.{table} MODIFY (ID GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))");

        var hrScreen = await db.Set<SysScreen>().FirstOrDefaultAsync(s => s.ScreenCode == "hr-employees");
        var hr = await db.Set<SysSystem>().FirstOrDefaultAsync(s => s.Id == hrScreen!.SystemId)
            ?? throw new InvalidOperationException("HR system registration is missing.");
        var featureCodes = new[] { "view", "create", "edit", "delete", "approve", "reject", "export", "import", "post", "reverse", "link-user", "configure" };
        foreach (var code in featureCodes)
            if (!await db.Set<SysFeature>().AnyAsync(f => f.FeatureCode == code))
                db.Add(new SysFeature { FeatureCode = code, FeatureName = code, FeatureNameE = code, IsActive = true, CreationUser = "HR_REPAIR", CreationDate = DateTime.UtcNow });
        await db.SaveChangesAsync();
        foreach (var code in new[] { "employees", "attendance", "attendance-corrections", "leaves", "loans", "payroll", "payroll-adjustments", "payroll-policies", "salary-components", "work-calendars", "payroll-posting" })
        {
            var screen = await db.Set<SysScreen>().FirstOrDefaultAsync(s => s.ScreenCode == "hr-" + code);
            if (screen == null)
            {
                screen = new SysScreen { ScreenCode = "hr-"+code, ScreenName = code, ScreenNameE = code, SystemId = hr.Id, IsActive = true, CreationUser = "HR_REPAIR", CreationDate = DateTime.UtcNow };
                db.Add(screen); await db.SaveChangesAsync();
            }
            foreach (var feature in await db.Set<SysFeature>().Where(f => featureCodes.Contains(f.FeatureCode)).ToListAsync())
                if (!await db.Set<SysScreenFeature>().AnyAsync(sf => sf.ScreenId == screen.Id && sf.FeatureId == feature.Id))
                    db.Add(new SysScreenFeature { ScreenId = screen.Id, FeatureId = feature.Id });
            await db.SaveChangesAsync();
        }
        report.Add("HR screens and explicit operation features registered. No role/user grants were added.");
    }
}
